### ISSUE TITLE
TAB completion of help command shouldn't list commands with :: prefix

### ISSUE THREAD

**Issue by MBilderbeek** [openMSX/openMSX#1027]
if you type
`help [TAB]`
you also get all global commands listed with the `::` prefix. But that doesn't give any useful results...

E.g. `help ::reverse` gives no useful result, although `::reverse` is listed when you type `help [TAB]`.

This behaviour was not present in openMSX 0.11.0.

**Comment by ghost** [comment]
This issue seems to have started between interim builds openMSX 0.11.0-254 and openMSX 0.11.0-256, on 9-Jul-2015.
The following two commits seem to have made the changes responsible for this: 39fb861313a3fc33e382dddcc0679721b4b5830d 731b01b9de2b9a6d9caa781ea2f661b539d6222e

You don't need to type `help` either, if you just hit tab on an empty command line, it will display every command twice, once with leading colons, once without.
Note that while `help ::reverse` doesn't work, `::reverse` itself works fine.
