### ISSUE TITLE
NVIDIA Shield control only works for interface

### ISSUE THREAD

**Issue by CosmeFC** [openMSX/openMSX#1040]
It does not work for game

**Comment by MBilderbeek** [comment]
Thanks for your report, but to be honest, I haven't got a clue what you are talking about. Please provide more info:
- what are you trying to do? What happens? What did you expected instead?
- on which system are you doing this? (OS, hardware)
- what do you mean with interface?
- what game are you talking about?

**Comment by CosmeFC** [comment]
I am trying to play old MSX games.
I can use NVIDIA controller for NVIDIA SHIELD.
It works on the interface, selecting files, but it is dead for running games.
My system is a Nvidia Android TV.
Several games. Try The Castle.

Thank you for your interest.

**Comment by MBilderbeek** [comment]
I tried The Castle, and the game doesn't respond to any joystick input to start it. Once it's started, it will respond to joystick input.

Your NVidia controller is used as MSX joystick. If the MSX software doesn't respond to MSX joystick, it will not work... that is the problem here. Try some other games which do respond to joystick to start them.

**Comment by MBilderbeek** [comment]
Better close it, as this doesn't seem to be an openMSX bug after all. @CosmeFC please reopen if you think otherwise.
