### ISSUE TITLE
Inconsistent support for the different slot conector formats

### ISSUE THREAD

**Issue by sdsnatcher** [openMSX/openMSX#1075]
Some machines have the 2nd slot connector in the "expansion bus" format.

I noticed that, for some reason, the XML files of some MSX machines have this slot connector commented out, eliminating a connector that exists on the real machine. These are some of the cases I found:

- Fenner SPC-800
- Sanyo MPC-6
- Toshiba HX-10D

This isn't an exhaustive list. There might be others.

OTOH, other machines have the very same kind of slot connector and their slot is present in the XML file. I.e.:

- Daewoo DPC-100
- Toshiba HX-10

But the expansion BUS is a perfectly normal MSX slot with a different shape. It's easy to connect an adaptor to connect cartridges there.

Going further, I noticed that the issue of the shape of the slot connector is totally inconsistent, leaving margin to confuse the user. For example:

1) Some machines have expansion bus connectors that work as a normal slot on openMSX
2) Some machines have expansion bus connectors that are commented to make impossible to connect cartridges there
3) The 2nd slot of the Yamaha CX5M is just a male EDGE connector and the XML file of this machine allows normal cartridges to be connected there
3) The 3rd slot of the Yamaha CX5M is a proprietary 60-pin connector and yet it's exposed as a normal connector by this machine's XML file. The same goes for all machines that have this proprietary connector.
5) The 2nd slot of the Fujitsu FM-X is a proprietary 60-pin connector (probably different from the Yamahas) and it's commented to make impossible to connect cartridge there
6) The Yamaha SFG-01 and SFG-05 extensions can be connected to any MSX, regardless if they have the proprietary Yamaha 60-pin connector or not

IMHO, I find the approach of being strict about the shape of the connector a bit dangerous (*1) and that all slot shapes should be equally available, specially because on real machines anyone can easily make dumb adapters between them. 

*1: Making it strict would also mean that openMSX should include the dump adapter extensions between the shape formats, but that wouldn't do anything else other than make the life of users even more confusing and unnecessarily complicated and add code that would do nothing but require maintenance.

**Comment by MBilderbeek** [comment]
You're right, it's inconsistent.

I see several options:
1. Make all slots available as normal slots and document in the XML file that it's in reality not a normal slot (instead of commenting out the slot).  Rationale: 1. it's very convenient for most user 2. as FRS wrote, it's justifiable as these slots carry all normal cartridge slot signals (except from SNDIN exceptions here and there, but that's another topic)
2. Make none of the non-standards slots available as cartridge slots. Rationale: you can't just use them on a real MSX either without extra effort. However, this means you can't use them at all, which is not very convenient.
3. Make separate types of (incompatible) interfaces for all types. This is the most realistic one, it works just like the real stuff. But what does this add? (See the last paragraph of FRS's text above.) It basically adds only strictness without really helping a lot. IMHO, documenting the differences in the XML file with comments is good enough.
4. Keep it as it is now.

I like option 1 best. What about the others?

**Comment by m9710797** [comment]
I was totally unaware of these special connectors. But now that you (both)
explained it, i tend to agree with option 1 in Manuel's list.

On Thu, Aug 17, 2017 at 9:10 PM, Manuel Bilderbeek <notifications@github.com

**Comment by MBilderbeek** [comment]
OK, I implemented proposal 1. Except for the Fujitsu FM-X, as I have no idea whether that slot is really possible to convert into a normal MSX cartridgeslot at all. Also, the stuff for that slot is not emulated at all (in contrast to the Yamaha unit slot, for which we emulate the SFG-01/05).

If there are any more issues or comments, please add them here. We can always reopen the ticket if there are new insights.
