### ISSUE TITLE
Failed to compile openmsx mac os sierra.

### ISSUE THREAD

**Issue by retrocant** [openMSX/openMSX#1082]
I'm having problems compiling openmsx in binary, I have the libraries installed less ALSA with which I can not compile, I need help to compile properly on Mac OS Sierra.
![captura de pantalla 2017-09-04 a las 22 12 44](https://user-images.githubusercontent.com/23484201/30058644-3ad3cf2e-923c-11e7-8bc3-d5010b57aed4.png)
![captura de pantalla 2017-09-04 a las 22 14 43](https://user-images.githubusercontent.com/23484201/30058656-45859df8-923c-11e7-9ffd-08db7d6fc3eb.png)
![captura de pantalla 2017-09-04 a las 22 18 21](https://user-images.githubusercontent.com/23484201/30058658-47fda35a-923c-11e7-8e93-ec9d2a8cb082.png)

**Comment by mthuurne** [comment]
ALSA is Linux-only and is not required. The problem here is that while a Tcl library was found, linking to it didn't give access to the `Tcl_CreateInterp()` function for some reason. If you want to look deeper into this, take a look at the `derived/tcl-search.log` log file, which lists where Tcl was found and what compile and link flags were detected for it.

However, what I would recommend instead is to compile using [`make staticbindist`](http://openmsx.org/manual/compile.html#standalone), since that will compile all required libraries for you as well. It is the easiest way to compile on Mac OS and also how we produce the nightly builds and releases.

**Comment by fxcoudert** [comment]
macOS has Tcl and it can be used in the build. Can you modify the configure system so specific directories for Tcl can be passed as options?

**Comment by mthuurne** [comment]
In eeb74206 we added support for passing the directory containing `tclConfig.sh` through an environment variable.

**Comment by MBilderbeek** [comment]
Can I assume this issue is solved? Please let me know. If not, I'll close this issue.

**Comment by retrocant** [comment]
closed

**Comment by MBilderbeek** [comment]
OK, thanks.
