### ISSUE TITLE
help in compiling openmsx for windows

### ISSUE THREAD

**Issue by retrocant** [openMSX/openMSX#1085]
greetings, I would like to know how to compile openmsx for windows 64 bit and with that necessary tools necsito many thanks.

**Comment by MBilderbeek** [comment]
Have you read the compilation guide on
http://openMSX.org/manual/compile.html ?

If yes, please be more specific...


Op 20 sep. 2017 12:06 PM schreef "retrocant" <notifications@github.com>:

greetings, I would like to know how to compile openmsx for windows 64 bit
and with that necessary tools necsito many thanks.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/openMSX/openMSX/issues/1085>, or mute the thread

**Comment by MBilderbeek** [comment]
Please let us know if you need more specific help. If not, I'll close this issue.

**Comment by MBilderbeek** [comment]
No updates, so closing.
