### ISSUE TITLE
LS or DIR command 

### ISSUE THREAD

**Issue by artrag** [openMSX/openMSX#1090]
Pressing F10 in Openmsx under Android, I often use the CD command to locate the directory where ROM files are stored.
I cannot find a DIR or LS command, so I need to swap Openmsx with an Android file manager to be sure I'm in ther right directory and to read the exact name of the file I need.
Would it be possible to add a DIR or LS command in the command line?

**Comment by MBilderbeek** [comment]
First of all, I use the TAB key for that, it tries to complete filenames and directories and shows you what's in the current directory. Did you try that? No need to cd, just tab away and use paths like ../../ if necessary.

When loading ROMs, you can of course also use the built in file browser you get when selecting the "Load ROM" option of the main menu. No need to type there either. Why not use that?

Anyway, in a Tcl shell, you can use the `glob` command to find files. See http://wiki.tcl.tk/1474
So, `glob *` shows the files in the current folder. You could make an alias to that like this: `proc ls {} {glob *}`
But I think it's still easier to make better use of the TAB key of your Hacker's Keyboard or of course the main menu. Should save you a lot of nasty typing and searching.

**Comment by m9710797** [comment]
Manuel already gave a pretty good answer. I'll only make some small
additions.

If you want to implement a ls-like command in Tcl, you should indeed use
the 'glob' command. 'glob *' is a good start but the output could be better
formatted. Though instead of reinventing the wheel it might be better to
just use the native 'ls' command like this:  'exec ls'.

I'm not sure we should add an 'ls' command in openmsx. The alternatives are
easy enough.

Wouter

**Comment by Vampier** [comment]
“exec ls” won’t work on windows

**Comment by NYYR1KK1** [comment]
On Windows you can use "exec cmd /c dir"

**Comment by MBilderbeek** [comment]
@artrag Can this issue be closed or do you still think we need to add a command?

**Comment by artrag** [comment]
sure, exec ls on android works fine
thanks!
