### ISSUE TITLE
Additional info needed for "Unsafe PSG port directions" event

### ISSUE THREAD

**Issue by Wierzbowsky** [openMSX/openMSX#1100]
This is a feature request. The OpenMSX sometimes shows a message: "The running MSX software has set unsafe PSG port directions. Real (older) MSX machines can get damaged by this". As this is a real threat to older MSX computers, it would make sense for the emulator to provide additional information on this event:

- the PC register value (address) of the command that set unsafe PSG settings
- the unsafe value that was set
- current slot configuration

This data could be output into the "Statis info" tab of the emulator.

This will help to find and fix such bugs in the known software. For example the original game "train.rom" from Sony triggers this event. Knowing the address and the bad value will help to fix this bug and create a safe rom to be used in real MSXs.

**Comment by mthuurne** [comment]
It is possible to customize the code executed when this event happens, using the `invalid_psg_directions_callback` setting. For example this should (I didn't test it) freeze execution when the event happens, so you can attach the openMSX Debugger and investigate where in the program the OUT came from:

    set invalid_psg_directions_callback {debug break}

**Comment by Wierzbowsky** [comment]
Thanks. Where exactly should this code be placed? I am not a professional programmer, so I am not sure that I can compile custom binaries.

**Comment by Vampier** [comment]
in windows push f10 within openMSX. See here for a quick tutorial how to use the console with TcL (scripting engine for openMSX) - you don't have to be a prof programmer 

https://www.youtube.com/watch?v=k34vsDNF4DI

**Comment by Wierzbowsky** [comment]
Oh, that was a console command? I didn't realize that. Then I can really use it to stop at that event. Will verify tonight. Thanks.

**Comment by Wierzbowsky** [comment]
Unfortunately this command doesn't work. It says: invalid command name "debug break".

**Comment by mthuurne** [comment]
Maybe drop the curly brackets? I'm not very good with Tcl.

    set invalid_psg_directions_callback debug break

**Comment by m9710797** [comment]
It seems callbacks should be a single command name without parameters. (The command "debug<space>break" doesn't exist. But there is  a command "debug" that accepts the parameter "break"). 

As a workaround you can define a proc like this:
    proc my_debug_break {} { debug break }
and then register that (single command without parameters) in the callback:
    set invalid_psg_directions_callback my_debug_break

Background info: some callbacks (not this one) pass extra parameters to the given command. That's why currently the given string is interpreted as the (single) command name instead of a full command with parameters.

**Comment by Wierzbowsky** [comment]
The last suggestion worked, thanks! I still recommend to implement an easier way to trigger debug breaks on such events.

**Comment by MBilderbeek** [comment]
The point of the setting was that you can assign a Tcl proc to be called when this event happens. The default proc prints that warning, but any other proc can be used to replace it. In the above case @m9710797 created a new proc that has 'debug break' as only implementation. 

So the mechanism is very generic and simple. But it does require a bit of Tcl knowledge, or at least of how this works in openMSX :) 

As the help also says:

> Setting invalid_psg_directions_callback:
Tcl proc called when the MSX program has set invalid PSG port directions

**Comment by Wierzbowsky** [comment]
Ok, as the workaround exists, I am closing this ticket.

**Comment by mcolom** [comment]
Hi all. Even if it's possible to use a TcL function to break the debugger, indeed wouldn't it be really useful that the message prints at least the PC?

It's just changing slightly the printed message:
message [format "The running MSX software has set unsafe PSG port directions.
Real (older) MSX machines can get damaged by this. PC=0x%04X" [reg PC]] warning

I know this issue is closed and that there are workarounds, but I don't see why printing the PC should be avoided. It's really useful, and to me it's like weird to read a message saying that an invalid PSG direction was set, but not saying where even if this information is available.

**Comment by MBilderbeek** [comment]
If you want to debug such issues, wouldn't it be easier to just set the proc with 'debug break' and then check with the debugger what's going on and where?

**Comment by mcolom** [comment]
Well, for me it's simpler if the message already tells where the problem is.
But I understand that the point of the current message is to tell common users "Hey, be careful with this software, because it could fry your real machine", instead of providing any technical information. If showing PC=xxxx is annoying or looks scary for common users, then yes... I agree that it shouldn't be shown.
But it's a pity for developers, because you need to know about what is explained in this issue (that's why I ended up here where looking for info) to really take advantage of this really useful warning feature. I agree with Wierzbowsky that it'd be good to have a simpler mechanism. For example, something like "set break_on_unsafe_psg true" in the console, and add it to the documentation.

**Comment by m9710797** [comment]
The 'best' solution will be different for different people.
* For many users this message is not useful at all. E.g. they just want to play a game, and might get scared by a message they don't understand (or they get annoyed by a message that's not useful for them).
* For developers (of new MSX software) the message is valuable, and may not be detailed enough.

So it's a tradeoff, and it's difficult to find the right balance.
To make it possible to satisfy both extremes, we made the behavior configurable. But this of course shifts the problem to picking the right default behavior.

My personal opinion is that the default behavior should be somewhere in the middle, but maybe slightly tilted towards novice users (who don't know how to configure callbacks) than towards developers (who can be expected to learn about callbacks). On the other hand, only adding "PC=0x1234", like you suggested, might still be a good middle ground. I'm not sure.

I don't like your second suggestion to have a "break_on_unsafe_psg" setting. The current mechanism is more flexible: it allows you to do anything, not just print a message, or "debug break". And the current callback mechanism is already documented. I guess the problem is more that the documentation is not easy to find. (And your 'break_on_unsafe_psg" suggestion does not solve this documentation problem).

**Comment by mcolom** [comment]
> The 'best' solution will be different for different people.
> 
> * For many users this message is not useful at all. E.g. they just want to play a game, and might get scared by a message they don't understand (or they get annoyed by a message that's not useful for them).

I think it's still useful for common users. Some of them might be just gamers who use both openMSX and their real machines, and for them, even if they don't know what the PSG directions are, still the message is clear "this could damage your real machine". It can save some machines :)

> * For developers (of new MSX software) the message is valuable, and may not be detailed enough.
> 
> So it's a tradeoff, and it's difficult to find the right balance.
> To make it possible to satisfy both extremes, we made the behavior configurable. But this of course shifts the problem to picking the right default behavior.
> 
> My personal opinion is that the default behavior should be somewhere in the middle, but maybe slightly tilted towards novice users (who don't know how to configure callbacks) than towards developers (who can be expected to learn about callbacks). On the other hand, only adding "PC=0x1234", like you suggested, might still be a good middle ground. I'm not sure.

Yes, it's a question of finding the right balance.
That's why I suggested having a simple setting that one can configure in the console.

> I don't like your second suggestion to have a "break_on_unsafe_psg" setting. The current mechanism is more flexible: it allows you to do anything, not just print a message, or "debug break". And the current callback mechanism is already documented. I guess the problem is more that the documentation is not easy to find. (And your 'break_on_unsafe_psg" suggestion does not solve this documentation problem).

To me both are compatible. I mean, I agree that writing your TcL handler is more configurable, no doubt about that. But to me it's like having to add extra code to do what most of the time will be adding a break for the debugger to fix an undue OUT. Perhaps others might need more than this, but I don't think it'd be that common.

I think that having an option that activates automatically breaking on invalid PSG is a good solution, because it's really low-level and very simple (no need to TcL coding and only does a very particular thing). Of course, nothing prevents that people use their own TcL handlers if they need to do more complex stuff (with  invalid_psg_directions_callback, that indeed is in the doc).
