### ISSUE TITLE
Feature request: Add scrollbar to console window

### ISSUE THREAD

**Issue by NYYR1KK1** [openMSX/openMSX#1112]
Many commands output such a lot of stuff that even using "set consolerows" does not help. A scrollbar would help a lot.

**Comment by m9710797** [comment]
Quick question: Do you know about the PgUp/PgDown and SHIFT+PgUp/PgDown key
bindings?
Is this already sufficient for your needs? I'm asking because adding
scrollbars is not straight forward in the current console code. And (for me
personally) it would have zero benefit (if I'm typing in the console I want
to scroll with the keyboard, not switch between mouse and keyboard).

**Comment by NYYR1KK1** [comment]
No, I didn't... (or at least I didn't remember) Yes, this will help a lot! Scrollbar would be much more intuitive to find & use, but this workaround is ok for me,

**Comment by MBilderbeek** [comment]
OK, then we can close the ticket. Thanks :)
