### ISSUE TITLE
OpenMSX fails to load CAS file

### ISSUE THREAD

**Issue by Wierzbowsky** [openMSX/openMSX#1120]
The latest build of OpenMSX (RELEASE_0_14_0-330-g39f536183) fails to start the CAS file. The UI shows the command typed and run in Basic, but nothing more happens. The CAS file can be found here:

http://podrezov.com/temp/storm.cas

Sorry if this is a trivial issue, but I can't fix my OpenMSX to load this file.

**Comment by MBilderbeek** [comment]
It runs fine on exactly that version here. So, I'm not sure what's going on on your system. Do you see the Found: prompt? If yes, it's may be an incompatible MSX model, try a Toshiba HX-10, works on that one guaranteed. OTOH: there's a basic loader, so you should then at least see "STORM iS LOADING"

**Comment by Wierzbowsky** [comment]
No reaction at all on CAS or WAV files. Tried several machines - nothing gets loaded. Do we have a complete MSI package with the installer? I would like to make a clean installation. Maybe my current setup is busted?

**Comment by Wierzbowsky** [comment]
Found the installer for OpenMSX 0.14.0 x64. With the vanilla installation everything works fine. But after I replace the "openmsx.exe" file with the latest "openMSX64.exe", nothing gets loaded via cassette interface.

**Comment by Wierzbowsky** [comment]
Thanks! I was not aware of that and the build location. I made a clean install with the MSI file. Now the game and other software loads fine.

I noticed that the full-throttle speed (after you press F9) is way slower than it was before. Not it takes ages to load a multi-file game via cassette interface. Was that change intentional?

**Comment by MBilderbeek** [comment]
I'm not aware of such a change. It would be very useful if you could find out which change caused it. 0.14.0 was still fast?
Perhaps you can bisect the change that caused it using these installer packages. That would be immensely helpful to find out the cause.

**Comment by Wierzbowsky** [comment]
Ok, will try. Please close this ticket.

**Comment by MBilderbeek** [comment]
You know how to bisect? It should take you only about 8 installs to find the first version that has the issue.

**Comment by MBilderbeek** [comment]
Indeed. That was a likely candidate, too. I should have asked you about it first.
What PC hardware are you using? 
Also, it could be that you should change the maxframeskip setting to something large like 100, because when using the OpenGL rendering, the framerate could be limited to 60 fps by the driver, slowing down the full-throttle speed (in combination with a low maxframeskip setting). Your CPU will be idling a lot even though it's doing things as fast as possible, simply getting delayed by the max framerate of 60fps.

**Comment by MBilderbeek** [comment]
Sure: http://openmsx.org/manual/commands.html#maxframeskip
But I will add something about OpenGL framerate somewhere, I think. Not sure yet what is the best place.

**Comment by mthuurne** [comment]
I think this is more about `throttle` than about `maxframeskip`. The two are tied together currently in implementation, but conceptually `maxframeskip` is the maximum number of frames the emulation should skip if it is lagging behind real time, while `throttle` is for being able to turn on/off realtime sync. What the user actually wants is fast-forward, which is a third concept.

The `throttle off` mode has become less useful as there is more variation in computation speed between devices. It should probably become a feature for scripting in headless mode instead of something bound to a function key.

Fast forward should then be done by explicitly asking for a speed, like 100x normal. Video output should be done at ~60 fps regardless of how fast the emulated machine is running.
