### ISSUE TITLE
MSX-AUDIO PCM BUSY flag does not work

### ISSUE THREAD

**Issue by grauw** [openMSX/openMSX#1124]
The Y8950 MSX-AUDIO PCM BUSY flag (status bit 0) should go high while register 7 (ADPCM control) bit 7 (START) is set, and go low again when it’s unset. It does not generate an IRQ. This is documented on page 35 of the application manual.

Current openMSX implementation never changes this flag. It’s preventing me from simplifying the MSX-AUDIO detection in VGMPlay MSX greatly. Would be nice if it was fixed in the pending release, then I won’t have to hold back on this change.

Test case: [vgmplay.com.zip](https://github.com/openMSX/openMSX/files/2593295/vgmplay.com.zip)

Just play any MSX-AUDIO VGM (e.g. track 03 from [Psycho Soldier](http://vgmrips.net/files/Arcade/Psycho_Soldier_%28SNK_Triple_Z80%29.zip)), and observe the MSX-AUDIO is not detected, resulting in silence.

See [here for the corresponding code change](https://bitbucket.org/grauw/vgmplay-msx/commits/9d3ef340b9387db40a29a9cec5c2bcad9f392388) which does work on real MSX (both MSX-AUDIO and the OPNA which uses the same ADPCM unit), but not in openMSX.

**Comment by m9710797** [comment]
Implemented in 7c458d06cd50d898.
I've implemented it as requested, but didn't verify against real hardware.
I still have a question: is status bit 0 a one-to-one mirror of R#7 bit 7? Or does the status bit go to zero when the sample finishes?

**Comment by grauw** [comment]
Great!

The documentation says literally:

> During ADPCM voice synthesis/analysis, this bit is set to “1” when bit D7 of address $07 becomes “1”. No IRQ is generated by this setting.

The sentence can be interpreted in two ways I think, either to mean that D7 of $07 implies “during”, or to mean that with D7 of $07 being set, “during” a certain time span it will stay high.

I did the following test on my Music Module (after loading Psycho Soldier track 03 samples into memory with VGMPlay so I could actually hear something 🙂):

```
100 OUT &HC0,&H7:OUT &HC1,&H20
110 OUT &HC0,&H8:OUT &HC1,&H0
120 OUT &HC0,&H9:OUT &HC1,&H0
130 OUT &HC0,&HA:OUT &HC1,&H0
140 OUT &HC0,&HB:OUT &HC1,&HFF
150 OUT &HC0,&HC:OUT &HC1,&H1F
160 OUT &HC0,&H10:OUT &HC1,&HEC
170 OUT &HC0,&H11:OUT &HC1,&H51
180 OUT &HC0,&H12:OUT &HC1,&HFF
190 GOSUB 280
200 OUT &HC0,&H7:OUT &HC1,&HA0
210 GOSUB 280
220 OUT &HC0,&H7:OUT &HC1,&HA1
230 GOSUB 280
240 OUT &HC0,&H7:OUT &HC1,&H0
250 GOSUB 280
260 PRINT
270 END
280 PRINT RIGHT$("0000000"+BIN$(INP(&HC0)),8);CHR$(13);
290 IF INKEY$="" THEN 280
300 RETURN
```

After I set D7 of $07 (line 200) the status register PCM BUSY flag continuously remains at 1 even after the sample has finished, until I unset it again (line 240).

To be clear, the output for the four GOSUBs is, regardless of how long you wait:

```
00000110
00000111
00000111
00000110
```

So the current implementation seems correct.

(Although I haven’t been able to test 7c458d0 yet, because I’m getting a blank screen with my builds. Something to do with MacOS 10.14, OpenGL and XCode 10.)

**Comment by grauw** [comment]
I tried build bb6160176 from niekniek’s build server, and the test program does not give the expected output (nor does VGMPlay detect the MSX-AUDIO).

**Comment by grauw** [comment]
Because of the statusMask in peekStatus()? Since the mask bits only affect status bits 3-6, I think:

```
return (status & (0x80 | statusMask)) | 0x06;
```

Should be:

```
return (status & (0x87 | statusMask)) | 0x06;
```

Also changeStatusMask() does not seem to be correct:

```
	statusMask = newMask;
	status &= statusMask;
	if (status) {
		status |= 0x80;
		irq.set();
	} else {
		status &= 0x7f;
		irq.reset();
	}
```

Should be something like:

```
	statusMask = newMask;
	status &= 0x87 | statusMask;
	if (status & statusMask) {
		status |= 0x80;
		irq.set();
	} else {
		status &= 0x7f;
		irq.reset();
	}
```

Finally these lines in Y8950Adpcm::writeReg() need to be modified:

```
		if (reg7 & R07_RESET) {
			reg7 = 0;
		}
```

They make the output of the test program go back to 00000110 in the third step rather than the fourth.

**Comment by grauw** [comment]
Patch: [ym8950adpcm-pcmbusy.diff.zip](https://github.com/openMSX/openMSX/files/2633951/ym8950adpcm-pcmbusy.diff.zip)

```
diff --git a/src/sound/Y8950.cc b/src/sound/Y8950.cc
index b167900a1..72bf3670c 100644
--- a/src/sound/Y8950.cc
+++ b/src/sound/Y8950.cc
@@ -1222,7 +1222,7 @@ byte Y8950::readStatus(EmuTime::param time)
 byte Y8950::peekStatus(EmuTime::param time) const
 {
 	const_cast<Y8950Adpcm&>(adpcm).sync(time);
-	return (status & (0x80 | statusMask)) | 0x06; // bit 1 and 2 are always 1
+	return (status & (0x87 | statusMask)) | 0x06; // bit 1 and 2 are always 1
 }
 
 void Y8950::callback(byte flag)
@@ -1253,8 +1253,8 @@ byte Y8950::peekRawStatus() const
 void Y8950::changeStatusMask(byte newMask)
 {
 	statusMask = newMask;
-	status &= statusMask;
-	if (status) {
+	status &= 0x87 | statusMask;
+	if (status & statusMask) {
 		status |= 0x80;
 		irq.set();
 	} else {
diff --git a/src/sound/Y8950Adpcm.cc b/src/sound/Y8950Adpcm.cc
index ec420638f..1cbd40b1d 100644
--- a/src/sound/Y8950Adpcm.cc
+++ b/src/sound/Y8950Adpcm.cc
@@ -153,6 +153,11 @@ void Y8950Adpcm::writeReg(byte rg, byte data, EmuTime::param time)
 	switch (rg) {
 	case 0x07: // START/REC/MEM DATA/REPEAT/SP-OFF/-/-/RESET
 		reg7 = data;
+		if (reg7 & R07_START) {
+			y8950.setStatus(Y8950::STATUS_PCM_BSY);
+		} else {
+			y8950.resetStatus(Y8950::STATUS_PCM_BSY);
+		}
 		if (reg7 & R07_RESET) {
 			reg7 = 0;
 		}
@@ -160,9 +165,6 @@ void Y8950Adpcm::writeReg(byte rg, byte data, EmuTime::param time)
 			// start ADPCM
 			restart(emu);
 			restart(aud);
-			y8950.setStatus(Y8950::STATUS_PCM_BSY);
-		} else {
-			y8950.resetStatus(Y8950::STATUS_PCM_BSY);
 		}
 		if (reg7 & R07_MEMORY_DATA) {
 			// access external memory?
```

Tested with a local build using savestate screenshots to work around #1126 😄.

**Comment by m9710797** [comment]
Thanks. I've reviewed your patch and applied it.

But I still wonder how exactly the combination of START (bit 7) and RESET (bit 0) in register R#7 should behave.

**Comment by grauw** [comment]
Confirmed fixed.

About START and RESET, I wondered too, I think the ADPCM unit implementation could probably use some thorough evaluation. One could look at [YM2608 ADPCM implementations](https://github.com/mamedev/mame/blob/master/src/devices/sound/ymdeltat.cpp#L166) since it’s near identical (though that one also doesn’t seem to implement PCM BUSY correct). I limited my change to minimally modify the current implementation to get the observed behaviour for PCM BUSY.

Perhaps RESET just clears the MEMORY DATA flag since it’s only relevant for external memory playback. I also noticed on the real thing that if I stop without resetting first (comment out line 220 of the test program), start doesn’t play the sample anymore. Although I did no further tests, I think it may get stuck at the end of sample state, and START does not reset the memory pointer.

**Comment by Eugeny1** [comment]
I'd second @grauw report about clicks when operating start/stop. I did the following test: perform manual start through "Generic MSX-Audio regs" debuggable (writing $A0 into reg $07), and manual stop writing $00 into reg $07 somewhere in the middle of the sample. I get the following waveform when stopping:

![adpcm-waveform-zero](https://user-images.githubusercontent.com/12286988/51865280-dfc68600-2356-11e9-9ec3-eb0b087c6d43.gif)

This one is made using

    record_channels "Generic MSX-Audio" 15

You can see that at the interruption waveform goes to 0 sharply, however registers $13/$14 still show non-zero value.

In general handling this sample value reset is tricky one: there're ADPCM samples which do not finish at 0, thus if resetting to 0 at their end will cause popping sound at the end, however resetting at the start of the next sample causes this popping sound at the beginning of this next sample.

IMHO the main task here is to figure out how real Y8950 performs (ideally attenuates envelope exponentially towards 0 according to sampling rate), and then ensure we emulate it properly. I have no real audio module, thus unable to troubleshoot further...

Second question is why openMSX has this sharp drop to 0 as code clearly shows that sample value reset occurs at the *start* of the new sample, not at the end of current one.

**Update**: I found out the cause of the drop to the 0:

    int Y8950Adpcm::calcSample()
    {
    	// called by audio thread
    	if (!isPlaying()) return 0;          <-------------------------
    	int output = calcSample(false);
    	return (reg7 & R07_SP_OFF) ? 0 : output;
    }

As soon as bit 7 of `reg07` gets reset to 0, `isPlaying()` returns false, and `calcSample()` immediately returns 0 as next and further samples causing the popping sound. Then popping sound will not appear at the start of next sample because the contents of `pd.output` is reset when bit 7 of reg 07 is set.

**Update**: here're the tests we have made for start/stop operation - when ADPCM playback is interrupted by writing $01 into the register $07. I was doing programming, Leo Oliveira was doing implementation and measurement.

<img width="761" alt="adpcm1" src="https://user-images.githubusercontent.com/12286988/51963422-90767780-2474-11e9-99e5-6cee5e66e9d0.png">
<img width="845" alt="adpcm2" src="https://user-images.githubusercontent.com/12286988/51963426-953b2b80-2474-11e9-89de-d5e4e9a2aa79.png">
<img width="846" alt="adpcm3" src="https://user-images.githubusercontent.com/12286988/51963431-99674900-2474-11e9-8057-bef2138e0b83.png">

The conclusion is that it is really bad idea to abruptly stop ADPCM playback as most of the times waveform goes to some arbitrary high DAC value, causing relatively loud crackling sound. Leo confirms - no known software does that, letting samples play till their end. He mentioned Moonblaster which is used by most applications.

However the most interesting in these waveforms is that after this unextected spike wavform goes exponentially to 0: it is either LPF at the output of the MSX-Audio module (we were measuring at the output of the module, not at the immediate output of the DAC chip), or, after playback stops, Y8950 deliberately  exponentially drives sample value to 0.
