### ISSUE TITLE
scale factor 3 issues in SDLGL-PP

### ISSUE THREAD

**Issue by Vampier** [openMSX/openMSX#1145]
while using scale factor 3 and SDLGL-PP pixels don't have equal sizes like one would expect. Scale Factor 2 and 4 work like expected. The issue is most visible in a 512pixel wide screen mode (0 width 80/6/7) 

![big](https://user-images.githubusercontent.com/12684428/52920768-42130680-32c5-11e9-8312-3d143c57b6e3.png)

Blur 50+ takes a bit away from the issue but this is not ideal. Horizontal stretch doesn't have any impact on the issue.

**Comment by MBilderbeek** [comment]
512-pixel wide modes on a 960-pixel wide host window isn't a very good match... that's what's causing this... @m9710797 can this be improved within our current framework?

**Comment by MBilderbeek** [comment]
@m9710797 Is this also solved now?

**Comment by m9710797** [comment]
No, this is something different.
I think this issue is fundamentally unsolvable. You cannot have interpolation-free (no blur) rendering in combination with a non-integer scale-ratio:
512 msx pixels, with border and stuff that's 640 pixels, and output those on 960 host pixels. Without blurring you cannot do better than leave 2 pixels as is and repeat the 3rd pixel.
Because it's unsolvable, I'm closing this issue. Please reopen if I missed something.
