### ISSUE TITLE
Missing alsa.conf when compiling staticbindist

### ISSUE THREAD

**Issue by nataliapc** [openMSX/openMSX#1150]
Compiled openmsx using ``make staticbindist`` the ``alsa.conf`` file is not loaded from ``/usr/share/alsa/`` folder, instead is used the next path:

``/home/myuser/openMSX/derived/x86_64-linux-opt-3rd/3rdparty/install/share/alsa/alsa.conf``

This string can be found at the raw binary itself using an hexeditor.

Can be fixed this to use ``/usr/share/alsa/`` with a static compilation?

Thanks

**Comment by MBilderbeek** [comment]
@mthuurne Can you comment on this?

**Comment by mthuurne** [comment]
I tried to fix this by passing `--with-configdir=/usr/share/alsa` to the `configure` script of `alsa-lib`, but then `make install` for `alsa-lib` will try to install a lot of configuration files in that directory, which is of course not what we want.

A possible solution is to make `ALSA.isSystemLibrary()` (`build/libraries.py`) return `True`. That will force the 3rdparty build to assume that `alsa-lib` is always available on Linux systems and it will not be built as part of `staticbindist`.

Alternatively, you can work around the problem by exporting the environment variable `ALSA_CONFIG_DIR` with the value `/usr/share/alsa` when you run openMSX.

Can you describe your use case? We've only used `staticbindist` on Linux for OpenDingux and testing so far, so we don't have an idea what people expect from it in other situations.

**Comment by nataliapc** [comment]
As the config file is added to the binary with the full 3rdparty source code path, If I delete de source code folder after the compilation, or copy the binary to other computers, the ALSA config file is not found.

**Comment by mthuurne** [comment]
Yes, I understand why the current behavior is not good. But I'm trying to figure out what would be the right solution.

Overriding the ALSA config dir would require a patch to the source and I like to keep the number of patches to a minimum, since they are a pain to maintain. Also, I'm not sure that using the system configuration directory is the right approach, since that directory might not be present (if there is no `alsa-lib` installed on the target system) or it might be incompatible (if it belongs to a different `alsa-lib` version).

Treating ALSA as a system library (linking to it dynamically) is probably the cleanest solution, so that's the one I'm leaning towards.

What I'm interested in is why you're using `make staticbindist` on Linux, since most Linux users use just `make` instead. Are you building for PCs or embedded targets? What is the reason you want a statically linked binary instead of a dynamically linked one?

**Comment by nataliapc** [comment]
Do what you consider appropriate, I just reported a bug 6 months ago.
