### ISSUE TITLE
openMSX hashs vs MAME hashs

### ISSUE THREAD

**Issue by LodanZark** [openMSX/openMSX#1158]
I was checking randomly some openMSX machine files to check some firmware hash's, and more than once, I've found systems that which had completely different  hash values in comparison to the MAME ones.
 
I am wonder which one side has the most accurate dumps, if openMSX or MAME...

Source:
https://github.com/mamedev/mame/blob/master/src/mame/drivers/msx.cpp

**Comment by m9710797** [comment]
(Sorry for the delay).
It's hard to tell which is more accurate. When openMSX and MAME have different hashes for the same MSX machine, it's still possible that both are correct. Possible explanations for this are:
- Some machines have different revisions with slightly different ROM content.
- Often ROM content is dumped on the MSX machine itself (instead of removing the chips from the machine and e.g. using an EEPROM reader). In some cases there are parts of the memory region were not the actual ROM content is visible but some other memory mapped registers. A typical example of this are MSX disk ROMs which often have the FDC registers mapped somewhere in 0x7ff0-0x7fff region. Depending on the exact dump tool, reading these registers may not always yield the same value. Thus this also results in a different hash value.

We try to be careful when adding new machine configurations to openMSX. But I'm not claiming there are no mistakes. I assume the same is true for MAME.

Do you have any concrete examples where you suspect openMSX is wrong?

**Comment by m9710797** [comment]
I'm closing this report, because it's likely not a bug, and there was no response from the reporter.
Feel free to reopen.
