### ISSUE TITLE
[Feature] Jump in lists in menu with alphanumeric keys

### ISSUE THREAD

**Issue by sdsnatcher73** [openMSX/openMSX#1162]
When selecting a machine, ROM or disk image from the menu system it can take a long while when scrolling through the list. It could be helpful if pressing a key on the keyboard would jump to the first entry starting with that letter. So pressing Y in the machine selection would jump to the first Yamaha machine and P would jump to the first Panasonic machine.

**Comment by MBilderbeek** [comment]
Great idea (I've also thought about it once), working on it.

**Comment by sdsnatcher73** [comment]
The public Mac builds on openmsx.dev are broken since these changes, this is the error that is thrown when opening menu, probably the build area is not completely clean. However if I build it myself the OSD menu works fine, but keys don't register in the console (might be my build setup)

```
Error while (lazily) loading Tcl script: _osd_menu.tcl
invalid command name "clock"
    while executing
"clock milliseconds"
    (in namespace eval "::osd_menu" script line 25)
    invoked from within
"namespace eval osd_menu {

set_help_text main_menu_open   "Show the OSD menu."
set_help_text main_menu_close  "Remove the OSD menu."
set_help_text mai..."
    (file "/Users/peter/Downloads/openMSX.app/share/scripts/_osd_menu.tcl" line 1)
    invoked from within
"source /Users/peter/Downloads/openMSX.app/share/scripts/_osd_menu.tcl"
    (in namespace eval "::" script line 1)
    invoked from within
"namespace eval :: [list source [data_file scripts/$script]]"
warning: Error executing delayed command: invalid command name "clock"
    while executing
"clock milliseconds"
    (in namespace eval "::osd_menu" script line 25)
    invoked from within
"namespace eval osd_menu {

set_help_text main_menu_open   "Show the OSD menu."
set_help_text main_menu_close  "Remove the OSD menu."
set_help_text mai..."
    (file "/Users/peter/Downloads/openMSX.app/share/scripts/_osd_menu.tcl" line 1)
    invoked from within
"source /Users/peter/Downloads/openMSX.app/share/scripts/_osd_menu.tcl"
    (in namespace eval "::" script line 1)
    invoked from within
"namespace eval :: [list source [data_file scripts/$script]]"

```

**Comment by MBilderbeek** [comment]
Thanks for reporting. I worked around it by using another time source in eaa47e34b2424939c52d5b5aa9f42a47a1f95552
Please try again.

**Comment by MBilderbeek** [comment]
Oh, can you try what this gives in that Mac public build, when executing in the console:
` ::tcl::clock::milliseconds`

Just to know what could have been another solution if this gives proper output.

**Comment by sdsnatcher73** [comment]
It gives 1561145748512

**Comment by sdsnatcher73** [comment]
> Thanks for reporting. I worked around it by using another time source in [eaa47e3](https://github.com/openMSX/openMSX/commit/eaa47e34b2424939c52d5b5aa9f42a47a1f95552)
> Please try again.

Will have to wait for a new Mac Build (latest 326 still has the issue)

**Comment by MBilderbeek** [comment]
Yes, use 327 or higher. The latest when it appears :)

Your test result means that `::tcl::clock::milliseconds` would also have worked. Good to know. In Tcl talk that means "the ensemble" wasn't initialized correctly, but the command is still there. It is because of the fact that in staticbindist builds, we do not include the Tcl scripts that come with the Tcl distribution, which are necessary to get a fully working (and supported) Tcl environment. On a normal native build, we link against the system wide Tcl installation, which does have these scripts. There are ways around this (like http://www.rkeene.org/devel/kitcreator/kitbuild/nightly/libtclkit-8.6.9-linux-amd64-kitdll-sdk.tar.gz), but it's simpler to avoid these Tcl commands. The Tcl project is discussion a way to easily ship these extra scripts as well. We might need that at some point in the future.
