### ISSUE TITLE
Compiling 0.15.0 with gcc-4.8.5 results in error

### ISSUE THREAD

**Issue by edevaldo** [openMSX/openMSX#1171]
Compiling openMSX on RedHat 7 (gcc-4.8.5) fails due to compilation errors. 0.14.0 Compiles fine with almost no warnings.
openMSX seems to use C++ constructs not supported by that version of gcc, that may top at C++11 or C++14.
Compiling src/utils/strCat.hh results in many warnings and errors. The first error make the problem clear:
src/utils/strCat.hh:534:49: error: ‘std::index_sequence’ has not been declared
 size_t calcTotalSizeHelper(const Tuple& t, std::index_sequence<Is...>)
It seems that gcc is not aware of that version of STL.

Not really a critical issue, just a heads up. I'll be stuck with that version for the foreseeable future though.

**Comment by mthuurne** [comment]
It is indeed a case of that version of GCC being too old. Unfortunately RedHat Enterprise has an extremely slow release cycle, which makes it unsuitable for installing up-to-date packages on top of it.

Note that RedHat 8 has GCC 8, but I'm guessing you're not in control of when the system is upgraded. Maybe there is an easy way to install GCC in your user account? You could always compile GCC from source of course; it takes a bit of work but it's not overly complex.

The 0.15.0 documentation states that GCC 4.8 is the minimum version, so that seems to be wrong. It's been bumped to GCC 6 though in the development version, so it looks like this mistake has already been fixed. Thanks for reporting!
