### ISSUE TITLE
[Bug] V9990 Command completion interrupt

### ISSUE THREAD

**Issue by GhostwriterP** [openMSX/openMSX#1173]
Dear openMSX team,
command completion interrupts (CE) appear only to occur at start of display period and after another interrupt has been processed, either line int or vertical retrace. 

[p1_cmd_test.zip](https://github.com/openMSX/openMSX/files/3365637/p1_cmd_test.zip)
Attached you will find a test program (dos file and source)  that should show a green square on the left and a blue square on the right side of the screen.
In openMSX currently only the green square is shown. The blue one is copied too late since it is processed at the line interrupt at line 96 just below the square, were in reality all commands should have been processed before display period even starts.

PS: assemble sources with sjasm =)

**Comment by MBilderbeek** [comment]
Is it possible that these interrupts are not implemented at all, if you look at the current behaviour? I can't find anything about it in the openMSX source code...

**Comment by GhostwriterP** [comment]
Could be, but the CE flag is set, otherwise none of the follow up copy commands would be executed.
Anyway, please implement it ;-), it is one of the nicer features of the v9990, which I plan to exploit.

**Comment by MBilderbeek** [comment]
As Wouter put it:
<wouterv> V9990CmdEngine::cmdReady() is called at the end of each V9990 command ..
<wouterv> that calls V9990::cmdReady(), and that calls V9990::raiseIRQ(CMD_IRQ)
<wouterv> so it seems to be implemented .. i have no idea if it actually works

So, it is implemented, but apparently not working as it should...?

**Comment by GhostwriterP** [comment]
As far a I can tell, it gives the cmd ready interrupt once at the beginning of the display period and at the same time of the line interrupt after that. I think this also happens even when the command is not ready yet, which will cause a mess...  This can be examined by setting the HILINE constant in the source to 8 for example. 
It is indeed not working as it should.

**Comment by m9710797** [comment]
I did some debugging. But as far as I can tell the gfx9000 interrupts are working as expected. I gave the following commands in the openMSX console:
* debug set_bp 0x0100
* debug probe set_bp "Sunrise GFX9000.IRQ" 1 {puts "gfx9000" ; debug break}
* debug set_bp 0x0038

The first triggers when the program actually starts. (And only then I enter the 2nd and 3rd command).
The 2nd will print a message in the openMSX console and break whenever the gfx9000 IRQ status changes. Thus when the IRQ is first generated (not yet when the Z80 accepts it) or when the IRQ is cleared. The 3rd triggers a breakpoint when the Z80 accepts the IRQ.

After that I did 'debug cont' (thus stop at the next breakpoint). Followed by 'debug step' commands. I only traced the first 10 or so (gfx9000) interrupts. But from what I can tell it behaves fully as expected:
* When the gfx9000 IRQ triggers, bit 1 or bit 2 in P#6 (IO port 0x66) is set.
* Reads from IO port 0x66 usually return the value '3' or '5' (I once saw '7'). Although bit 0 is set, it does NOT trigger the IRQ.
* Writes to IO port 0x66 (value 2 or 4) do clear the corresponding bit and do clear the IRQ line if it was the last 'active' bit (bit 0 remains set, but does NOT keep the IRQ active).

I sometimes saw that the ISR is entered with BOTH CE (bit 2) and HI (bit 1) set. In that case the ISR only handles (and only clears) the HI bit. Thus soon after the ISR finishes it triggers again and then handles the CE stuff. So also this works fine (but is maybe unusual).

So I don't know why the test goes wrong. The timing of the emulated v9990 commands IS know to be different than the timing of the real V9990 commands. This will cause the CE interrupt to trigger sooner/later, thus maybe also before/after the HI interrupt triggers. Could this explain the difference you see?

(detail) I don't think it's causing problems in this test, but the code is writing gfx9000 registers both in the ISR and in the main loop with Z80 in EI mode. Would be safer to only write registers inside a DI-block.

**Comment by GhostwriterP** [comment]
"Although bit 0 is set, it does NOT trigger the IRQ" this is correct I turn VI off.

In the test code I change the backdrop colour to blue after CE interrupt has been processed and to black /dark purple after HI interrupt has been processed. 
In all cases the blue comes directly after black/purple indicating that the HI is processed first, which is also given the higher priority in the test code. 

But the CE interrupt is always occurring exactly at the same time as the HI interrupt, regardless the size of the command, they should not coincide like that. 
In addition to above I think the CE is given once at start of display time, at line 0. That is why I put a total of three commands in the test. The first fills the screen with checkered purple tiles, the second places the green tiles and the third places the blue tiles. 
In openMSX the completion of the first command is triggered at line 0, the completion of the second is given at line 96 (HILINE) and the last is given at line 212, hence all coinciding with line interrupts.

It is like the command completion does simply not trigger a IRQ on its own and needs some help ; ) .

**Comment by m9710797** [comment]
> It is like the command completion does simply not trigger a IRQ on its own and needs some help ; )

Aha, now that you phrase it like that, it does ring a bell.

The problem is related to the emulation model that openMSX is build upon. Very much simplified: Internally in openMSX the emulation is driven by the CPU (e.g. Z80), emulation of other devices (e.g. V9990) is only done on-demand. More concrete: when the Z80 is emulated it runs, in emulated time, ahead of the other devices. When at some point the Z80 communicates with the V9990 (e.g. the Z80 executes an OUT instruction) only then we emulate the V9990 till it reaches the same point in emulated time as the Z80.

But there is a complication with devices that can generate interrupts. In the above scenario, without extra "help", after the Z80 does an OUT to the V9990, we start emulating the V9990. This includes V9990 commands, which can generate an interrupt. Though because the Z80 is possibly already much further ahead in time compared to the V9990, it will seem as if the Z80 received the interrupt too late.

To solve this we have the concept of a 'scheduler' in openMSX. Again much simplified: devices that can generate interrupts must tell _in advance_ when those interrupts will occur. With that extra information we can make sure that the Z80 is not emulated past such 'synchronization points'.

We do already schedule the V99x8/V9990 line/vertical interrupts (and other devices that trigger interrupts). But we forgot to do it for the V9990 end-of-command interrupts.

Fixing this does require some work. I'll try to make time for it one of the following weekends.

**Comment by GhostwriterP** [comment]
Splendid!

**Comment by m9710797** [comment]
I added extra synchronization in the V9990 emulation. Now the test case also shows the blue square.

**Comment by MBilderbeek** [comment]
@GhostwriterP wrote on MSX.org "tested the patch for CE implementation and can confirm it is working a lot better now, much appreciated!" So I'm closing this now.

Please reopen if there's still something not working as it should about CE interrupts or open a new ticket if it's something unrelated to CE interrupts. Thanks!
