### ISSUE TITLE
Enter to select ROM/DSK in OSD menu also sends the enter key to MSX

### ISSUE THREAD

**Issue by sdsnatcher73** [openMSX/openMSX#1177]
When navigating the OSD menu with cursor keys and using enter to select a disk (or ROM I presume, but MSX will reboot so less of an issue) the enter key is also sent to the MSX.

This happens to me on MacOS 10.14 with build 366 (build myself). Currently not able to test other platforms.

**Comment by MBilderbeek** [comment]
I can reproduce it. @m9710797 Can you explain why this happens and perhaps also indicate whether it could be avoided?

@peterhanraets is this really a problem in practice? (Although I do agree it's not desired behaviour in general.)

**Comment by sdsnatcher73** [comment]
@MBilderbeek not a big issue but like you set undesired and unexpected. So if there is an easy way to fix it that would be preferable.

**Comment by m9710797** [comment]
@MBilderbeek: this is what happens. Scenario: MSX is running, the OSD-insert-disk menu is open and the cursor is above the name of a disk image. Next the user presses ENTER shortly followed by releasing the ENTER key.

1) The SDL_KEYDOWN case triggers in InputEventGenerator::handle(), this calls handleKeyDown()
1a) This calls triggerOsdControlEventsFromKeyEvent() which (after some more function calls) generates an openMSX 'OsdControlPressEvent'.
1b) The handleKeyDown() function also generates an openMSX 'KeyDownEvent'.
2) Similar for release: now the SDL_KEYUP case triggers
2a) This calls triggerOsdControlEventsFromKeyEvent() which (indirectly) generates an openMSX 'OsdControlReleaseEvent'
2b) And also an openMSX 'KeyUpEvent'

The very first 'OsdControlPressEvent' triggers some Tcl menu stuff which inserts the selected disk and closes the menu. Closing the menu also disables the OSD menu keybindings.

Next the 'KeyDownEvent' gets distributed. We have a priority system for event listeners. This delivers an event first the higher priority listeners and also allows those higher priority listeners to block the event for lower priority listeners. This allows the OSD menu to block events from the MSX  keyboard. Though the OSD menu was just closed, so this blocking is no longer active.

A possible solution is to swap the order in which the events 1a) and 1b) are generated. This introduces a symmetrical problem: in the current order the MSX doesn't receive the event that opens the OSD menu, with the order swapped it will. Though because with the current binding the MSX won't do anything with the 'open-menu' event, this swapped order may be better.

@MBilderbeek: can you try experimenting with this? In InputEventGenerator::handleKeyDown(), swap the order of the calls to triggerOsdControlEventsFromKeyEvent() and distributeEvent().

Note that even with this order swapped, the problem remains for the release events (even if we swap the order of 2a and 2b). But often the MSX enter key will not be pressed when opening the OSD menu, so this event will have no effect. Maybe this can be solved by making the OSD react to key-release instead of key-press events?

**Comment by MBilderbeek** [comment]
@m9710797 The biggest risk of this construction is that operating the OSD menu could interrupt a replay that is going on and as such destroy someone's work...

**Comment by sdsnatcher73** [comment]
Just sondering about this ‘priority’ system and blocking. Are the priorities fixed? Or could the priority be switched so that when in the OSD menu, the OSD has higher priority than the emulation engine and vice versa if emulation is active?

**Comment by m9710797** [comment]
> Are the priorities fixed?

Yes and no.

Yes, keybinding (used by the OSD menu) have always higher priority than msx keyboard input. 

No, in the sense that when the OSD menu isn't active it doesn't block events from reaching the MSX keyboard. In other words the blocking behavior is dynamic.

But this isn't the root cause of the problem. The problem is that there's a race condition between closing the OSD menu (which implies no longer blocking events from the MSX) and delivering the events (including to the MSX).

**Comment by sdsnatcher73** [comment]
How about balancing the odds in favour of the OSD by keeping it active for a short period longer? No idea how tight the race condition is but I guess a delay of even a second would be acceptable (but most likely a shorter delay is enough).

**Comment by m9710797** [comment]
Interesting idea. Though instead of picking some amount of time we can also do something like:
`    after realtime 0 {deactivate_input_layer osd_menu}`
in the `menu_last_closed` proc in `share/scripts/_osd_menu.tcl. This effectively means re-schedule part of the work at the back of the event queue.  This way we don't have to pick a fixed order in the c++ code.
Though it doesn't yet solve the key-release part, and there could be an arbitrary long time between press and release, so any amount of delay we pick is wrong. Should we make the OSD actions trigger on key-release instead of key-press?

**Comment by MBilderbeek** [comment]
Seems to work fine for me now, please confirm! :)

**Comment by sdsnatcher73** [comment]
I can confirm it is fixed.
