### ISSUE TITLE
Adding the capability of loading rom/dsk/whatever files from the command line, but via URL, so the files really live in some external server

### ISSUE THREAD

**Issue by friguron** [openMSX/openMSX#1196]
It would be really useful to load .rom/.dsk files living in some external web server via pure command line parameters. Something like:

_openmsx -carta http://www.msxgames.com/roms/nemesis2.rom_

As far as I've checked there is not such possibility as of now.

**Comment by m9710797** [comment]
You're asking about support for http://, next question will be support for ftp:// or even https://. These are all non-trivial extensions. But does such functionality really belong in openMSX itself? Can't you easily write a wrapper script around wget+openMSX that achieves the same thing?

15 years ago (or more) I had a similar idea, hence in the internal openMSX C++ code, the class that handles (uncompressed) files access is called 'LocalFile'. In principle the design allows to be extended to non-local files. But I changed my mind and I no longer think this belongs in openMSX.

I'm closing this request for now. Feel free to reopen if you have compelling arguments for why we should add this to openMSX. In other words: why is a wrapper script not suitable?

**Comment by friguron** [comment]
Eh, ok... It's a somewhat unneded harsh answer to a honest suggestion.

Not all people (and not all developers, I'm one) are aware of the power of openMSX tcl scripting, which apparently seems to be the magic bullet for everything surrounding openMSX. 
Sorry for being so ignorant, really... 

I'll try to learn a bit more tcl+openmsx interoperability to see if I manage to achieve something on my own.
Thanks.

**Comment by m9710797** [comment]
I apologize if my comment seemed harsh, it was not intended like that.

The feature you're asking for is quite a lot of work, for in my personal opinion, only a small benefit for the user. The main focus of openMSX is to emulate MSX machines. The main focus of programs like 'wget' is downloading content over http(s) and ftp. Instead of duplicating wget-like functionality into openMSX I propose to combine both programs via an external wrapper script. (Unfortunately I currently don't see how the internal Tcl scripting can achieve this. I know Manuel hinted at this in the MRC thread).

Anyway, this is just my personal opinion, other openMSX developers may disagree.

**Comment by Vampier** [comment]
a more logical approach would be to implement the gr8net features into openMSX (network support in general) as for this request - it could be handled with TcL but it would not be something I would use. I understand that having a (local) repository of games on a central server would make sense but we had this discussion quite some time ago and all sorts of 'evil' things could be done with this feature (on the server end like controlling etc.)

**Comment by mthuurne** [comment]
Much of the web has moved from HTTP to HTTPS already and I think it's likely that trend will continue. So HTTP support without HTTPS support is not going to be very useful.

Implementing HTTPS entirely inside openMSX is not something we should do in my opinion, since it is a lot of work and difficult to get right. But there are libraries that implement it, such as libcurl, that might be an option.

If we want to have any kind of online features in openMSX in the future, we'll need HTTPS support anyway. For example updating the software DB between openMSX releases or matchmaking for online multiplayer.

Several MSX network cards have TCP/IP stacks inside their network chip (DenYoNet does, maybe GR8NET that Vampier mentioned does as well). I think the most practical way to emulate those would be high-level emulation where we intercept requests to the network chip instead of emulating the entire embedded CPU plus TCP/IP stack.

If we're adding HTTP(S) support at some point, we might as well support loading ROMs etc with it.

**Comment by friguron** [comment]
Someone said "libcurl" and it's indeed a very powerful library to deal with URL wget behaviour.
Besides, (modern) MSX environments and ecosystems are one of the very few everyday systems which would probably benefit from simple http addressing mechanisms.

Of course, our proper modern internet is migrating towards https (makes complete sense), but many of the new network capabilities of the new HW/SW developments (GR8NET and some other cards, MSX connectivity, real  MSX web browsing, etc...) depend strongly of some kind of simple non SSL enabled HTTP support. Which again, I can't see how that would be a problem in terms of safety for MSX. Having a nice "server for resources" for a GR8NET card is amazing, and this same server could be used for openmsx to load said resources, inside a LAN, etc...

Of course 2, devs seem to have discussed the topic in the past (it was more than logical), so it was just my 2 cents.

Of course 3: Yes, openmsx is coded in c++ which is (for modern standards) a bit more delicate to code for than, let's say, dirty "python" or dirty "php" scripting, where you can (for example) code silly "apache servers from a disk folder" with clever one liners from command line... Or you can fill a memory variable with just (invented syntax) something like 

$rom = Load_rom_from(url:"http://www.msx.com/romfile.rom"); 

and there you have your rom file ready to be launched. I suppose I've became used to "modern and easy" coding style and it's very tempting to think in these terms when wanting to add features to openmsx.

Again, I haven't touched a C++ line since 2000, so I know I'm RUSTED, I have no idea about "how difficult" would be to add some c++ libcurl inside openmsx to enable command line http addressing... I don't want to feel like "I'm asking for my Santa's presents in a list". 
I can also imagine how it's not "adding libcurl to the mix, and  then magic happens" but it will also need some modifying the command line parser, which BTW I also tried to understand by reading openmsx code, but I didn't managed to get the real grasp from it...

OTOH, I'm more than sure than modern c++ libcurl or similar library has also more than decent httpS support as well, so adding http support would get https support "for free".

Anyway, interesting talk nonetheless. 

Greetings.
