### ISSUE TITLE
Binding to LALT/RALT/LCTRL/RCTRL broken (regression)

### ISSUE THREAD

**Issue by MBilderbeek** [openMSX/openMSX#1202]
In openMSX 0.15.0 you could bind commands to the RALT/LALT/RCTRL/LCTRL keys, but that is broken in current development build (probably due to SDL2 migration?). 

Reported by ren here: https://www.msx.org/forum/msx-talk/openmsx/openmsx-question-how-bind-keys?page=3

**Comment by MBilderbeek** [comment]
Wouter found out that the `,release` variant still works.

**Comment by m9710797** [comment]
I played around with 'set kbd_trace_key_pressed on'. (After closing the console) when pressing SHIFT or CTRL in BASIC, I see messages like:

Key pressed, unicode: 0x0000, keyCode: 0x40132, keyName: LCTRL+CTRL
Key released, keyCode: 0x400132, keyName: LCTRL,RELEASE
Key pressed, unicode: 0x0000, keyCode: 0x20130, keyName: LSHIFT+SHIFT
Key released, keyCode: 0x400130, keyName: LSHIFT,RELEASE

So it seems that in addition to the key itself also the corresponding modifier is present. Though only on press, not on release.

The following bindings do work:

bind lalt,alt { puts "press" }
bind lalt,release { puts "release" }

This behavior does make sense from an implementation point of view, but it's counter-intuitive for regular users.

I'm not sure yet what's the best way to fix this.

**Comment by mthuurne** [comment]
I think supporting the old syntax would be the best option:

- users are already familiar with it
- backwards compatibility
- it is more intuitive

One option would be to implicitly adjust the binding: when the user binds the LALT keyboard event, we actually register a handler for SDLK_LALT with a KMOD_ALT modifier.

Another option would be to ignore modifiers when handling press events for modifier keys.

Let's say hotkey commands are bound to LALT and LSHIFT. Now the user presses both LALT and LSHIFT simultaneously. In the adjusted binding approach, neither hotkey command would be triggered, since the modifier ALT + SHIFT isn't registered. In the ignored modifiers approach, both hotkey commands would be triggered.

So the question is what a bound modifier key means: is it an additional normal key that is affected by other modifiers or is it a single-purpose key that always performs the same action when pressed, regardless of other modifiers? I think the latter is easier to understand.

**Comment by MBilderbeek** [comment]
Note: Wouter implemented mth's 2nd suggestion: ignore modifier attributes on modifier keys
