### ISSUE TITLE
The joystick stops working when the openMSX window looses its focus

### ISSUE THREAD

**Issue by sdsnatcher** [openMSX/openMSX#1225]
This bug seems to have appeared after the migration to SDL2.

With the SDL1 openMSX version, I could use the joystick with openMSX even when the focus was set to another windows.

But with the SDL2 openMSX version, whenever the focus is moved to another window, the joystick stops working.

This might sound irrelevant, but when debugging it was a life saver. Because openMSX-debugger is an external program, whenever you do step-by-step debugging the joystick was the only way to move things around on the MSX without hassle.

Tested with openMSX 1.15.0-342 on macOS 10.14.6.

**Comment by sdsnatcher** [comment]
Restested with openmsx-0.15.0-657, and this problem persists.

**Comment by mthuurne** [comment]
I would actually expect that joystick input, like other input events, is only received when an application has focus. I think it only accidentally worked differently with SDL1.

**Comment by m9710797** [comment]
I agree with mthuurne. I'd call the SDL1 behavior a bug that was fixed in SDL2.
I understand that for your particular use case this bug was actually useful.
But in any case, this is implemented deep in the SDL library itself. As the user of the library (openMSX) we don't have any control over it. So even if we wanted to change this (personally I don't) we still can't do it. Therefor I'm closing this issue.

**Comment by sdsnatcher** [comment]
That's sad. What I was going to suggest was a grabjoystick setting, similar to what the grabinput does for the mouse.

Not sure if this is viable in SDL2 for the joystick though.

**Comment by mthuurne** [comment]
Mouse grabbing works slightly differently: it means mouse events are received when the mouse cursor leaves the window while the application still has focus. Receiving input when an application doesn't have focus is much harder and might not even be possible in some graphical environments: special extensions are being designed to allow global hotkeys in Wayland, for example, since those weren't possible by default.

Maybe something else can be done to make debugging of games easier?

Years ago we did experiments with loading a GUI as a shared library instead of an external process, but I don't remember what the conclusions were.

**Comment by sdsnatcher** [comment]
> Mouse grabbing works slightly differently: it means mouse events are received when the mouse cursor leaves the window while the application still has focus.

Yes, they indeed work slightly different. This is why I said it's similar (but not identical).     :)

According to the SDL2 guys, the SDL_HINT_JOYSTICK_ALLOW_BACKGROUND_EVENTS setting allows you to select this behaviour.

It seems interesting to map this selection to the openMSX, specially for developers. Probably the SDL2 guys had the same reason to add this to their library.

If possible, please also enable this behaviour automatically when open-MSX debugger connects to openMSX. This will save some time.  
(The debugger issues many commands when it connects to openMSX, so this command could be added there)
