### ISSUE TITLE
Always file indexing if first alternative ROM not installed

### ISSUE THREAD

**Issue by MBilderbeek** [openMSX/openMSX#1260]
In a machine configuration there can be multiple alternative ROM images configured (e.g. see NMS 8245 config). If you don't have the first one installed, but you do have a later one installed, this means the machine will start up, but openMSX will always start indexing your ROM filepools for the first entry which could not be found in the .filecache (and will never be found as it is not installed).

Although I understand this behaviour (REALLY prefer the first entry), I wonder if it is really desired. Wouldn't it be better to try the alternatives first and if none can be found, index the ROM pool?
It can mean it takes a really long time for openMSX to start in such situations.
Or should we just let the user install the proper ROMs?

Comments please :)

Reference: https://www.msx.org/forum/msx-talk/openmsx/please-help-testing-upcoming-openmsx-release?page=21#comment-380502

**Comment by MBilderbeek** [comment]
Hmm, the issue in the reference was caused by a virus scanner changing time stamps of the files (are we requesting access time?). We should check whether the above is actually the situation.

**Comment by m9710797** [comment]
Are we sure about the virus checker timestamp stuff?  Maybe it always scans, but (only) when the virus checker is active this scan operation is slowed down enough so that it actually prints progress information.

I never investigated in detail, but for some of my (manually edited) machine configs I also see this scanning progress stuff, but only when using a debug or sanitizer build.

**Comment by MBilderbeek** [comment]
See e.g. 86cf3ad991f5716577250f393874e158f98b181c

@m9710797 says this should be solved now, as the code is much faster now.
