### ISSUE TITLE
Compilation support for msys2 mingw-w64

### ISSUE THREAD

**Issue by strikersix23** [openMSX/openMSX#1272]
Cannot compile for msys2 mingw-w64 x64 or i686

Could use instructions or added target information also fails to detect xiph libraries  installed and all sdl libraries as well. Library issue also applys to Ubuntu 18.04 and up

**Comment by mthuurne** [comment]
Cross-compilation from Linux using mingw-w64 does work, but I've heard that native compilation can run into problems when trying to build pkg-config. Note that the easiest way to build is the [standalone binary (`staticbindist`)](http://openmsx.org/manual/compile.html#standalone) approach, since that will build all the libraries for you as well.

Are you trying to build openMSX 0.15.0 for Ubuntu? That version of openMSX depends on scripts like `sdl-config` which are no longer shipped by some distros. The current Git version will use pkg-config instead, which should work.

In general, diagnosing problems with libraries not being found requires looking at the `probe.log` file, for example `derived/x86_64-mingw-w64-opt-3rd/config/probe.log`.

**Comment by MBilderbeek** [comment]
@strikersix23 Can you please update us on the status? Are things better with our latest openMSX 16.0 release? If not, can you check the probe.log file as mentioned by mthuurne?

**Comment by MBilderbeek** [comment]
No response, closing issue. Please reopen and provide more information if this is still a problem.
