### ISSUE TITLE
Internal OSD lacks monitor type option (for non-colour monitors)

### ISSUE THREAD

**Issue by Dalekamistoso** [openMSX/openMSX#1311]
The monitor type functions are missing in OSD (Green/Amber/monochrome color)

That function is linked to "monitor_type" command in console

for example:

monitor_type green

**Comment by m9710797** [comment]
Thanks for your feedback.
There is a lot of other functionality not accessible via the OSD menu, and that's intentional. We try to strike a balance between offer the most useful functionality and not making the menu too cluttered.
Do you think the 'monitor_type' functionality is useful enough for the "average" openMSX user? Where in the menu would it fit best? (which sub menu?)

**Comment by Dalekamistoso** [comment]
Thanks for your quick response :)

Personally I use the function via custom key binding from time to time, but this is not a is not very user friendly for common user.

But the main reasons are:

- Some MSX enthusiasts like this feature for nostalgic reasons.
- Is useful for desingning color schemes in games compatible with all monitors
- Is more useful than "Display Derfom: 3D" by example

And above all because I am tired of arguing with them because they think that Bluemsx is the only major msx emulator that has that feature.

I propose to add that feature inside "Video Settings" menu option

An appropiate name would be: "Monitor Type:" and cycle between available options.

Thanks in advance and merry christmas
