### ISSUE TITLE
Installed SDL2_ttf not detected on Fedora

### ISSUE THREAD

**Issue by lintweaker** [openMSX/openMSX#1344]
I am trying to build openmsx 0.16 on Fedora 33 x86_64. I installed all required libs and devel packages but configure does not detect SDL2_ttf.
Output of configure:
```
Found libraries:
  ALSA:             version 1.2.4
  GLEW:             version unknown
  libogg:           version unknown
  libpng:           version 1.6.37
  libtheora:        version unknown
  libvorbis:        version unknown
  OpenGL:           version 4.6
  SDL2:             version 2.0.14
  SDL2_ttf:         no
  Tcl:              version 8.6.10
  zlib:             version 1.2.11

Components overview:
  Emulation core:   no
  GL renderer:      yes
  Laserdisc:        yes
  ALSA MIDI:        yes

```
Install SDL2 packages:

```
rpm -qa "*SDL2*"
SDL2-2.0.14-1.fc33.x86_64
SDL2-2.0.14-1.fc33.i686
SDL2-devel-2.0.14-1.fc33.x86_64
SDL2_ttf-2.0.15-6.fc33.x86_64
SDL2_ttf-devel-2.0.15-6.fc33.x86_64
```
What is needed for me to be able to build openmsx?

**Comment by Dalekamistoso** [comment]
My script program already does everything automatically it but I dropped Fedora support in the last rewrites due to lack of interest from public but:

In ubuntu/debian based distros you have to install first: 

"libfreetype6-dev" (in some systems you have to install "libfreetype6" too)

So I suppose that FEDORA based distros should use:

"freetype-devel" package  (& additional freetype related if not enough)

If you want to check additional requirements you should check my repo and use the old version "launcher-fedora-english.sh", the program does the compile process easily with logs and everything you need should work (but not the spanish translation and lacks all the new features I added after that version):

https://github.com/Dalekamistoso/openMSX-linux-launcher-compiler

**Comment by lintweaker** [comment]
@Dalekamistoso thanks for the tip! After installing ```freetype-devel``` configure detects SDL2_ttf as available and compile succeeds. I bit odd but...

**Comment by mthuurne** [comment]
It's a limitation of our build system: indirect dependencies are needed when linking statically and our build system cannot currently track dependencies differently for dynamic and static linking. As a result, the indirect dependency (FreeType) becomes required for dynamic linking as well, even though in theory this shouldn't be necessary.
