### ISSUE TITLE
nop mod player is stuck in operation

### ISSUE THREAD

**Issue by denjhang** [openMSX/openMSX#1345]
I am confused.
I tried both in dos2 and nextor.
enter
nmp *.mod
After that, it was completely frozen and there was no response.

[nmp.zip](https://github.com/openMSX/openMSX/files/6283787/nmp.zip)

**Comment by MBilderbeek** [comment]
Did you try this:
```
MODE 80
nmp *.mod
```
with that, it suddenly starts working. I guess it can't handle SCREEN 1 mode...?

**Comment by denjhang** [comment]
Although it works, the sound is particularly unpleasant.

**Comment by denjhang** [comment]
I tried multiple mod files and it was almost all noise

**Comment by sjaaq** [comment]
Author of NMP here.

I just tested this on OpenMSX. The NMP player in the archive does not freeze. But know that you need at least 512K for most MODs. On a Turbo-R with 256K I only can allocate 16K memory for pattern data. If it does freeze, it probably has something to do with your openmsx settings.

The MOD included (GH.MOD) is 8CH. This build 1970 does not support 8CH mods, only 4CH. That's why it does not sound correct.

I created a newer build some time ago that supports 8CH mods (in fact 4,6,8,12 and 16 channels) BUT it seems that most mods that are not 4CH do not use the same format as 4CH mods do. For example, using 16 bit samples or more than 3 octaves.

The option to play more than 4 channels if therefore used with caution. I personally cannot find any good mods that have more than 4 channels and actually are nice tunes. That does not include S3M, XM or IT, which is a completely different format.

If you want to get the right format mod, you can use milky tracker to convert most files to a correct formatted MOD file but you will quickly find that it will actually break the music.

**Comment by sjaaq** [comment]
> 
> 
> Did you try this:
> 
> ```
> MODE 80
> nmp *.mod
> ```
> 
> with that, it suddenly starts working. I guess it can't handle SCREEN 1 mode...?

You  are right about that. I'll fix that in an upcoming release.

**Comment by MBilderbeek** [comment]
Closing, as these are no openMSX issues.

**Comment by denjhang** [comment]
@sjaaq Thank you, exactly as you said. I tried some authentic MOD format music, which can be played normally.
