### ISSUE TITLE
"disk full" error

### ISSUE THREAD

**Issue by gilbertfrancois** [openMSX/openMSX#1360]
I have the following issue. I like writing small programs in basic and want to write/read them to (virtual) floppy disk. I can mount a virtual floppy with `diska` command and the first minutes read/write with `load` and `save` commands work fine. I can see the files on disk with the `files` command. However, after a while I get the error `disk full`. 

I tried 2 different methods for mounting a floppy:
* Folder mount: `diska /Users/myname/msx/floppy1/`
* Create a floppy image with: 
    - `diskmanipulator create /Users/myname/msx/floppy1.dsk 720`
    - turn the machine on
    - `diska /Users/myname/msx/floppy1.dsk`

Both methods give same result. When using method one and looking in the folder, I see some successful written files, some bytes large. The files that were unsuccessful during writing and returning the `disk full` error, have a size of 0 bytes. Both the folder and disk image have read/write permission on the host file system.

I also noticed that when the `disk full` error appears and I eject the floppy, the command `files` still shows all files of the already ejected disk, including the unsuccessful written files. 

The physical disk on the computer has plenty of space and the msx basic programs I wrote do not exceed 720 kb.

macOS 10.15.7 (Catalina)
openMSX 16.0

**Comment by MBilderbeek** [comment]
Which MSX machine were you emulating?

**Comment by MBilderbeek** [comment]
OK, I can reproduce the problem on the Sony HB-F500P, but not on the HB-F700P.

To reproduce:
1. `mkdir /tmp/test`
2. `openmsx -machine Sony_HB-F500P`
3. `diska /tmp/test`
4. `?DSKF(0)` returns 2!??
5. `FILES` says "File not found"
6. Create a `/tmp/test2` with files in it.
6. `diska /tmp/test2`
7. `FILES` says "File not found"??????? 

WTF??

@m9710797 Can you take a look?

**Comment by gilbertfrancois** [comment]
The Sony HB-F500P. I'll switch to HB-F700P.

**Comment by MBilderbeek** [comment]
@m9710797 It's even worse. If I replace step 2 and 3 in the above reproduction recipe with this, the problem doesn't occur:
2&3: `openmsx -machine Sony_HB-F500P -diska /tmp/test`
4. `?DSKF(0)` returns 713. As expected.

So, it must be related to the disk image selection logic and not with the MSX hardware emulation.

**Comment by m9710797** [comment]
I haven't found the problem yet, but here's already an interesting observation:
* I boot Sony_HB-F500P without disk inserted
* I wait till I see the BASIC prompt, and then insert a blank disk
* I execute ?DSK(0)   This gives the wrong result (2 instead of 713). BUT WITHOUT doing any disk access (the drive LED remains off)

When I repeat this experiment, but now with a disk image inserted from the start (or very early during boot). Then ?DSK(0) gives the correct result, but ALSO without performing any disk access.
 
On a machine like Sony_HB-F700P, the ?DSKF(0) command always gives the correct result, but it also always performs disk access before giving the (correct) answer.

This is just a guess, but it seems as-if the F500P software has cached the content of the FAT sectors, but then doesn't realize it needs to flush this cache on a disk change. Possibly the hardware has a disk-change mechanism that isn't emulated yet ???

**Comment by m9710797** [comment]
After some debugging I found that the Sony_HB-F500P software indeed checks a specific bit before deciding to (not) re-read the disk. That bit had no emulated functionality yet. If I connect that bit to a 'disk-changed' function then the Sony_HB-F500P starts to behave as expected.   So this seems fixed!

**Comment by MBilderbeek** [comment]
Thanks, this fully explains the observations. The difference was not the command, but the presence of the disk at boot time, apparently. Weird that it gives a 2 blocks free result, but OK.... anyway, thanks for debugging and fixing.

**Comment by gilbertfrancois** [comment]
Thank you all for fixing it. Great work.
