### ISSUE TITLE
Move build folder

### ISSUE THREAD

**Issue by liberodark** [openMSX/openMSX#1381]
Hi,

Are you ok to move `build` folder to `src_build` folder ?
That can help for compilation on  batocera with buildroot = br is remove automatically `build` folder.
I think is better to just move an not to make a big patch for fixe that is not good solution for later.

Best Regards

**Comment by MBilderbeek** [comment]
Can you explain why this is necessary on that OS?
The build folder is not where openMSX is built... all stuff that is written by the openMSX build system ends up in the (automatically created) `derived` folder.

**Comment by liberodark** [comment]
Hi,

yes no problem moving the `build` folder avoids this automatic deletion.
I know that openmsx does not build this in the `build` folder but `derivated` 
But builroot simply deletes the folder for him.
It is a normal mechanism at buildroot for him if there is a `build` folder it is not normal because it is supposed to be present after the compilation. 
So impossible to compile openmsx without patching it either with meson or autotools. 
This allows you to add the compatibility of your software to several OS based under Buildroot: batocera, recalbox, lakka... 

Best Regards

**Comment by MBilderbeek** [comment]
Looks to me this is an issue of 'buildroot', making such assumptions... @mthuurne  what do you think about this? 
(Note that I had never heard of buildroot before...)

**Comment by liberodark** [comment]
Hi,

It is very well known but I understand that you do not know.
It is embedded linux very suitable for board arm and pc.
This allows for a light and efficient linux system.
Widely used in the retrogaming world.
Note that my PR corrects this problem and has no impact on your project simply it brings compatibility to openmsx. 

Best Regards

**Comment by mthuurne** [comment]
I'm very reluctant to rename parts of our source tree, since it's likely to cause a lot of fallout, in terms of incorrect documentation, CI scripts failing etc. More so because I don't think we're doing anything wrong: the `build` directory contains our build system, not the output of the build. Assuming that `build` is always an output directory is incorrect, in my opinion.

Buildroot is used to build the OpenDingux rootfs, so I'm familiar with it. I haven't run into any problems with it removing source directories though. Could you point to the documentation or implementation where it removes the `build` directory? Maybe there is a configuration override to disable this behavior on a per-package basis? (in the `openmsx.mk` in buildroot)

**Comment by liberodark** [comment]
Have change documentation and CI too in my PR.
You are the first project I see with a build folder in its sources.
It is not common precisely. 
We have found no option to change this behavior.
But I'll let you watch our MK: https://github.com/batocera-linux/batocera.linux/pull/4879

**Comment by mthuurne** [comment]
Ah, you're using Meson to build. Our Meson build is still in an experimental state; you'll likely get better results from using the old Make-based custom build system instead. Especially if you're doing cross-compilation, since I haven't tested that with Meson at all yet.

Could it be that buildroot's Meson support always creates a build directory named `build`? Maybe switching to the Make system will also fix the `build` dir problem.

[Documentation on how to use the build system.](https://openmsx.org/manual/compile.html#local)

**Comment by liberodark** [comment]
Meson is only the last attempt.
Because I also used autotools it also removes the build folder.
The deletion of the build folder is done well before everything else just after the extraction. 
I specify that my PR is not to correct the meson compilation but to add the compatibility of compiling under buildroot.
So meson or other making this change will simplify the maintainability of your emulator.

**Comment by liberodark** [comment]
We have make a workaround for fix that.
