### ISSUE TITLE
gles support?

### ISSUE THREAD

**Issue by christianhaitian** [openMSX/openMSX#1386]
Greetings,

Any plans to further develop gles support for this emulator?  I noticed there's a gles2 branch and while it builds, it doesn't seem to be functional yet.

Thanks,

**Comment by christianhaitian** [comment]
Nevermind, it does run.  Just can't use the tcl files from the latest master branch.

**Comment by m9710797** [comment]
It's been a while, so I don't remember all details...
I believe most (all?) of the work on the 'gles2' branch has been merged to the 'master' branch, But you still need to select the openGL version by editing the code: see src/video/GLUtil.hh lines 23-26. So on line 26 set OPENGL_VERSION to one of OPENGL_ES_2_0, OPENGL_2_1 or OPENGL_3_3.
However this only changes how we interact with the openGL in the c++ code itself (which gl functions we call). This does NOT change anything in the build system. So it continues to link against the openGL rather than the openGLES libraries (and on my system that happens to work).
There is currently no real driver to continue working on this.

**Comment by mthuurne** [comment]
There will be motivation to continue with GL ES though after the Android patches have been integrated.

**Comment by christianhaitian** [comment]
Interesting. So far the gles2 branch seems to work well on a Odroid Go Advance using ArkOS.

**Comment by christianhaitian** [comment]
It’s more performant than using SDL which needed some tuning before I tried gles2
