### ISSUE TITLE
DirAsDSK: File added from host doesn't appear on disk for some MSX machines

### ISSUE THREAD

**Issue by MBilderbeek** [openMSX/openMSX#1410]
I did the following with a 8250, which works as expected:
```
mkdir /tmp/bla
openmsx -diska /tmp/bla
FILES
no files
touch /tmp/bla/crap
FILES
CRAP
```
the same thing does NOT work on e.g. a Sony HB-F1XV. There the CRAP file does not appear.

**Comment by m9710797** [comment]
I suspect it's because of disk caching on the MSX side.
For example when executing `FILES` for the 2nd (3rd, ...) time the disk drive LED doesn't activate.

I'll try to confirm this hypothesis and then maybe force an (emulated) 'disk was ejected' signal when using DirAsDisk.

**Comment by m9710797** [comment]
Fixed.

**Comment by 0cjs** [comment]
If I'm understanding the above patch correctly, when using the DirAsDsk feature the patch _always_ says that the disk change line is asserted, when asked.

However, I just noticed the `set DirAsDSKmode read_only` setting. In the case of a read-only diskette, it would never need to be asserted as changed until it's removed via `diska  eject` or similar means, right? It looks to me as if doing this might be as simple as changing the implementation from `return true;` to `return ! isWriteProtectedImpl();`.

**Comment by m9710797** [comment]
Hi Ocjs, thanks for your comment.

DirAsDsk is a bit tricky. It can be read/written both from the host and from the MSX side. Changes on one side are reflected on the other side.

The `set DirAsDSKmode read_only` stuff only makes the disk read-only on the MSX side. (There's no way the openMSX application can prevent other host applications from modifying the files in the dir-as-dsk-subdirectory). So changes made on the host-side should still be reflected on the MSX side.

This means that, although the MSX itself cannot write to the disk, the (emulated) disk content can still change (because of a write on the host side). And then the DirAsDSK::hasChanged() method must return true to force MSX software to re-read the disk (e.g. to drop disk-caches).

We could make DirAsDSK::hasChanged() only return true when some host file has actually been changed. Though in the current implementation that's difficult to know. We don't actively monitor the host files for changes. Instead we only (lazily) examine the host files when the MSX actually tries to read from the (emulated) disk.

**Comment by 0cjs** [comment]
@m9710797 Ah, I'd been thinking for some reason that for `read_only` you also built the DSK image just once when the disk was loaded and ignored changes to the filesystem, but of course that doesn't make a lot of sense. (If you really need to avoid changes on the filesystem side, it makes more sense to build a `.dsk` file and maybe mark it read-only.)

Perhaps part of what was confusing me is that `read_only` is a DirAsDSK-specific setting, rather than a setting on `disk<x>`. Is there a reason for that?

**Comment by m9710797** [comment]
Hmm, let me check ... (the code is 20 years old, sometimes the idea I have in my mind about how the code is supposed to work does not (or no longer) match the implementation) .... But I was right: `set DirAsDSKmode read_only` means read-only on the MSX side, but still writable on the host side.

You have a good point. In it's current form the `DirAsDSKmode` setting could be generalized to all disk images. At the moment this setting can take only the values `read_only` and `full`. If I remember correctly in the past there were still other values that only made sense for dir-as-disk. We (or at least I) never realized this can now be generalized.

On the other hand, it might still be useful to have this mode dir-as-disk-specific. The main use-case is to easily share host files with the MSX. This mode makes the sharing unidirectional (instead of bidirectional). And the justifications for this is to make sure that the MSX cannot corrupt the host files. Better said: the MSX or the openMSX emulator itself. Dir-as-dsk is non-trivial code, and certainly in the past, there were bugs that could result in corrupt files.

For non-dir-as-dsk types you can already make the (individual) dsk/dmk image files read-only.

Another answer to your question could be: instead of having a read-only-setting per drive, it's more useful to have this property per disk image (so that you don't have to alter the setting when you switch disk image). Though for dir-as-disk images we approximate this with a single setting.
