### ISSUE TITLE
Update openMSX events to send events about the emulator's own metadata

### ISSUE THREAD

**Issue by pvmm** [openMSX/openMSX#1414]
This feature would make things easier for debuggers since they wouldn't have to pull all the needed data from the emulator all the time. And openMSX already returns status changes, so just extend them to return the emulator's own metadata, like if debuggables, breakpoints, conditions or watch points changed.

**Comment by m9710797** [comment]
I like this suggestion, but I'd also want to ask for some clarification.

We can relatively easy add notifications when breakpoints/watchpoints/debug-conditions are added/removed.
I'll try to make time for this the following days.

But I'm not sure what you mean with "status changes on debuggables". If this means "watchpoint-like-functionality for anything that can be viewed as a 'debuggable'", then that's technically not possible (or at least difficult) at the moment. In general the content of a 'debuggable' is only calculated on-demand in openMSX, so technically openMSX doesn't know about changes in a debuggable (not without constantly querying the content and comparing with the previous result). Of course an important subset of all debuggable just reflect an some array (e.g. ROM / RAM) that is present in openMSX, and for those we could add callbacks when something changes in those arrays. But I prefer not to do this because of the extra overhead (extra checks on all writes). OTOH watchpoints on the Z80 address space were possible to implement without any extra overhead (when not in use). This is because it reuses the checking-mechanism we anyway already had to be able to implement memory-mapped-IO.

**Comment by pvmm** [comment]
OK. No debuggable for now, but let's just let it registered for further reference. But maybe send status changes on probes too. I forgot to mention. I guess they are simple too.

**Comment by m9710797** [comment]
Implemented in cabc54edc939.
Please check and let me know if this is usable. I'm leaving this ticket open for now.

Note: if you plan to use this in the openMSX-debugger, you should take care of a possible version-mismatch. That is a new version of the debugger cannot use this feature in an old version of openMSX. So either you need a fallback mechanism in the debugger (like the current code) or refuse to connect to a too old openMSX. I'm assuming the current debugger already does some kind of version check?

**Comment by pvmm** [comment]
Implemented on pull request https://github.com/openMSX/debugger/pull/175

**Comment by MBilderbeek** [comment]
@pvmm can this issue be closed? If yes, please do.
