### ISSUE TITLE
Add option in OSD and console to reset with clean RAM

### ISSUE THREAD

**Issue by sdsnatcher73** [openMSX/openMSX#1416]
Sometimes you load a game from disk or tape and the game has a ROM header in RAM. Resetting the emulated MSX gets you back in the game (like on a real MSX). It would be nice to have an option to reset the machine back to it's initial RAM content. It could also be called power cycle (power off and on), on a real MSX you might have to wait a bit for the RAM to clear, don't think this has to be emulated ;)

**Comment by m9710797** [comment]
I assume you know this is already possible via: `set power off` followed by `set power on`?

But your question is to add something like this as a single item in the OSD menu? IMHO we should try to keep the OSD menu lean, so only put really commonly used functions in there. My preference is to not add an extra line in the menu for this niche-feature (IMHO).

I'm leaving this ticket open. Maybe other people have other opinions.

**Comment by sdsnatcher73** [comment]
I tried to find power on/off did not expect it to be a “setting”. Anyhow, maybe a setting could be added clearmemoryduringreset? Then the OSD would not be bloated and the user would have easy control over the reset procedure.

**Comment by m9710797** [comment]
That's possible. Though ...

... when writing an emulator you sometimes need to make a choice:
* Between keeping the behavior as close as possible to the behavior of the real machine. (Real machines don't have clear-on-reset behavior. Instead on a real machine you do the power-off, power-on stuff.)
* Or you can intentionally deviate from the real behavior. For example to make the emulator easier to use.

In general:
My personal preference is to remain close to the behavior of the real machines. Also because openMSX is (also) intended as a development tool(*) with as goal to later run the developed software also on real MSX machines.

And of course it's possible to make everything configurable via settings. But that increases the testing effort and, maybe more important, such settings are not easily discoverable for the users (like you didn't know about the "power" setting).

Specifically about this clear-memory-on-reset stuff:
I don't have a strong opinion about this. Maybe you can explain your use-case better? Where did you encounter this ROM-header-in-RAM issue? How frequently does this occur? Would beginners often hit this issue?



(*) Maybe as a developer you want to immediately see this RAM-is NOT-cleared-on-reset behavior (maybe you can then erase the header from RAM after it's been used).
If this is controlled via a setting which is enabled by default, then there's a good chance the developer will miss this difference from real behavior.
On the other hand, if the setting is disabled by default then, beginners (for who this feature is mostly intended?), won't benefit because they don't know (or don't understand) this setting.

**Comment by MBilderbeek** [comment]
As the functionality is already present, I propose to close this issue. I don't think it's worth it to expand it right now.
