### ISSUE TITLE
OpenMSXVR, best way to add to configuration file

### ISSUE THREAD

**Issue by S0urceror** [openMSX/openMSX#1419]
OpenMSXVR is an update for OpenMSX I am working on. 

It runs the OpenMSX on the MSXVR and integrates it with the VR hardware. For this I reverse engineered the inner workings of the machine and found out how to communicate with the joysticks, leds, buttons and best of all, the cartridge ports. Both IO and memory read/write.

I know my way around the OpenMSX codebase and will soon release a pull request so that more people can enjoy this. Imagine starting OpenMSX and having it boot a real cartridge and play with your old MSX joysticks!

I created this issue actually to ask for your advice on how to best integrate it in a machine configuration. I want to elegantly add it to the machine configuration so that you can choose to do fully emulated or have a mixed mode and select which physical devices you want to connect to.

1. I want to retain the ability to change machines like starting as a Sony or Philips. And still be able to select virtual extensions, sound cards, etc.
2. I want to be able to map the primary or secondary slots to the physical VR slots (all 4 of them).
3. I want to be able to specify that IO access or memory access or both is allowed.
4. I want to be able to link the joysticks to the proper PSG inputs.
5. I want to be able to link the leds to the PPI outputs
6. Power, reset, pause and VCC to the slots need to be enabled on/off

Below I added what I am after and would like to hear your feedback:
```
<?xml version="1.0" ?>
<!DOCTYPE msxconfig SYSTEM>
<msxconfig>

  <info>
    <manufacturer>Philips</manufacturer>
    <code>NMS 8250</code>
    <release_year>1986</release_year>
    <description>A popular MSX2 machine in the Netherlands.</description>
    <type>MSX2</type>
  </info>

  <MapperReadBackBits>largest</MapperReadBackBits>

  <CassettePort>
    <msxvr>true</msxvr>
  </CassettePort>

  <devices>

    <primary slot="0">
      <ROM id="MSX BIOS with BASIC ROM">
        <mem base="0x0000" size="0x8000"/>
        <rom>
          <sha1>6103b39f1e38d1aa2d84b1c3219c44f1abb5436e</sha1>
          <filename>nms8250_basic-bios2.rom</filename>
        </rom>
      </ROM>
    </primary>

    <primary external="true" slot="1">
        <MSXVRSlot number="1" /> <!-- memory and io enabled -->
    </primary>

    <primary external="true" slot="2">
        <secondary slot="0">
            <MSXVRSlot number="2" IO="true" Memory="false" /> <!-- only IO for example for an SCC cartridge -->
        </secondary>
        <secondary slot="1">
            <MSXVRSlot number="3"/> <!-- memory and io enabled -->
        </secondary>
    </primary>

    <primary slot="3">

      <secondary slot="0">
        <ROM id="MSX Sub ROM">
          <mem base="0x0000" size="0x10000"/> <!-- it is mirrored all over the slot -->
          <rom>
            <sha1>5c1f9c7fb655e43d38e5dd1fcc6b942b2ff68b02</sha1> <!-- same as 8245/00, verified by mth on his 8250/00 -->
            <filename>nms8250_msx2sub.rom</filename>
          </rom>
        </ROM>
      </secondary>

      <secondary slot="2">
        <MemoryMapper id="Main RAM">
          <mem base="0x0000" size="0x10000"/>
          <size>128</size>
          <initialContent encoding="gz-base64">eNpj+M8wouEI9z4DAJBx/wE=</initialContent> <!-- (chr(0) + chr(255)) * 128 + (chr(255)+ chr(0)) * 128) -->
        </MemoryMapper>
      </secondary>

      <secondary slot="3">
        <WD2793 id="Memory Mapped FDC">
          <connectionstyle>Philips</connectionstyle>
          <mem base="0x0000" size="0x10000"/>
          <!-- Verified on a real 8250 and 8280: FDC registers are visible
               in all 4 pages, rom only in page 1. This is handled internally
               in the WD2793 device -->
          <rom>
            <sha1>dab3e6f36843392665b71b04178aadd8762c6589</sha1> <!-- marked as "NMS 8250" and "v 1.08" -->
            <sha1>c3efedda7ab947a06d9345f7b8261076fa7ceeef</sha1>
            <sha1>8625c6b633d9cca2875e4dc33404fb98653379d7</sha1> <!-- verified by mth's 8250/00, same as previous with different FDC register values -->
            <filename>nms8250_disk.rom</filename>
          </rom>
          <drives>1</drives>
        </WD2793>
      </secondary>

    </primary>

    <PPI id="ppi">
      <io base="0xA8" num="4"/>
      <sound>
        <volume>16000</volume>
      </sound>
      <keyboard_type>int</keyboard_type>
      <has_keypad>true</has_keypad>
      <key_ghosting_sgc_protected>true</key_ghosting_sgc_protected>
      <code_kana_locks>false</code_kana_locks>
      <graph_locks>false</graph_locks>
      <msxvr_leds>true</msxvr_leds> <!-- caps led -->
      <msxvr_cassette_motor>true</msxvr_cassette_motor>
    </PPI>

    <VDP id="VDP">
      <io base="0x98" num="8" type="O"/> <!-- S-3527 mirrors -->
      <io base="0x98" num="8" type="I"/> <!-- S-3527 mirrors -->
      <version>V9938</version>
      <vram>128</vram>
    </VDP>

    <PSG id="PSG">
      <type>YM2149</type> <!-- in S-3527 MSX-ENGINE -->
      <io base="0xA0" num="2" type="O"/>
      <io base="0xA2" num="1" type="I"/>
      <sound>
        <volume>21000</volume>
      </sound>
      <ignorePortDirections>true</ignorePortDirections> <!-- not sure, but guess based on use of Engine IC -->
      <msxvr_joysticks>true</msxvr_joysticks>
      <msxvr_leds>true</msxvr_leds> <!-- kana led -->
    </PSG>

    <RTC id="Real time clock">
      <io base="0xB4" num="2" type="O"/>
      <io base="0xB5" num="1" type="I"/>
      <sramname>nms8250.cmos</sramname>
    </RTC>

    <PrinterPort id="Printer Port">
      <io base="0x90" num="2"/>
    </PrinterPort>

  </devices>

</msxconfig>
```

**Comment by m9710797** [comment]
Hi S0urceror,

Nice work. Do you plan to document the result of your reverse-engineering work? I'm interested in learning more about it.

Instead of directly answering your questions, I'd like to suggest some alternatives. I must admit that I don't know the MSXVR hardware well. So these suggestion may or may not be a good idea.

* About the LEDs. Any reason why you would NOT want to link these to the MSXVR hardware? In other words: my should this be configurable?
* About the joystick ports. Won't it be simpler (and more flexible) to model the MSXVR joystick ports as one of the possible "pluggables" in openMSX. That is: you plug in the "MSXVR-joystick-port" in openMSX. That allows you to still unplug and plug-in something else (in openMSX), without having to switch to a different machine configuration. And by tweaking the startup scripts you could make this the default plugged-in openMSX joystick device.
* And a similar suggestion for the cartridge slots. Model them as a (openMSX) MSX-device. Not a property of the slot in the machine config file.

**Comment by S0urceror** [comment]
Hi Wouter,

Yes, I intend to document the result and the process of reverse engineering. There are still a small couple of things left that the community hopefully picks up.

LEDs could indeed auto connect but then I need to first identify on which hardware OpenMSX is running. A normal RaspberryPI or a RPI in a MSXVR case. Luckily there are ways to detect this. Initially I thought it would be simpler to configure and only VR users would do that. 

I will investigate what you mean with pluggables. I just don’t want to introduce extra latency via scripting. Any lag on input devices is a nuisance. Is a pluggable an extension selected in the GUI?

Ok on the cartridge slots  I’ll derive a class from MSXDevice with it’s own tag in the configuration file. Want to be able to mix and assign virtual and physical devices to the cartridge slots. 

I’ll create a first release soon and iteratively we can work out what works best. Thanks for the direction and tips.

**Comment by m9710797** [comment]
I'm looking forward to reading that documentation.

About normal RaspberryPI vs MSXVR: won't you anyway need a special build for MSXVR? I assume accessing the extra MSXVR features requires some direct hardware (GPIO?) access? Is that safe to do on a normal RPI? Does it require extra privileges? Maybe I'm mistaken, but in my mind MSXVR would anyway require a special openMSX build. And if this assumption is correct, then you don't need any detection code.

I used the term "pluggable" in the openMSX meaning. That is in openMSX we emulate "connectors" like the printer port, the joystick ports, the cassette port, etc. We also emulate stuff that connects to those ports, like a printer, a joystick, a mouse, a cassette player, etc. Those things we call "pluggables". So it's not related to software "plug-ins", sorry for the confusion.

So what I meant was that you implement a MSXVR joystick port openMSX "pluggable". You activate this (in the openMSX console (*1)) with a command like "plug joyporta MSXVR-joystick-kport-A" (thus the "MSXVR-joystick-port-A" is the stuff you will add). This new device only connects the emulated openMSX joystick port to the physical MSXVR joystick port.
(*1) And it may be convenient to have this command automatically executed via the startup scripts.

Now that you mention 'latency', I do have a concern about the timing in general while interacting with real hardware (e.g. real joystick, real mouse or real MSX cartridge). Maybe your documentation will resolve my concerns. But I'll already ask my question:

* I'm simplifying things _a lot_, but openMSX is roughly frame-based. That is: we emulate the CPU (Z80) for some time, then we emulate sound, then we emulate video, etc. And at the end of a frame (50 or 60 times per second) we check the timing. Typically emulation runs (much) faster than real-time, certainly on a modern desktop, and probably also on a RPI. Thus after every frame we wait a little so that (on average) the emulated MSX appears to run at the correct speed.
* Thus if you look in detail: during CPU emulation, the emulated Z80 runs much faster than the Z80 in a real MSX. During sound/video emulation or during the sync-with-real-time, the emulated Z80 does not advance in time at all.
* I wonder how this timing (I mean the non-constant timing rate) interacts with real hardware. Suppose the MSX software is toggling some joystick port output pin at a constant rate. So it writes to the emulated PSG ports, and that toggles a pin on the real MSXVR joystick port. Though because the Z80 is emulated in short fast burst, followed by long pauses, the timing on the real MSXVR port is very different: instead of toggling at a constant rate, there's now a period where the pin toggles much faster, followed by period without any toggles, and so on.
* For a real MSX joystick this non-constant timing is not a problem. It might be a problem for a real MSX mouse.
* The same timing discrepancy is present when communicating with real MSX cartridges. This might be a serious problem.

So when you document you reverse engineering findings, I'm especially interested in the timing aspect.

At this point I'm only guessing, but I can imagine that the official MSXVR software had to take special care of the timing (maybe it synchronizes with real-time much more frequent than once per frame??). OpenMSX was not designed with this extra timing stuff in mind. So I can imagine it will need some adjustments before it will work well.

**Comment by S0urceror** [comment]
Regarding the timing I guess we just have to go for it and find out ;-)

Thanks for explaining pluggable, I get it now and know where to find and extend it in the codebase.

Regarding a special build. Yes that is always possible. The reason I started this post is to have it integrated as 'standard' and smart as possible. Everything optional only when you configure to tap into the VR hardware. Then it is up to you to decide if you want to have it in your mainstream ARMv7l build or have it indeed as a separate fork so that your build does not carry any optional stuff in it.

Anyway, I'll first start coding and then come back to present the results. Thanks for your guiding comments.

**Comment by m9710797** [comment]
One clarification: a separate build does not necessarily mean a fork of the source code. We can have conditional code with constructs like:

    if (PLATFORM_MSXVR) { ...

**Comment by S0urceror** [comment]
I know the original issue is closed but I wanted to update you that I just published my [code](https://github.com/S0urceror/MSXVR) including a write-up on the reverse engineering process. You can find it on my GitHub [here](https://github.com/S0urceror/MSXVR/wiki/reverse_engineer).

Btw. I followed most of your advise. I made a separate MSXVR target which enables the changes I made for the VR in the original codebase. Unfortunately OpenMSX currently only runs fast on Raspbian Buster. This means I can only run the 17.0 release of OpenMSX because C++20 is not supported on Buster. Hope SDL compatibility with Bullseye will improve so that I can make a normal 18.0 build.

**Comment by m9710797** [comment]
Thanks!
