### ISSUE TITLE
Request: 7zip archive support

### ISSUE THREAD

**Issue by ryz** [openMSX/openMSX#1439]
Hello! First of all, thanks for your hard work on this excellent emulator!

It'd be great if openMSX would support 7z archives (as well as loading games from them on-the-fly, just like zip files do) due to the superior compression ratios with LZMA2 compared to zip archives.

**Comment by MBilderbeek** [comment]
Is the compression ratio relevant for MSX software?

Op wo 20 jul. 2022 13:23 schreef Steve Haßenpflug ***@***.***

**Comment by m9710797** [comment]
Hi,

I'm not against this request. But I do wonder about the trade-off between implementation/maintenance effort versus the benefit it will bring.

Compression algorithms are continuously evolving:
* First  (1991) there was deflate (zip/gz), runs very fast, has a reasonable compression ratio.
* Then (1996) we had bz2, better compression ration, but slower.
* Followed by lzma (1998), even better compression ratio, but runs *much* slower (both compression and decompression).
* Recently (2015) we have zstd, this covers a wide range of compression-ratios, the best approaching the ratio of lzma, while at the same time being much faster (even faster than deflate).

So maybe instead of lzma, we should add support for zstd?

I did a few tests: I compressed various MSX ROM files with zip, lzma, zstd. Lzma indeed gives the smallest file size, but the difference compared to zip is often only 5%-10%. Given the already fairly small initial file size, the absolute difference is often only 1kB-10kB. The largest absolute difference in my test was 30kB on a 512kB ROM. (I'm sure you can find more extreme examples, but the general trend is a few kilo-bytes per game).

Personally, because this only gives a small benefit, I'm not giving this request a high priority (read: given my amount of free time, there are other requests that deserve more attention). But if there are volunteers to work on this, then I'm of course very happy to help.

Thanks.

Wouter

**Comment by ryz** [comment]
Hello, thanks for the response! 

You guys are probably right, it might not be worth the effort considering the negligible gains in compression. Thanks for considering it though!

**Comment by MBilderbeek** [comment]
We are not going to implement this, as it's probably not worth it. Still, if someone is willing to work on this, we'll of course help.
