### ISSUE TITLE
Add support for Yamaha SKW-01 cartridge

### ISSUE THREAD

**Issue by MBilderbeek** [openMSX/openMSX#1476]
See https://www.msx.org/forum/msx-talk/hardware/trying-to-dump-yamaha-skw-01 and particularly https://github.com/uniabis/msxrawl/tree/main/dumpskw1

Just for the fun of it.

**Comment by sdsnatcher73** [comment]
dumped ROMs and SRAM:

[SKW-01.ZIP](https://drive.google.com/file/d/1GSqMWNhaxuZz8SOtWErDuMX3O6vcEuCa/view)

**Comment by grauw** [comment]
@MBilderbeek Clang complains:

```
src/YamahaSKW01.cc:65:55: warning: implicit conversion loses integer precision: 'int' to 'std::array<unsigned short, 4>::value_type' (aka 'unsigned short') [-Wimplicit-int-conversion]
                        fontAddress[group] = (fontAddress[group] & 0xFF00) | (value << 0);
                                           ~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
src/YamahaSKW01.cc:68:55: warning: implicit conversion loses integer precision: 'int' to 'std::array<unsigned short, 4>::value_type' (aka 'unsigned short') [-Wimplicit-int-conversion]
                        fontAddress[group] = (fontAddress[group] & 0x00FF) | (value << 8);
                                           ~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
src/YamahaSKW01.cc:147:9: warning: returning address of local temporary object [-Wreturn-stack-address]
        return MSXDevice::getName() + " printer port";
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by MBilderbeek** [comment]
@grauw  Exchanging warnings eh? :) Thanks for reporting.
@m9710797 can you teach me how to fix these best?

**Comment by MBilderbeek** [comment]
Let's already close it, as the feature request was implemented via 715361ec4061e9d577f4029864d4e0d4ee57dd49

**Comment by grauw** [comment]
I promise it’s not on purpose :). I got them when I updated to latest master to fix the other warnings.

For the first two, the literal values and the shift promote the expression to int. Best to enclose the expressions in `narrow_cast<uint16_t>()` (we can use the `_cast` version because we know the value is guaranteed not to overflow so does not need to be checked).

For the last one, either don’t compose a string, or store the composed string on the object so that its lifetime lasts beyond the local method body.

**Comment by MBilderbeek** [comment]
For the last one: why doesn't that create a temporary string object that lasts already long enough?

**Comment by grauw** [comment]
Because heap-allocated resources like `string` are deallocated when they leave scope, and `string_view` is a non-owning type so the string doesn’t get copied as the view is returned.

**Comment by grauw** [comment]
Basically `string_view` is like a `string*` pointer but with additional start and size values.

**Comment by MBilderbeek** [comment]
I had missed it was a std::string_view instead of a std::string... fixed now, but I think it's a bit strange to have a fixed string there, e.g. if we want to reuse this code for the SKW-05, it is weird to have it called SKW-01...

Anyways, all issues should be fixed now, please review again.

**Comment by grauw** [comment]
Apparently it is not good practice (unsafe practice) to return string views, and rather it is only intended to be used for passing parameters in… is what I read on a SO post. Made sense to me.

**Comment by m9710797** [comment]
About std::string vs std::string_view:
I don't feel strongly about this, so if you insist feel free to change the return type to std::string (in all overrides of this virtual function). Nevertheless I'll shortly explain the reasoning for this choice.

First in general, grauw's remark about the SO post. I don't know the context of that SO question. But as a general rule of thumb I can agree. In general it's better to return a std::string instead of a std::string_view. But I only agree as a rule of thumb, not as a rule that must be followed at all times. In some cases it's perfectly fine to return string_views. For example a string-trim function, or string-split, ... Or from functions that must return a fixed string, see next paragraphs.

Now more specific about the YamahaSKW01 code. The `getDescription()` method is part of the `Connector` class. This class has (among others) these methods: `getName()`, `getDescription()` and `getClass()`. The result of `getName()` is (must be) unique among all instances. But `getDescription()` and `getClass()` are expected to be fixed for all instances (of the same type). It's easiest to explain via an example (and I'll switch from `Connector` to `Pluggable`, but the same reasoning applies). Take two joystick devices and a mouse device. The names might be "joystick1", "joystick2" and "mouse". All three have the same class name "Joystick Port" (they all plug into a joystick port, in a way this string is used as an enum value). The description is (and currently must be) the same for the two joystick devices, but different from the description for the mouse device.

At one point (and probably still today) catapult was using these description-strings to distinguish between device-types. It would be annoying if the description-string would vary between instances of the same type. (Yes, I know: using description-strings to identify types is not ideal, but it is what we have today).

I don't know enough about the hardware to understand that comment about SKW-01 vs SKW-05. Is it exactly the same hardware that's sold under two different names? Or are it (small?) variations on a basic design? E.g. if you need extra C++ code for the SKW-05 variant (via inheritance or via a boolean variable, or whatever) then it's not so difficult to give a specific description string for the different types. But if it's really the same hardware, then in the current "philosophy" the description must also be the same.

So that's the current "philosophy". In my mind it makes sense for the above joystick/mice example. But I can understand it's less applicable to the YamahaSKW01 case. I mainly wanted to explain where it's coming from.
