### ISSUE TITLE
Remove old cruff that makes compilation slow

### ISSUE THREAD

**Issue by pvmm** [openMSX/openMSX#1481]
Perhaps we could leave the compilation of some extensions optional. For example, who is using ADvram today? It's not even real hardware, right?

**Comment by m9710797** [comment]
I'm not against this idea per se, but I'm skeptical that it will make compilation substantially faster:
* Some of the slower-to-compile units are CPUCore and VDPCmdEngine, those are essential components (can't be made optional).
* We indeed have several rarely used components. But I personally doubt all those components combined account for anything close to 10% of the total compilation time.
* You only need to compile these components once. After that you can rely on incremental compilation to skip them. (This works very reliable in the openMSX build system, no need to every do a clean build).
* And if you make a change (e.g. in a header file) that does require re-compilation of such a component, then my preference is that you DO actually test-compile it before pushing your change.
* In the past we actually had some optional components, but we removed them because (as far as I know) nobody used it. I complicated the build process. And it puts extra burden on testing (actually probably nobody tested those stripped down versions).

Or is there something that I overlooked?

**Comment by grauw** [comment]
How usable are C++ modules right now? I know stdlib is not modulified yet, but...

**Comment by m9710797** [comment]
I'm afraid not very usable yet in practice. At least not for a cross-platform projects.

C++ modules not only requires changes in the compiler frontend (AFAIK that part is done in the 3 major c++ compilers), but also in the build system. To some degree the content of the .cpp files now puts constraints on the order in which those files need to be build. cmake has *experimental* support for that, but only for visual studio yet. The build system again needs help from the compiler to figure out this order. Visual studio and cmake can cooperate to figure this out. IIRC there were patches to do the same with gcc (and clang?), but I don't believe there is an officially released gcc that includes those patches. Also in openMSX we have our own make-based build system. So we should either extend that with module support, or switch to a more standard build system (like cmake).

**Comment by MBilderbeek** [comment]
I think we're not going to do this. So closing the issue.

**Comment by grauw** [comment]
It’s a lame answer I know because there’s a financial component, but, for me upgrading from an 2019 Mac (Intel Core i7-9750H) to an 2023 Mac (Apple M3 Max 16C) made a massive difference in compile speed. It’s more than 5x faster, going from 256 seconds for a full compile to just 46 seconds.

**Comment by MBilderbeek** [comment]
46! I upgraded last year to an AMD Ryzen 9 7950X 16-Core Processor with 2 threads per CPU and it takes 52 seconds!
