### ISSUE TITLE
Remote debugging feature

### ISSUE THREAD

**Issue by Colpocorto** [openMSX/openMSX#1485]
Hello,

I am wondering if the old TCP socket access for debugging could be reimplemented by modern means.

There are tons of great possibilities if this could be done. I suggest some kind of secured endpoint (maybe over SSH transport and authentication with a certificate or strong credentials).

It would make quite easy to build a debugging UI with remote debugging capabilities. For example, you might have an MSX-box such as a Raspberry or a dedicated PC or server (or even an AWS intance!) while you test and debug a program on an iPad or a Chromebook and your wife or husband is watching TV by your side :D

**Comment by m9710797** [comment]
OpenMSX only offers TCP-socket access on Windows systems. On non-Windows systems openMSX uses UNIX-domain-sockets. And the only reason for TCP-sockets is that Windows doesn't support UNIX-domain-sockets. At least not until fairly recently (multiple years already, but I don't remember exactly since when). And we don't (yet) want to force openMSX users to use such a recent Windows version.

Unlike TCP sockets, UNIX-domain-sockets are secure. In the sense that only local users can connect. And more specifically (how we use them) only the same user that started the openMSX process can connect to it. No need to program any authentication/credential stuff: the operating systems all handles this.

Security is important because it's possible to send arbitrary Tcl commands over the connection. Including stuff like "delete all files".

There are tools available to make a (local) UNIX-domain socket accessible as a TCP-socket (thus over the network). Different tools implement this in different ways, but typically this indeed uses SSH. Important: those are external tools, NOT part of openMSX. This means the user has full control, and also full responsibility, over what tool to use and what security guarantees this offers.

Implementing security stuff (authentication, credentials, SSH, ...) is always tricky. Even if you use a library for it. I strongly prefer to not add such stuff to openMSX. Instead, in the future, we could simplify the Windows implementation to use UNIX-domain-sockets.


I'm closing this ticket. But feel free to re-open if you disagree or if you want to add something to the discussion.

**Comment by Colpocorto** [comment]
Sure I respectfully disagree. I can connect by SSH to an AWS instance running a big company's backend, but TCP sockets aren't secure enough for an MSX emulator? 

No need to re-open this ticket, though. I clearly see (from your comments) that this would be a fruitless discussion that is not going anywhere. 

Thank you anyway.

**Comment by m9710797** [comment]
What you want to achieve is already possible today by combining openMSX with a tool like 'socat' (and several others).
OpenMSX should focus on MSX emulation.
Other tools focus on their strength.
Letting the user pick and combine tools is more flexible than building one specific solution into openMSX.

I'm sorry if this is not the answer you were hoping for.
