### ISSUE TITLE
hb-f1xd_disk.rom sha1 mismatch

### ISSUE THREAD

**Issue by yupferris** [openMSX/openMSX#1511]
Hi! A few years ago I dumped system ROMs from my HB-F1XD, and now looking at [the current config for this machine](https://github.com/openMSX/openMSX/blob/master/share/machines/Sony_HB-F1XD.xml#L97), I notice my `hb-f1xd_disk.rom` sha1 (`de1d9be70dc894eadaf99cd730adf77658a7e06f`) doesn't match that in the machine config (`12f2cc79b3d09723840bae774be48c0d721ec1c6`). The hashes for the other two ROMs (`hb-f1xd_basic-bios2.rom` and `hb-f1xd_msx2sub.rom`), however, _do_ match.

I don't know how common this kind of mismatch is; I would guess for a disk ROM it's not so surprising? Even still, it presents a somewhat annoying problem, where I have to change the machine config each time I install openmsx in order to use my own ROMs.

Since I don't know how common this is, or where the current hash came from, I don't really want to suggest updating it, but perhaps there could be a command-line (or .tcl) option to override the expected ROM hashes/files (and perhaps other properties as well)? At least that way I could encode the differences explicitly in my project scripts, and wouldn't have to deal with it manually anymore.

Also, cheers for the fab emulator :)

**Comment by MBilderbeek** [comment]
Hi,

Thanks. The thing is with disk ROMs, that most of the time, the FDC registers are visible in the ROM area (also hiding the actual ROM bytes). Dumping the ROM from within the MSX also means that the FDC registers are then thus also included in the dumped ROM image. The values are mostly varying so all dumps are different. 

Please check whether clearing the last 8 to 16 bytes of the ROM file makes the file the same as the existing dump's hash (which is clean, I just checked that). If it still doesn't match, I'd be interesting to receive the file to examine it.

There is a way to override the hashe. If openMSX finds a file as named in the XML file (including path), it will load that file, instead of the file that it found before with a hash. This is usually not needed. Let's first try to avoid this :)

**Comment by yupferris** [comment]
Aha, interesting, thanks for the info. In a hex editor I can see that my dumped ROM has the last 8 bytes set to various values, and the remaining last 16 bytes are zero. Clearing the last bytes, I indeed get `12f2cc79b3d09723840bae774be48c0d721ec1c6`, which appears to match what's in the current config. That's quite satisfying :) .

I suppose I should just leave these bytes cleared in my local dump and call it a day then?

**Comment by m9710797** [comment]
Hi,

The real hardware, and openMSX, don't use those particular bytes in the ROM
in any way.
Instead when you read those particular locations, the hardware instead
returns you the content of some FDC register (not the content of the ROM).
One of those FDC registers is for example the track-register, that (more or
less) contains the current location of the disk drive's read-write-head.
Thus when you're dumping the disk ROM, and writing a (partial) result to
disk the content of that register varies. And the specific values depend
e.g. on where exactly there happened to be free space available on the disk
you're using.
This example was about the track register, but the other FDC registers can
vary as well.

About your question: should you clear the bytes in your local dump?
That's totally up to you. Your dump is equally good as the version with
cleared bytes.
The specific value of those bytes doesn't matter at all when openMSX is
running.
They do matter when openMSX is starting to verify that you're using the
correct ROM. (Unfortunately there is no efficient way to cache sha1
calculations when part of the file has to be ignored (and not always the
same part of the file)).

Wouter

**Comment by yupferris** [comment]
Thanks for the info! I’ll just leave the bytes clear in my dump and call it good. Cheers!
