### ISSUE TITLE
machine config issue

### ISSUE THREAD

**Issue by pokemonfan6498** [openMSX/openMSX#1526]
i always been using Panasonic FS-A1GT but now it doesn't work i have no idea how to fix it since i rely on it

**Comment by Vampier** [comment]
We need more information - what doesn’t work - any errors on screen - what are you doing to start the machine - do other MSX models work?

**Comment by pokemonfan6498** [comment]
Most of them didn't if resetting configuration i only had some c-bios but
when i launched it for first time i didn't got any non working machines or
extensions

**Comment by pokemonfan6498** [comment]
And when i tried to launch the specific machine it had error that it's not
present in settings.xml

**Comment by pokemonfan6498** [comment]
I may have some evidence on this

**Comment by m9710797** [comment]
I'm sorry, but your report is very unclear (to me). With this information it's difficult to help you.

You mention "error that it's not present in settings.xml". Can you give the full error message? Where and when does the error appear (in catapult, in openmsx, in your terminal, ...)?

How do you start openMSX? From a terminal? From within catapult?

I understood that the "Panasonic FS-A1GT" machine used to work for you, but now it doesn't work anymore. Do you remember what changed? In other words: what did you do so that it now doesn't work anymore? Any details that you remember could be important. Because right now I can't really help you, sorry.

**Comment by pokemonfan6498** [comment]
I usually open from catapult

**Comment by pokemonfan6498** [comment]
As for how it happened I deleted emulator by accident without deleting
folder in documents after I reinstalled all components again now it shows
nonworking machines and extensions

**Comment by Vampier** [comment]
This is not related to openMSX but this is simply a user error (This is a bug tracker and not a support forum) - since your configuration is unknown you just have to figure it out yourself. I would advice to uninstall openMSX completely and then reinstall. 

Here is an installation tutorial https://www.youtube.com/watch?v=6MvhuTiLJqc 

We can provide support at https://discord.gg/vaGwq3GNB

Good luck

**Comment by pokemonfan6498** [comment]
But how if im not using normal installer but instead 7z archive

**Comment by mthuurne** [comment]
On donderdag 13 juli 2023 15:43:40 CEST pokemonfan6498 wrote:
> As for how it happened I deleted emulator by accident without deleting
> folder in documents after I reinstalled all components again now it
> shows nonworking machines and extensions

Where did you put your system ROMs: in the user directory or in the 
installation directory? If they were in the installation directory, they 
would be gone after removing the emulator, which is why it's better to 
put them in the user directory.

**Comment by pokemonfan6498** [comment]
I put system roms in machines directory

**Comment by pokemonfan6498** [comment]
And it seems i put them in wrong area because after i put sysroms on
Documents/openMSX/share/systemroms i got no nonworking machines or
extensions
