### ISSUE TITLE
RS232-Tester input file stream improvement

### ISSUE THREAD

**Issue by CleversonSA** [openMSX/openMSX#1540]
Hi,

I'm developing a hamradio device to decode and encode FT8 using my MSX Expert 1.1 and a Raspberry PI B. The goal is to use RS232 integration. Meanwhile I don't own a real RS232-C device to my MSX, I'm using the RS232-Tester provided at openMSX.

I noticed all keys I type inside COMTERM is written to the output file with no issues, but when plug the input file into menu, the input file is read just once, no matter if I add or remove it's content. I had to unplug, exit the emulator and try again.

I was using the v016.0 in my Raspberry PI 400 (debian bulls eyes). I managed to download and compile the latest master version (0.19.0) and I had the same issue.

So I debugged the RS232Tester.cc file and made a change into this file to check the file input change into the thread. Now I was able to send content from a external program to the input file and, almost real time(without need to unplug and plug the RS232Tester every time), be shown at COMTERM command. I'm not an experient C++ developer, how may submit my code to test and review?

Here's my openMSX Settings:

`machine "Gradiente_Expert_Plus"
ext DDX_3.0
ext rs232
diska dsk/dska/.
set rs232-inputfilename /tmp/in.txt
set rs232-outputfilename /tmp/out.txt`

Sequence test (without my proposal modification):
1) Insert a "hello" into /tmp/in.txt
2) Start openMSX
3) Goto to BASIC (not MSX-DOS)
4) run CALL COMINI("8N1NNNNN",9600)
5) run CALL COMTERM
6) Goto to Menu/Hardware/Connectors/RS232Tester... to plug
7) Go back to BASIC screen...the "hello" will appear
8) Insert a new line or word at /tmp/in.txt
9) Go back to openMSX...nothing changed
10) Go to Menu/Hardware/Connectors/RS232Tester, unplug
12)  Go to Menu/Hardware/Connectors/RS232Tester, plug again
13) Go back to BASIC, nothing changed.

With my proposal modification:
1) Insert a "hello" into /tmp/in.txt
2) Start openMSX
3) Goto to BASIC (not MSX-DOS)
4) run CALL COMINI("8N1NNNNN",9600)
5) run CALL COMTERM
6) Goto to Menu/Hardware/Connectors/RS232Tester... to plug
7) Go back to BASIC screen...the "hello" will appear
8) Insert a new line or word at /tmp/in.txt
9) Go back to openMSX... the new content was shown without need to plug or unplug.

Regards

**Comment by m9710797** [comment]
Hi CleversonSA,

Thanks a lot for your interest in openMSX and your willingness to contribute your modifications.

The preferred way to contribute code changes is via a github "Pull request". That is: you submit your changes, we get an email notification and can then review your code. Possibly we'll ask you to make some changes. After zero or more iterations, when we're both happy with the code, we can then integrate it in the main openMSX code.

I'd also like to ask you to describe your use case in more detail. And then specifically the input-file part ("/tmp/in.txt" in your example). How exactly will you produce that file? And why do you need to make changes to this file? What happens (or should happen) if you don't simply append to the end of the file, but instead delete some lines at the start? (Or a combination of deleting at the start/middle and appending at the end.)

I can be totally wrong, that's why I'm asking for clarifications on your use case, but my first impression is that instead of using a normal file for input, you might want to use a "fifo" (also known as a "named pipe"). That is:
* You create a fifo with a command like    "mkfifo /tmp/my-fifo".
* You specify this (special) file as input in openMSX. OpenMSX opens this fifo for reading.
* OpenMSX will read bytes from this fifo, but initially this will block(*1), because there's no data yet in this fifo.
* Then some other program opens the same fifo for writing. After a while this program writes data to the fifo.
* OpenMSX unblocks, reads that data, and processes it. When the end of the data is reached, openMSX does NOT stop, but instead blocks(*1) again until more data becomes available.
* At some later point the writing-program can write more data to the fifo, this then unblocks openMSX. And so on.

(*1) With "block" I mean block the reading-thread in RS232Tester, not block the whole openMSX process.

All this should already work today, without any changes to the openMSX code. Although I admit I haven't recently tested it.

Again, I have not read your code modification, I may have misunderstood your use case, and I have not (recently) tested that fifo's indeed work as rs232-inputfilename. But my first impression was that "checking for a changing file" is re-inventing what fifo's already do. Please enlighten me.

Thanks.

Wouter

**Comment by CleversonSA** [comment]
Hi Wouter,

Thanks for the reply. For clarification, the external program append some data to end of "/tmp/in.txt" file, no matter the current content of it. I tried create a fifo file with the original code before and all events you reported happend, but just once:

* The content of /tmp/in.txt file is read and shown at CALL COMTERM command
* After, I append some data into the fifo file
* The OpenMSX not display any changes.

But, after your great explanation, I noticed may I be missing something with fifo. For test isolation, I've appending the  fifo file with echo command:

`echo "Some content" > /tmp/in.txt`

After the explanation you wrote _"Then some other program opens the same fifo for writing. After a while this program writes data to the fifo."_ , I think I'm testing on the wrong way: what if I keep the input file opened into my program? 

 I will test this scenario with the original code, recompiling it again and post here the results later.

Thanks.

**Comment by CleversonSA** [comment]
Hello, there you are the results, with original master branch code:

1. Scenario 1:

 * Created a fifo file:
`mkfifo /tmp/in.txt`
* At terminal, tested with command:
`cat > /tmp/in.txt`
It will leave the fifo file openned for writting
* Adjusted my openMSX settings script with this content:
`machine "Gradiente_Expert_Plus" 
ext DDX_3.0 ext rs232 diska dsk/dska/. 
set rs232-inputfilename /tmp/in.txt 
set rs232-outputfilename /tmp/out.txt`
* Ran openMSX
* Into BASIC typed the command:
`CALL COMTERM`
- Went to menu/hardware/connectors/RS-232-Tester (to plug)
- Typed something at external terminal hitting ENTER each line
- OpenMSX shows the line content on screen. **Worked**

Until this moment, Is what I need to my project, without extra modification. The only issue I've noticed happens in these sequence bellow (nothing critical):

(with the previous scenario still running)
- Close the External Terminal 
- Went to menu/hardware/connectors/RS-232-Tester (unplug)
- Went to menu/hardware/connectors/RS-232-Tester (plug again)
- Goto to External Terminal
- Type the command:
`cat > /tmp/in.txt`
-  Went to menu/hardware/connectors/RS-232-Tester (to plug)
- Type something at external terminal hitting ENTER
- OpenMSX shows nothing.
- Close OpenMSX
- Start OpenMSX again
- Goto to BASIC and do a CALL COMTERM
- Plug the input file again
- Type into external terminal hitting ENTER
- OpenMSX shows the text

I debugged that at this scenario, once "poller.aborted()" (line 93 at RS232Tester.cc) is called,  a class member attribute called abortFlag is set to true and the poller object is never recreated again.  I think that's why I have to restart openMSX to enable the fifo file text to be read again.

As a matter of fact, the RS232 feature works fine, I've misunderstood just how to propper user it. I've made a modification at my hamradio decoding app to manipulate streams with fstream (cpp), and It worked at the first try: I was able to send data to openMSX via emulated RS232.

Thanks.

**Comment by m9710797** [comment]
I'm very sorry. I completely missed your last post in this thread.
Recently there was some work on RS232 stuff (including RS232Tester). For that reason I was looking through old issues and re-discovered this one.

Specifically the issue you describe in your last post related to the `poller.aborted()` stuff has been changed. Now we reset the poller object when the RS232Tester is unplugged/re-plugged.

Is this ticket now fully resolved? I'm closing this ticket, but absolutely feel free to re-open if some aspect is still missing.
