### ISSUE TITLE
Some settings are not saved

### ISSUE THREAD

**Issue by theNestruo** [openMSX/openMSX#1556]
> - Windows version: 10.0.19045.3754
> - OpenMSX version: 19.1-467-g993c367c0 [Release]

Steps to reproduce:
1. Open OpenMSX
2. Menu > _Connectors_ > _MSX Joystick port B_, set to _[unplug]_
3. Menu > _Settings_ > _Misc_ > _Fade out menu bar_, set to _unchecked_
4. Close OpenMSX
5. Re-open OpenMSX

Current behaviour:

6. _MSX Joystick port B_ has been reset to _MSX joystick 2_
7. _Fade out menu bar_ has been reset to _checked_

Expected behaviour:

6. _MSX Joystick port B_ has kept the empty selection
7. _Fade out menu bar_ has been kept unchecked

Note: this two settings are just an example; I haven't go through all the possible settings to validate them.

**Comment by MBilderbeek** [comment]
To you these two items probably seem of the same category, but internally they are not. :) 

The joystick plug state has never been saved so far. When you start openMSX, it will always start with a default plug state (most empty, but some are automatically plugged by a script called autoplug). This is not new in the GUI, has been like this for always. Currently, the only way to save this is by making a savestate.
We do have some vague ideas on how to improve this, but it's unrelated to the GUI.

The "Fade out menu bar" setting is a specific GUI setting. It's not part of the normal openMSX settings. That said, I'd also expect it to be remembered, so I fully agree this is a bug. @m9710797 was this an oversight? I didn't immediately see how this works with ImGui, though, so I hope you can take a look at it.

@theNestruo if you see any other 'settings' that are not saved, please do let us know. As far as I know, these are the only ones.

**Comment by m9710797** [comment]
It was indeed an oversight.

And yes, it's expected that the plugged connectors aren't remembered. Just like we don't remember which disk and cartridges were inserted.
It might be useful to remember this, but that's a separate issue.

**Comment by theNestruo** [comment]
None of the settings of the hexadecimal viewers are saved.

For example, the number of columns, the "Show Ascii", "Grey out zeroes", "Uppercase Hex" checkboxes, etc. from the "Memory" window, the "PSG regs" window, etc.

**Comment by m9710797** [comment]
Indeed. Thanks a lot for reporting!

Background info:
The hex-editor is a [3rd-party widget](https://github.com/ocornut/imgui_club), we did not implement this ourselves. We do have the source code, and eventually we will change it. But for now the focus is on completing/fixing our own code.

There are more things that (eventually) we might want to change in the hex-editor:
* The address input field should also accept symbol names, and even expressions like `[reg HL]`.
* The hex-values can be edited, but the ASCII values cannot.
* (What you just reported) the settings are not saved.
* ...

And (also already reported elsewhere) clicking on the scrollbar should scroll one page, instead of jumping immediately to that position. But that behavior seems, currently, inherent in Dear ImGui itself (the GUI toolkit we use). Eventually we'll get to this, but for now there are higher priority items.

**Comment by theNestruo** [comment]
No problem. I think it is something to keep in the backlog to be eventually implemented, but I agree this is not high priority by any means.

**Comment by MBilderbeek** [comment]
Settings are now saved as of c965628a5eddfe4af6792d1ad7e52dc4292b2a81 - so now this is really solved.
