### ISSUE TITLE
"Select MSX machine..." dialog usability

### ISSUE THREAD

**Issue by theNestruo** [openMSX/openMSX#1571]
The main use of the "Select MSX machine..." is to select a new MSX machine.
The number of options is so high that most of the time user will filter (e.g.: "8245"), then double click on the list to select the machine.
Currently, the filter is initially hidden, the input is the last option within the filter, and the actual buttons "replace" and "new" are far below, and get hidden if the "Selected machine" section is collapsed.

Please consider this alternative layout:
![image](https://github.com/openMSX/openMSX/assets/12213477/a7efa021-6674-4d26-b61d-495514bb2c86)

**Comment by m9710797** [comment]
Thanks! I like (most of) your suggestions.

I'll put it on my TODO list (though not at the top).

**Comment by m9710797** [comment]
Hi theNestruo,

I've implemented parts of what you suggested, together with changes of my own. Please review and share your feedback. Do you think it needs additional changes?

Here's the list of what I changed:
* Double click in the list, closes the window. But double click on a bad machine (shown in red) does nothing (before it would print an error).
* The 'Available machines' section is no longer collapsible. This was the main point of the window, there's not much to gain by hiding it.
* The 'filter' section is open by default (I still kept it collapsible).
* The text search field has default keyboard focus, but i kept the original order (type, region, text).
* I completely removed the 'Selected machine' section. The same information is visible as a popup in the list.
* When the currently selected machine is filtered out, the 'replace'/'new' buttons at the bottom are disabled (but the selection is remembered for when you broaden the filter again).
* Because the 'replace'/'new' buttons are now always close to the 'available machines' list, there's no need to introduce a separate scroll region to keep those buttons always visible. More in detail: if you don't see which machine is selected, you may also not want/need to press the buttons.

Please close this ticket if you think these changes are sufficient. Or if not, then please explain.

**Comment by theNestruo** [comment]
Yes, they are sufficient. Thanks!
I didn't expect this to be solved so fast! Please keep in mind that I will be opening issues from time to time as I try to use OpenMSX, but I do not expecte every issue to be immediately tackled nor have a high priority. Please feel free to keep them open with a low priority :)
