### ISSUE TITLE
Regarding incorrect specifications of PCM of MSX turboR

### ISSUE THREAD

**Issue by mdpc-msx** [openMSX/openMSX#1574]
There are two.
One is the wrong PCM sampling rate.
In the document it is 15750Hz, but in reality it is 15700Hz.
    　
The second problem is the wrong timing of PCM pronunciation.
Even if data is sent to I/O, it will not be reflected immediately on the actual machine.
When I/O A5h bit0 (ADDA) is 1, it becomes double buffer,
The data immediately before the update is retained until the next update.
No matter how many times data is written within 456 clocks (15700Hz),
Only the data immediately before the update is output.

**Comment by m9710797** [comment]
Hi. Thanks a lot for reporting this issue!

What you're saying makes perfect sense:

* Dividing the turboR base clock (7159090Hz) by 456 gives 15699.76Hz (so indeed 15700Hz).
If we instead want to reach 15750Hz, the divisor needs to be around 454.5. But that's not (close to) an integer, so that's indeed less likely.

* What you're saying about buffering also makes perfect sense.

Thanks again for reporting. I'll try to fix the implementation in openMSX in the next days (or week).

Out of curiosity: could you give some background information on how you discovered this bug in openMSX?

**Comment by mdpc-msx** [comment]
Thank you for your reply.

The reason it was found,
In openMSX, when playing a long sampling, it finishes faster than on the actual machine.
Also, it was found that when playing music with openMSX, there was a lot of noise.

Here is a music player that I made.
Please give it a try if you are interested.

https://mdpc.dousetsu.com/utility/msx/mu/player/top.htm

**Comment by m9710797** [comment]
These issues should be fixed now. Please verify.
Thanks again for reporting!
