### ISSUE TITLE
OpenMSX crashes when settings.xml is invalid

### ISSUE THREAD

**Issue by pvmm** [openMSX/openMSX#1605]
When `SettingsConfig::loadSetting` throws exception because settings.xml is empty, `ImGuiManager::parts` elements are unregistered (deleted), but there is only one element registered in it so far, so it crashes because `find_unguarded` fails assertion first!=last.

This crash shadows the real error that caused it (invalid settings.xml), so I think it's important to fix it.

**Comment by m9710797** [comment]
Thanks for reporting/investigating.

Without having investigated myself, here's my current hypothesis:
* In `ImGuiManager::registerPart()` we only add the new `part` to `toBeAddedParts`.
* Later when `updateParts()` get called, this `part` gets actually added in the `parts` vector.
* It's only allowed to call `unregisterPart()` for parts that were previously registered. Hence the use of `find_unguarded()` (the element we're looking for _must_ be found).
* Though when `registerPart()` is followed by `unregisterPart()` _without_ a call to `updateParts()` in between, then this will go wrong.
* When an exception gets thrown during startup (and this causes openMSX to exit) it's likely that there are no calls to `updateParts()` because this (mostly) only gets called from the rendering code.

This evening when I'm back at home I'll verify this hypothesis and try to fix it. (Likely fix:  `unregisterPart()` should also search in `toBeAddedParts`.)

**Comment by m9710797** [comment]
This is fixed now.
