### ISSUE TITLE
Request: identify OpenMSX instance on debugger windows

### ISSUE THREAD

**Issue by Colpocorto** [openMSX/openMSX#1625]
I use OpenMSX basically to fix bugs and compatibiliy issues in old games. Usually, I need to compare the execution step by step in to different instances of OpenMSX. However, having several debugging layouts on screen at once is confusing when you aren't sure what machine are actually debugging.

I used the 'Session' feature on the classic debugger to solve this, but I can't find a way to do it on the new GUI.

![image](https://github.com/openMSX/openMSX/assets/24856281/d7576c94-e305-47d7-9273-3ab9063aff5f)

**Comment by m9710797** [comment]
I checked a few other applications that use multiple (dockable) windows, but I couldn't find any that have some (configurable?) identification/instance string in (each of) the sub-windows. Mostly only the main window has some indication of the "instance" (e.g. the current document in an editor application). And I don't think openMSX should do this either (or by default) because it will only clutter the windows for the much more common use case that only 1 openMSX instance is used.

But I think there is an easy workaround. See this screenshot:
![identify-instance](https://github.com/openMSX/openMSX/assets/6695233/94c22aee-6d01-43af-82b2-0f4cf2527c53)
You could dock the `Select MSX machine` and/or the `Watch Expression` window into your layout. In the latter you can add an (empty) expression with (only) a description string to identify your openMSX instance.

I do understand this is only a workaround. Let me know if this workaround is sufficient.

**Comment by Colpocorto** [comment]
It's a workaround but I find it a brilliant idea indeed. Thank you for the suggestion.

Maybe a new type of debugging window might be added for descriptive purposes. For example, a small memo textbox where, in addition to the instance identification, the user can add some notes about the progress of the debugging.

See this mockup:

![image](https://github.com/openMSX/openMSX/assets/24856281/638fb5fd-2d0d-4cc5-9c3f-e40d0f58004d)

what do you think about this idea?  I think it would solve the instance ID issue and would add a very interesting feature. Currently I have to keep a separate .TXT file to track all the activity inside the debugger. Having it integrated with the Session would be great.

**Comment by m9710797** [comment]
I've implemented this. Read also the commit message of 04258bb777c5d8d5d17785218409e2c7b022a573.

**Comment by Colpocorto** [comment]
Thank you for the good work.
