### ISSUE TITLE
Saving to dir-as-disk not working properly anymore

### ISSUE THREAD

**Issue by MBilderbeek** [openMSX/openMSX#1628]
As reported on MRC and confirmed by some other users elsewhere: saving to disk using dir-as-disk in Windows isn't working. It crashes openMSX with:
` Fatal error: MultiByteToWideChar failed: 1113`
See the posts by [Dolphin101546015](https://www.msx.org/users/dolphin101546015) starting here: https://www.msx.org/forum/msx-talk/openmsx/please-help-testing-upcoming-openmsx-release?page=100

It worked fine with 19.1.

**Comment by MBilderbeek** [comment]
It still worked fine in this revision:
![image](https://github.com/openMSX/openMSX/assets/12675978/773d2739-53ea-4a65-8baa-7459e812b5ba)

This is the stacktrace:
![image](https://github.com/openMSX/openMSX/assets/12675978/08d9ffa0-6a43-4ef8-a935-9297812481bb)

**Comment by MBilderbeek** [comment]
@FiXato tracked down the versions which work and which don't:
> <openMSX_Discord> <f​ixato> 852 seems to be the culprit
> <openMSX_Discord> <f​ixato> 848 works, 852 doesn't

https://github.com/openMSX/openMSX/commit/888c795f959c0d8470de7aa11a98dc3b518ca793 perhaps?

852 = 7cb488f4e
848 = 5c1e24a86

**Comment by FiXato** [comment]
Windows builds were broken between 848 and 852, so unfortunately it's difficult to test if 888c795 is indeed the culprit, but since it touches DirAsDSK, it seems the most likely culprit.

**Comment by m9710797** [comment]
Revisions 849-851 indeed don't compile on windows, they need the (one line) fix from revision 852.

Revisions 851 and 852 are most likely not the problem (they only touch completely unrelated code). That leaves 849 and 850, of these two 850 (888c795) is indeed by far the most likely candidate.

However there's nothing windows-specific in this commit, and I had the impression that this bug only occurred on windows?? Was that a wrong impression? Did anyone test on Linux/macOS? (I admit I did not.) Though most likely the symptom will be different on non-Windows platforms (e.g. a corrupt (host)filename instead of an error about invalid utf8->utf16 conversion).

Anyway, I'll try to do a careful review of revision 850 this evening. Thanks for the help so far,

**Comment by MBilderbeek** [comment]
![image](https://github.com/openMSX/openMSX/assets/12675978/9fe77826-90b0-45a1-b5a6-ef7e801a0ca3)

Aha, I didn't notice this at first, but the problem does happen on Linux as well, just a bit differently: apparently part of the boot sector is saved as a file, and as these characters cannot be converted on Windows to UTF-16, the crash occurs there. But on Linux, you just get an extra weird file exported, as can be seen on the screenshot.
The content of the actually exported real files is fine, as you can see.

**Comment by MBilderbeek** [comment]
@Vampier pointed me to another scenario that shows problems with dir-as-disk:
1. load a basic program that is large (say 10kB)
2. insert a dir-as-disk
3. save the basic-program as ASCII: `save"test.asc",a`
4. result is that the file saved is truncated at 1024 bytes size...!?

This got broken by exactly the same commit: 888c795f959c0d8470de7aa11a98dc3b518ca793 - I just confirmed that.

**Comment by MBilderbeek** [comment]
This has been resolved with b6add40d7287101c29dd1e7c3dc1d83e84c4cd2f Thanks!
