### ISSUE TITLE
Ejecting media isn't effectuated with the OK button

### ISSUE THREAD

**Issue by MBilderbeek** [openMSX/openMSX#1652]
Apply/OK confusion in media dialogs. The idea is that OK does Apply+Close. Works when inserting, but not when ejecting media. So, Eject+OK doesn't eject. Eject+Apply does.

**Comment by m9710797** [comment]
There seems to be a misunderstanding of how the buttons behave:
* Pressing the eject button immediately ejects the disk/cartridge.
* Selecting a disk/rom image does NOT immediately insert it, because you first may want to select the rom-type and IPS patches (and you don't want to already insert the ROM with the wrong rom-type). To actually insert the disk/rom, you have to press the Apply or the OK button.
* Apply will only insert the selected media (keep the window open)
* OK does the same as Apply, but then also closes the window.

But important: there is no relation between Apply/OK and Eject. This is as intended.

But apparently this is confusing? Is it clear now with the above explanation? How can we change this window so that it's less confusing?

**Comment by MBilderbeek** [comment]
Maybe I got confused by this scenario:
1. insert game: GAME.ROM via the dialog
2. (Game starts.)
3. Eject the game, click Eject
4. But now the GAME.ROM is selected again, so if you
5. press OK to close the window, the GAME.ROM is inserted again and starts, as if eject didn't work.

But that doesn't match at all with what I first did.

**Comment by m9710797** [comment]
Would it be more logical to turn the eject button into one of the options in the radio button list? Then eject (also) only takes effect until you press the Ok/Apply button.

And maybe we could disable (gray-out) the apply button if the current situation is already the situation that would be applied.

**Comment by MBilderbeek** [comment]
Or, leave out the whole radio button list?

You want to do any of these 3 things:
- insert or change rom image 
- insert or change extension
- empty whatever is in

And you want to see what is currently inserted.

What would be the simplest way to achieve this?

**Comment by m9710797** [comment]
I implemented my idea. Please test and give feedback.
And/or give a _concrete_ proposal for an alternative.

**Comment by MBilderbeek** [comment]
I think it works and does not lead to confusion. But the radio button concept is just a bit unusual maybe. But so far I do not have a better proposal. 
It is also a bit weird that there is an "Eject" option, even when nothing is in. Maybe that option can just be left out if nothing is in?

**Comment by MBilderbeek** [comment]
Mostly solved by 4c491e65c86405452f9feffc8fdb361688441cf2 
Let's get some feedback on this, but I think it is still a bit weird that you can select "Eject" when nothing is in. Can we just leave out that option if the media slot is empty?
