### ISSUE TITLE
Prevent duplicate watchpoints...

### ISSUE THREAD

**Issue by MBilderbeek** [openMSX/openMSX#1665]
Some people put setting watchpoints in a script and they get accumulated in openMSX after a while. Can this prevented by not setting identical watchpoints? (All parameters are identical.)

See https://www.msx.org/forum/msx-talk/openmsx/please-help-testing-upcoming-openmsx-release?page=106

Bengalack wrote there:
> OTOH, I use the profiler script Grauw made back in the day. And it uses watchpoints to measure timings. Maybe I use it wrong, but for every run I make, a new watchpoint is added, even if it exists already. I also had this in my startup-script.
> 
> debug set_watchpoint read_io 0x2E
> 
> A few runs and it looks like this:
>  ![image](https://github.com/openMSX/openMSX/assets/12675978/760955a6-d8dc-4f7e-ac02-44c4cbd27cca)
> Many runs, and it is totally filled. Maybe duplicates shouldn't be added?

**Comment by m9710797** [comment]
I also read this on MRC. I've given it some thought ...

For simplicity I'll only talk about breakpoints, but the exact same applies to watchpoints and debug-conditions.

Allowing duplicate (identical) breakpoints is intentional, and I think we should continue to allow that. The reason is the following:
* Suppose you have a Tcl script that does something like:  `set my_bp [debug set_bp <parameters>]`.
* And at a later point the script does `debug remove_bp $my_bp`.
* So set a breakpoint, and later remove it again. The intention is that this has no netto effect. The state of all other breakpoints should remain unchanged. So even if there already was an identical breakpoint (e.g. set by another independent script) it should still be there after the above sequence.
* The proposal to filter identical breakpoints would break this. 

We could maybe only filter duplicates when loading breakpoints. But that's only a partial solution. Breakpoints set by a script are (usually) only useful within that script. Typically the script will react in some way when the breakpoint triggers. But when openMSX is restarted, the script won't be active anymore, and then there's nothing to react to the breakpoint. In other words: even preserving a single instance of such a breakpoint is useless.

My current idea is to explicitly annotate the breakpoints that should be preserved. E.g. the `debug set_bp` command could accept a new flags (like `-preserve`, or `-persistent`, or `-session`, ...). And then change the GUI to set this flag when creating breakpoints.

**Comment by bengalack** [comment]
Extra flags are nice!

For reference, the profile-script I am using is this: https://hg.sr.ht/~grauw/neonlib/browse/tools/profile.tcl?rev=tip

I'm terrible at tcl, but we can see that the script is using `debug set_bp`.

I found out that the script stops working correctly after a while when the amount of breakpoints were too many. (that lead me to this report alltogether)

**Comment by grauw** [comment]
I think the persistence of breakpoints is new? The old debugger also persists breakpoints (I reckon it sets them when it connects?), so this probably got introduced along with the built-in ImGui-based debugger.

I think the default should be to not persist. For scripts clearly it is not the correct behaviour.

But I would also pose the question: when is it useful to persist breakpoints?

Let’s say I’m reverse engineering a game ROM to find cheats, and I’m manually placing breakpoints using the debugger UI, maybe I placed a dozen of them, some enabled some disabled. If I close openMSX it would be annoying to have to place them all again. But why would I close openMSX, if I can just reset the MSX or use the reverse function. Maybe if I fat-finger Cmd-Q / Alt-F4 out of habit, or need to shut down my PC for the day.

But at the same time, if I’m done but forget to clear the breakpoints, when I run the game a week later it could unexpectedly hit those leftover breakpoints. I might even run some different game and hit the breakpoint while it no longer makes sense. Ok, just one button press on the Clear button in the breakpoints UI (if I still have it open).

Another situation, when I’m programming on a project. This workflow involves restarting openMSX every time I make changes to the code, so this seems a situation where persistence of breakpoints manually set through the UI would be more useful. Obviously breakpoints set by (startup) scripts should not be persisted, e.g. my startup scripts typically add a watchpoint on an I/O address so that I can easily trigger a break from the code.

Persisting the breakpoints works as long as the addresses of the code don’t change. There’s plenty of situations where this is indeed the case, e.g. when changing graphics or settings, or changing code past the break point. But it’s also not uncommon that I change the code before the breakpoint and it now hits in a semantically different location. Overall though, probably handy to have it persist in this case, even if it may still break in the general vicinity I can easily move it or clear it.

But here, too, there is the situation if I forget to clear the breakpoints they might unexpectedly trigger later, or in an unrelated project.

(In an ideal world, there would be integration with VSCode, so that I can set breakpoints directly in the source and would not really need that I/O watchpoint anymore. The breakpoints would then also be re-applied after every rebuild and run, adapting to source changes, and be specific to that project. Maybe someday.)

Anyway. I wonder what would be the best user interface for breakpoints set through the debugger UI. Some possibilities I can come up with:

* Do not persist breakpoints at all. Could potentially lead to more frustration than leftover breakpoints do. Currently I encounter the latter case occasionally, I’ve not experienced the former obviously, but I can imagine getting frustrated by having to track down the correct spot for the breakpoint again.
* Add a flag to the breakpoints UI to persist them. Probably a good idea if we do have persistent and non-persistent breakpoints. Though it leads to more clutter. And should it be on or off by default when adding one through the UI?
* When restarting openMSX, have all persisted breakpoints be disabled initially. Wonder if this is a good idea or not. On the one hand it avoids losing that carefully tracked-down breakpoint, but does not hit it unexpectedly. On the other hand .
* Add some concept of a persistence session. Perhaps creating one automatically based on whether you launch the same game and/or the same machine.  I’m not sure it’s easy to do the right thing automatically, it really depends a lot on the context of what you’re debugging, like a specific machine or extension’s firmware, or software across multiple machines with multiple different extensions (as would be the case for VGMPlay).
* When a breakpoint hits while the debugger UI is not visible, have some easy way to continue. Perhaps add Resume and Clear Breakpoints options at the top of the Debugger menu? I think this would be good to have.

**Comment by grauw** [comment]
Another thought: the Clear breakpoints option also clears breakpoints added by scripts, which will break the scripts and is probably not desirable. Perhaps if there is a separate concept of persistence, there should also be a separate Clear and Clear Persistent option.

And maybe also an option to only show persistent breakpoints? (UI getting more cluttered by the minute…)

**Comment by m9710797** [comment]
Thanks grauw for the extensive comment. I mostly agree with you.

I only want to make one clarification/addition:
* Breakpoints that are placed on a label do get updated when the label-value changes (e.g. when you recompile your project and some function changes location). IOW the symbolic name is stored/restored, not (only) the numerical value.
* I think with this extra info, it does make (more) sense to have persistent breakpoints.

But personally I don't have a strong opinion about this. I don't remember exactly, but I think I mainly implemented persistent breakpoints because it was listed as a regression compared to the old debugger.

**Comment by MBilderbeek** [comment]
In the old debugger there was a 'session' concept. So you could save your session to continue later, with all your breakpoints, views, symbols, etc.

Perhaps we need something like that back in the new debugger?

**Comment by m9710797** [comment]
We already have such 'sessions'. We currently call it 'layout'. This includes everything: the layout of the windows, recently used media items, GUI settings (e.g. VDP settings in bitmap/tile/sprite viewer). And also the breakpoints/watchpoints.
From a more technical point of view: it includes everything that's stored in the "imgui.ini" file.

Maybe we should rename 'layout' to 'session'?

You could argue that we should split this is separate files and allow to load/store these independently. On the other hand: it could we very useful that the session does include everything, so including the layout.  (So splitting it up would be a lot of work, and maybe not even that useful).

**Comment by MBilderbeek** [comment]
My point was that if breakpoints etc. are not stored permanently, there must be a clear way to save and load them. But I suppose that @grauw already made pretty clear which use cases there are. I was just reminding us how it was done in the past :)

**Comment by grauw** [comment]
> Breakpoints that are placed on a label do get updated when the label-value changes

Ah, that’s nice!

> I think with this extra info, it does make (more) sense to have persistent breakpoints.

I don’t disagree, though the UI complexity will increase a bit. Unless you don’t want to show breakpoints added by scripts, then you could only show persistent breakpoints and hide the non-persistent breakpoints. But I think that would lose some useful functionality, even though I would by default want to hide the ones added by scripts.

> In the old debugger there was a 'session' concept.

I never used that, and I never liked the pop-up asking me to save my session when I closed the debugger. It already had a natural form of “sessions”, since 1. the breakpoints were remembered when I restarted openMSX, since I would keep the debugger open, and 2. closing the debugger put a natural end to my debugging session.

So that felt pretty natural to me, but not sure how to replicate something as natural in the current set-up.

> We already have such 'sessions'. We currently call it 'layout'. This includes everything: the layout of the windows, recently used media items, GUI settings (e.g. VDP settings in bitmap/tile/sprite viewer). And also the breakpoints/watchpoints.

Mmh slightly unexpected, but that’s alright. Either way, I’m not sure I see myself creating separate layouts for every project I work on. Even if it were stored separately, I wouldn’t do it.

By the way, unrelated feature request: an option in Settings / GUI to reset the layout. On a couple of occasions now I accidentally mis-placed something in the layout without a clear way to put it back in its right place (status lights, reverse bar), and I just wanted to go back to the initial layout, but could not find an option for it. Took me a bit to find where the persistent UI settings (imgui.ini) were stored to manually delete it. For now I added a “Default” layout myself with those settings.

**Comment by grauw** [comment]
> my startup scripts typically add a watchpoint on an I/O address so that I can easily trigger a break from the code.

I just checked my Watchpoints tab and it’s indeed got dozens of those watchpoints.

> you could only show persistent breakpoints and hide the non-persistent breakpoints. But I think that would lose some useful functionality, even though I would by default want to hide the ones added by scripts.

Thinking it over some more, I’m probably not interested in seeing breakpoints set from script in the debugger UI. My profiler script easily adds a dozen of ’em, and if I’m debugging they would just fill up the UI with uninteresting noise. All I could do is accidentally remove them and break the script. So I would be fine with not showing them at all.

> My current idea is to explicitly annotate the breakpoints that should be preserved. E.g. the `debug set_bp` command could accept a new flags (like `-preserve`, or `-persistent`, or `-session`, ...). And then change the GUI to set this flag when creating breakpoints.

Is adding a `-persistent` option to TCL breakpoint commands actually needed? The persistence could possibly be implemented entirely through the UI layer... What’s the use case to persist breakpoints from script?

Summing up some ideas:

1. One possible approach could be:

* TCL breakpoint commands get a `-persistent` flag, as well as a way to change it on existing breakpoints.
* Breakpoints set in the Breakpoints UI are automatically made persistent.
* Breakpoints UI gets an additional “P” (“Persistent” tooltip) column with checkboxes.
* Breakpoints UI gets a “Hide non-persistent breakpoints” checkbox.
* Breakpoints UI gets an additional “Clear persistent” button.
* Debugger menu gets a “Clear persistent breakpoints” option.

2. Another could be to keep the UI breakpoints entirely separate (like in the old debugger):

* TCL breakpoints are all non-persistent, so no `-persistent` flag is added nor do the internals have a concept of it.
* Breakpoints set from the UI are persisted separately, they set and unset internal breakpoints depending on the layout.
* Breakpoints UI only shows breakpoints set through the UI.
* The rest of the Breakpoints UI remains unchanged.

3. Final option is to remove the breakpoints persistence.

Right now I’m leaning towards favouring option 3 first to fix the immediate issue, and then option 2 as a more long-term approach. Option 1 just sounds mostly useful when you’re writing TCL scripts, otherwise it just adds a lot of clutter and becomes harder to understand for the regular user who has no idea why they should choose to make breakpoints persistent or not.

**Comment by m9710797** [comment]
Hi grauw,

I understand your reasoning (I think), but I don't fully agree. I think we _should_ show breakpoints that are defined via Tcl scripts in the GUI (both the disassembly view and the breakpoint menu). Here's my reasoning:
* I agree that for your use case (breakpoints/watchpoints set by profiling script) it's not useful to show them in the GUI. But different people have widely different use cases. I can also imagine cases where it is useful to see them in the GUI.
* Showing them in the GUI does not hurt (IMHO). And 'special' breakpoints (those with a condition or a custom action) are shown in yellow instead of red in the disassembly view. Typically scripts that fully handle the breakpoint themselves do set such a custom action. I mean such typical script-breakpoints are visually distinct from typical manual-breakpoints.
* It would be weird if execution stops (breaks on a breakpoint), without any visual indication of a breakpoint in the disassembly view.  (Maybe there's a bug in the Tcl script, and execution failed to resume).
* The breakpoint GUI could also be an aid to debug Tcl scripts that do stuff with breakpoints. (E.g. for people less experienced with Tcl and/or the command line).

**Comment by bengalack** [comment]
Must agree with Grauw here on persisting breakpoints. To be frank, each time I start a session for debugging and it breaks on the various breakpoints I used in the previous run, it is just a hindrance which I need to manually remove. Don't think I ever have benefitted from this.

**Comment by MBilderbeek** [comment]
@bengalack how do you continue debugging later? Save the whole layout?

**Comment by bengalack** [comment]
When debugging I click in the border of the code view to set a breakpoint. Code stops here and I go back and fix code, closing the emulator as well. When I start up again, the execution breaks because of this breakpoint - which I do not want to keep there. I do not do anything special.

**Comment by MBilderbeek** [comment]
I meant, how do you manage continuing where you left off, usually?

**Comment by bengalack** [comment]
I always have to right click and paste inn a label for the area I want to debug. (search box with dropdown would have been great).

Typically, after I have been fixing something, and restart, the previous breakpoint has moved due to code changes + I often do not want to trigger at the exact same point as in previous run. It all depends on the modifications I did - what insights previous run gave me and so on.

But, true, it would have been great if the disassembly view would start up around the label(s) I used last time, **and not at 0x0000**. Then I can chose to add a breakpoint if I want to :)

**Comment by grauw** [comment]
> it was listed as a regression compared to the old debugger.

I wonder what use case scenarios the person that reported it had? Is there a link to relevant discussion?

**Comment by MBilderbeek** [comment]
Yes, see https://msx.org/forum/msx-talk/openmsx/please-help-testing-upcoming-openmsx-release?page=106 4th post from the top.

**Comment by grauw** [comment]
Sorry, I mean the motivations to introduce the persistence, not the origin of this bug report :).

**Comment by MBilderbeek** [comment]
Ah, sorry, I got confused I guess and responded too quickly.

My best guess is still that people were thinking about the session concept of the old debugger, where they could store and continue a session later, including the breakpoints that were active? I suppose @edwin-v just needed that when he implemented it originally.

**Comment by grauw** [comment]
Because my opinion right now is really leaning towards keeping things simple and just removing the breakpoints persistence function altogether, not trying to fix it in some way.

When the requirements and use cases for it become clear, then we can come up with a way that addresses those without negative side-effects. I’ve locally disabled the persistence already to dogfood it, if I miss it I will call it out.

As for @bengalack’s comment:
> But, true, it would have been great if the disassembly view would start up around the label(s) I used last time, and not at 0x0000. Then I can chose to add a breakpoint if I want to :)

I think that would be nice. The memory view remembers its position, probably thanks to the “Address” field at the bottom, it might be good to add that to the disassembly view as well. Some of the right-click context menu options should probably move there as well then, seems more convenient.

**Comment by m9710797** [comment]
I've disabled persistent break/watchpoints (for now?).

**Comment by bengalack** [comment]
Been using a version with the above changes included for some weeks now (scroll-to and no persistent breakpoints). Things work very well I think. No complaints :)

**Comment by m9710797** [comment]
Thanks for reporting back.
I think I'll close this issue. (But as always, feel free to reopen).
