### ISSUE TITLE
set_watchpoint read_mem not working as expected

### ISSUE THREAD

**Issue by pvmm** [openMSX/openMSX#1723]
While working on #1707:

when executing infinite loop code in ROM (slot 1):
`4015 |c3 15 40| jp #4015`

with watchpoint set as:
`debug set_watchpoint read_mem {0x0 0xffff} {[pc_in_slot 1]} {puts "[format %04x $::wp_last_address]"}`

the watchpoint is triggered several times while it should not trigger at all:
```
4015
4016
4017
4015
4016
4017
4015
4016
4017
(...) <-- repeats infinitely
```
Or am I missing something? `write_mem` is not affected.

**Comment by m9710797** [comment]
This is the expected behavior. Fetching instructions (the same instruction over and over) also requires reading memory.

More in detail: at the hardware level, outside the Z80, thus at the memory-bus, there is no difference between reads for data and reads for instructions. Watchpoints operate at this level.

I assume you're asking this in the context of reverse engineering? To figure out what is data and what is program? Some time ago I suggested to use watchpoints to generate a trace. I mentioned to include the PC in that trace, The reason was to distinguish between data and opcode reads (a read from the range [pc, .. pc+3] is likely an opcode read).

**Comment by pvmm** [comment]
> I assume you're asking this in the context of reverse engineering? To figure out what is data and what is program? Some time ago I suggested to use watchpoints to generate a trace. I mentioned to include the PC in that trace, The reason was to distinguish between data and opcode reads (a read from the range [pc, .. pc+3] is likely an opcode read).

That's insufficient because branch instructions move the PC away from that range anyway. So I still need to read and interpret the current z80 instruction inside my script to decode them myself.

**Comment by m9710797** [comment]
At the moment the opcode bytes are being fetched, the PC has not yet moved.

Did you try this? Can you give a more concrete example where this doesn't work?

**Comment by pvmm** [comment]
Can't we add a parameter to `set_watchpoint` that filters out instruction fetch? The emulator code is the easiest place to make such distinction. Tcl code will look hackish and complicated.

**EDIT** I have to do some tests.

**Comment by m9710797** [comment]
I'm not sure I like that.
* We added the Tcl condition on breakpoints/watchpoints just so that we don't have to add various special flags.
* We've had watchpoints since 2006, and (as far as I know) this is the first time it was needed to distinguish between data and instruction reads.
* The check for `pc <= addr <= pc + 4` is just as easy in Tcl as in c++. We could make this more accurate by taking the actual instruction length into account (but probably not worth the effort, maybe it's OK for a post-processing step).
* To be fully accurate it should also work when an instruction reads itself. E.g. on address 0x1234 have an instruction like `ld a,(#1234)` .. then this will both trigger an instruction and a data read from address 0x1234. BUT this requires extra annotations on all CPU memory reads. And this will make emulation slower for a niche feature.

That last point is important: a very important property of all the current openMSX debugging facilities is: when the feature is not used it has a negligible performance impact on emulation speed. But that won't be the case anymore when we need accurate tracking of data vs instruction reads.

**Comment by pvmm** [comment]
I think I won't need it after all.

**Comment by pvmm** [comment]
Related to #1944
