### ISSUE TITLE
Bad emulation of VRAM access timing with screen disabled on MSX2

### ISSUE THREAD

**Issue by aoineko-fr** [openMSX/openMSX#1754]
According to [VATT results](https://aoineko.org/msxgl/index.php?title=VRAM_access_timing), with tile-based screen modes (T1, T2, G1, G2, G3 and MC ; aka Screen 0~4) on MSX2, disabling the screen display (using BL bit of R#1) have **no impact** on VRAM access timing.

In this context, openMSX allows VRAM access at 12 t-states interval while real machine requires the same limit that with screen enable (15~20 t-states).

This was verified on 8 different machines:
- Mitsubishi ML-G10
- Panasonic FS-A1
- Panasonic FS-A1FX
- Panasonic FS-A1GT
- Philips NMS 8245 (with MSX2+ mod)
- Philips NMS 8250
- Sony HB-F1XD
- Sony HB-F500 (rev2)

See raw result: https://docs.google.com/spreadsheets/d/16uGdJ7JT1MWZ4qQLUDrGk1Wfw3w_EbaMpoS_fxeSJuI/edit?gid=880273221#gid=880273221

Note that disabling the screen on MSX1 effectively removes VRAM access time limitations; the same applies to MSX2/2+ for bitmap modes (Screen 5~12).

**Comment by MBilderbeek** [comment]
@m9710797 can you comment on this? How does it fit with your own measurements of back in the day?

**Comment by m9710797** [comment]
@MBilderbeek See the "Stuff not measured" section in my [V9938 VRAM timings, part II](https://map.grauw.nl/articles/vdp-vram-timing/vdp-timing-2.html) article. (Due to lack of time) screen-disabled was only measured for bitmap modes, not character or text modes.

@aoineko-fr Interesting results. I have some questions for clarifications:
* What is the meaning of the value in red cells? Is it some measure of how often the test saw something going wrong when using that particular access speed? (But then I'd expect to see higher numbers for faster access times). Or is it a percentage, how often the too-fast access did succeed anyway?
* With the same settings (sprites, screen), within measurement error (+/-1), the mode-groups {T1, T2}, {G1, G2, G3, MC} and {G4, G5, G6, G7} show identical measurement results. That confirms my measurements (see above article).
* The groups {T1, T2} and {G1, G2, G3, MC} also show identical results for both screen on/off and sprite on/off. That's surprising to me (but it's something I didn't measure). But since all measurement (for cycles 12, 14, 17, 18, 19, 20) are really identical (within measurement error) that's a good indicator that also the access-slots will be located identically.

**Comment by aoineko-fr** [comment]
The detailed test protocol can be found on VATT result page: https://aoineko.org/msxgl/index.php?title=VRAM_access_timing#Testing_protocol

Number are percentage (OK = 100%) of written data.
A red cell means that a least 1 byte haven't been written; and thus, the speed is considered as unsafe.

All this is empirical, and if we can be almost sure that a not-OK result is unsafe, we can't be sure that an OK result is safe.
Even if the tests represent a very, very large amount of data.

**Comment by m9710797** [comment]
I pushed a possible fix for this, see revision 9396f6cfaeb735b79f38683b82c52af11e065c77.

@aoineko-fr Can you help test this?

**Comment by aoineko-fr** [comment]
Is [openmsx-20.0-8-g9396f6cfa-windows-vc-x64-bin.zip](https://archive.org/download/openMSX_Windows_Bin) including the fix?

That said, it's easy to test on your side:
- Run the [VATT's ROM](https://github.com/aoineko-fr/VATT/tree/master/emul) on openMSX with a MSX2 machine
- Do "Test All" (screen is enable by default)
- Check the result (make a screenshot for example)
- Go back to menu, disable "Screen" in "Options"
- Do "Test All" again and compare with previous result

Mode T1~G3 should have the same "OK" speed in both case.

**Comment by m9710797** [comment]
Yes, that zip should include the fix.

Thanks for the pointers for how to test this. I'll try to do that this evening.

But I'd also like you to test it. It's always good to have the original reporter verify that the problem has indeed been fixed. If only to avoid any misunderstanding between what you reported and how we understood it. (I think in this case the problem description was very clear, but it's good to do it anyway).

Thanks.

**Comment by aoineko-fr** [comment]
I'll check this evening, but as I'm far from a MSX for a week, I'll not be able to make the real test: compare openMSX results with real machine ones.

**Comment by MBilderbeek** [comment]
@aoineko-fr and @m9710797 were any of you able to test with the VATT program and draw some conclusions?

**Comment by aoineko-fr** [comment]
If we're only talking about the limitations on VRAM access with tile-based mode when display is disabled, this seems to have been fixed.

On the other hand, openMSX is still too obtimistic by 1 to 3 t-states. Speeds that work on openMSX won't work on a real machine (at least for the Philips NMS 8250 and Panasonic FS-A1). But that's perhaps another subject.

![image](https://github.com/user-attachments/assets/71c12c99-60ab-4ea2-b0b5-12a2376fce32)
![image](https://github.com/user-attachments/assets/d7293727-35f3-4f20-bbf0-bc0a711cd2e5)

**Comment by m9710797** [comment]
@MBilderbeek yes, i was able to test and came to a similar conclusion as aoineko-fr.

@aoineko-fr you're right: in some cases openMSX is still too optimistic. But, for now, that's semi-intentional. We know that the maximum access time is different depending on what exactly the VDP is doing (vertical border, fetching sprite data, fetching bitmap data, ...).

There is existing MSX software that (probably unintentionally) accesses VRAM faster than 20 cycles, but only (by luck) during a time that it is allowed. If in openMSX we were to just increases the allowed access time by 1 cycle, then we likely break software that does actually work on real hardware.

So we know that openMSX isn't fully correct here, but with the current internal timing model, we've tuned the parameters as tightly as we can without breaking existing software (that does work on real hardware). With a more accurate timing model we might be able to get tighter (or ideally exact) timing values.

In other words: with a not quite accurate timing model we have a choice between:
* Have all software that work on real machine work in openMSX, but (occasionally) fail to warn about too-fast accesses
* Report all too-fast accesses (with an occasionally false positive), but risk breaking (some) software in openMSX that does actually work on real machines.

So for now we choose to error on the safe side.

I'd be very happy if we could improve the timing model. But personally I don't know how to do that. Help with this would be appreciated. The VATT tool is useful to demonstrate that there still is a difference, but it doesn't tell (much) about what exactly to change. (Because we know the timing model must be non-uniform, but VATT only gives a single maximum value).

Maybe one idea could be to specialize VATT further to only measure during specific moments. E.g. only during the display period (not mixed vertical border + display period), though I'm afraid also that won't be accurate enough because even within one display line there's considerable variation.

Another idea is for someone to repeat the logic-analyzer experiment I did in 2013 (see section on "measurements" [here](https://map.grauw.nl/articles/vdp-vram-timing/vdp-timing.html)). Though that experiment was focused on the VDP commands timing. It didn't capture (enough) info on CPU accesses. So the future experiment should also capture the Z80 /WR line and record enough other info to (later) analyze which CPU access failed (was too fast). I can't do this experiment myself: I don't have access to the right equipment, nor do I have sufficient time and motivation. But if someone else is willing to do the bulk of the work, I'm certainly willing to help.

@aoineko-fr So I propose to close this ticket. But absolutely feel free to open a new ticket for the remaining timing differences.



BTW: In [the msxGL VRAM access timing page](https://aoineko.org/msxgl/index.php?title=VRAM_access_timing) you talk about VRAM access while also a VDP command is executing and how openMSX faithfully emulates this. Actually openMSX doesn't do anything special for this case. Therefor my best guess about what's happening is:
* The VDP reads a byte from memory, with the intention to later overwrite the same byte again (e.g. to perform a logical operation, or to only change 4 of the 8 bits).
* The CPU overwrites the same byte.
* The VDP has again overwrites the same byte. This effectively looses the previous CPU write.

I don't know what type of VDP command the VATT test executes. But even a command that executes OR-with-zero, which should have no effect, will cause some unlucky CPU writes to get lost.
So the only "requirement" to correctly emulate this, is to model VDP command read-modify-write operations as separate read and write accesses, and allow to have a CPU access scheduled in between.

**Comment by m9710797** [comment]
We recently made some improvements in this area. OpenMSX should be a bit more accurate now.
@aoineko-fr if you're interested, and if you have time, I'd appreciate if you could run re-run the test with a recent openMSX development snapshot (at least version `RELEASE_21_0-525-gb5651165f` or newer). And then maybe you could also update the [VATT results](https://aoineko.org/msxgl/index.php?title=VRAM_access_timing) page?
