### ISSUE TITLE
Missing information in new tile viewer, compared to old debugger

### ISSUE THREAD

**Issue by MBilderbeek** [openMSX/openMSX#1759]
This is the tile viewer in the old debugger:
![image](https://github.com/user-attachments/assets/78c31b63-b206-47c1-a719-83803d7c9dbd)
In the new tile viewer, the details about a tile are missing:
>  Info for character, the address for PGT e CT. Hexadecimal numbers(and not only decimal) would be nice too.

See https://www.msx.org/forum/msx-talk/openmsx/please-help-testing-upcoming-openmsx-release?page=118

**Comment by Colpocorto** [comment]
I noticed this as well, and it's specially annoying when a pattern is drawn but its colour is #11 (black/black) so it remains invisible.  I've faced some debugging cases that I need to catch when a pattern is actually drawn (even if the routine hasn't applied the actual colour yet).  Seeing the details you can see the actual pattern even if its colour are "hidden".

**Comment by m9710797** [comment]
Hi,

The new tile viewer widget intentionally looks different than the old one. The goal was to retain the useful information and  remove the info that only takes up valuable screen space. I designed the new widget together with David (who implemented the old viewer).

The black-on-black thing is a valid concern. But you can easily work around this by (temporarily) selecting a different palette. (Top-right in the "Settings" pane, select "Custom" or "Fixed").

The "info for character" pane is something we intentionally left out: it takes up a lot of space, and most of the time it's not very useful: the character preview when hovering over a character is often good enough (with the above black-on-black palette workaround in mind). In the case where you do want to see the hex values you can of course still open a hex-viewer (Main menu bar > Debugger > Add hex editor > VRAM). Because typically in that case you want to see many characters (at once).

I'm not sure what you mean with "PGT" and "CT". Do you mean the address in the pattern/color table for the current character? Isn't that (trivially) calculated from the "pattern table" and "color table" base address which is visible in the "Settings" pane? On the other hand, there is enough space available below the character preview, so we could show it there.

I agree that showing pattern numbers (also) as hexadecimal would be a useful addition.

So again, the intention was to make a more compact viewer, while still retaining the most useful information. We had to make a judgment call about what is "the most useful information". So possibly what we think is "most useful" is not the same as what you think. I'm open for suggestions. Is there still anything critical missing?

Wouter

**Comment by MBilderbeek** [comment]
Reporter responded:
> I used the names "PGT" and "CT", because that's what the pattern and color table was called in the old tile viewer, as you can see in the screenshot, and of course this information can be easily calculated, but it was easier when you could just hover your mouse over the tile and get the information ;)
And I can still use the old debugger for some things like this, so it's fine.

**Comment by m9710797** [comment]
Should be fixed in commit 34d85071e271a875c070ec605e04159f5ccdb9a3.
Please test, and re-open this ticket is anything is still missing.
