### ISSUE TITLE
4th tileset of Screen 4 is not visible in tile viewer

### ISSUE THREAD

**Issue by aoineko-fr** [openMSX/openMSX#1763]
When tileset mirroring is disable (default setting for Screen 4), the tile viewer show only 3 of the 4 available tilesets, while we can display on screen all the 4 using V9938 vertical scrolling.
![image](https://github.com/user-attachments/assets/0d2b3f21-c2d9-4e26-9007-f74810aebbd6)

The stranger thing is that when you activate mirror (so 4th bank is not usable), the tile viewer correctly show the 4 tilesets.

The best should be to only show valid tilesets for a given mirroring configuration.
- [0 1 2 3] (no mirroring): show the 4 tilesets
- [0 1 0 1]: show tileset 0 and 1
- [0 0 2 2]: show tileset 0 and 2
- [0 0 0 0]: show only tileset 0 (Screen 1 like)

But at least, display the whole 4 regardless of the mirroring setting.

**Comment by aoineko-fr** [comment]
You can test the issue using this MSXgl sample program: https://github.com/aoineko-fr/MSXgl/raw/main/projects/samples/emul/rom/s_gm3.rom

Press:
- `1` for [0 0 0 0] mirroring
- `2` for [0 1 0 1] mirroring
- `3` for [0 0 2 2] mirroring
- `4` for no mirroring

**Comment by aoineko-fr** [comment]
Ok, hold on. ^^
openMSX don't allow to write in the 4th table... I have to check on real hardware if it is also the case.
If so, current openMSX tile viewer behavior make sense.

Also, tileset are correctly displayed in the viewer when mirroring is activated.

**Comment by mthuurne** [comment]
From my memory, there is a 4th tileset, but the default address in VRAM where the pattern or color data would be located overlaps with the name table. If you set base addresses such that the pattern and color table have a dedicated 8 kB each, having 4 tilesets should work fine.

**Comment by m9710797** [comment]
In the "Settings" section for "Visible rows" you can choose between 24, 26.5 and 32. When you select one of the latter two, the "Pattern Table" section will show 4 tile sets.

@aoineko-fr Is this sufficient? If not, then please explain in more detail. For now I'm closing this issue, but feel free to re-open in case I misunderstood your request.

**Comment by MBilderbeek** [comment]
Apparently the VDP is set for 24 lines. Overriding to 32 shows the rest, indeed. 
![image](https://github.com/user-attachments/assets/4139f3b7-bea9-4ed2-9470-c3d6a000bb87)

**Comment by mthuurne** [comment]
Maybe there could be an option for 8 visible rows as well, since a lot of games use a single tileset with mirroring.

**Comment by m9710797** [comment]
The "visible rows" option actually controls the number of rows in the name-table (not pattern-table). Even with mirroring (so that there's only a single pattern bank) you want to see all rows (the full screen) in the name-table.

My original reasoning was that the 4th pattern bank could only be made visible with the V9938 212-line option. So we only show the 4th bank in the pattern-table when more than 24 rows in the name-table are shown.

I didn't think of using the vertical scroll register (R#23, VDP(24) ??) to make the 4th pattern bank visible. Or actually I did think of it, but I seem to remember that in character mode VDP(24) scrolls within a character, not the whole screen. But I admit I didn't verify this on real hardware (and actually not even on openMSX). Or is this maybe a difference between screen 2 and screen 4?

**Comment by m9710797** [comment]
Replying to my own message:

I checked: in text modes VDP(24) only scrolls within one character, but in character modes it behaves the same as in bitmap modes.

Though if you're using VDP(24) tricks in character mode, you probably still want to see the full name-table (not just the first 24 rows). So IMHO it's not too bad that we coupled showing the 4th pattern-bank with showing 24 or more rows in the name-table (even if in retrospect, with VDP(24) scrolling in mind, that coupling is accidental).

We could make a new separate setting to select how many banks are shown in the pattern-table. But I also prefer to not clutter the UI with too many choices. So I'd prefer to keep the tile viewer as is.

**Comment by aoineko-fr** [comment]
If you want to keep it simple, why not just always display the 4 pattern-banks?

Or, without overloading the UI, you could automatically show only those pattern-banks that can be displayed on screen: 1, 2 or 4, depending on the mirroring settings.

Displaying several times the same tileset is useless imho.
Especially since on my computer I can only see the very top of the Name table at the bottom of the screen, even with x1 zoom.

![image](https://github.com/user-attachments/assets/6b3834f3-5452-4fa1-b3f4-aa534f9998c8)

**Comment by m9710797** [comment]
There are lots of possibilities, all with different trade-offs, and all valid. Depending on personal taste and implementation complexity etc.

My reasoning for (by default) only showing 3 pattern-banks is:
* On MSX1 it's not possible to ever see the 4th bank (is that correct?). So showing it in the debugger is not helpful.
* On MSX2 it's only(?) possible when 212 (instead of 192) display lines are shown, or when using VDP(24). In both cases it's useful to then also show 26.5 or 32 (instead of 24) rows. So IMHO it's not too bad to couple this.
* Many software does not use the 4th bank. In that case always showing the 4th (garbage) bank will only cause confusion.

Like you already said yourself: this window is already very tall. If we would always show the 4th bank the window becomes even taller. BTW for this reason I made it possible to collapse the sections. E.g. once you configured the settings you can collapse/hide that section. Same for the patterns and name table sections.

About mirroring.
* Mirroring can indeed cause some banks to be skipped. We could then not show those banks. I admit didn't think of that.
* Though keep in mind that it's also possible to setup mirroring so that e.g. banks 0 and 2 are used (and not 1 and 3). So a non-contiguous number of banks! But then showing two banks that are not 0 and 1 may again be confusing.
* And who knows, maybe you DO want to see all banks in the debugger, even in case of mirroring. E.g. maybe you're preparing those bank for the next frame, and you want to use the debugger to already inspect those (now invisible) patterns.

EDIT: this last point is nonsense, ignore.
