### ISSUE TITLE
[Feature] Copy/paste from/to openMSX [sf#9]

### ISSUE THREAD

**Issue by openMSX-import** [openMSX/openMSX#33]
**Reported by manuelbi on 2002-06-03 08:21 UTC**
It would be cool to be able to copy/paste from the
native OS to the emulated MSX and also vice versa.

**Comment by openMSX-import** [comment]
**Updated by manuelbi on 2003-06-25 20:46 UTC**
- **summary**: Copy/paste form/to openMSX --> Copy/paste from/to openMSX

**Comment by openMSX-import** [comment]
**Commented by sd-snatcher on 2007-10-14 04:18 UTC**
Logged In: YES 
user_id=130840
Originator: NO

I vote for that. It would allow to easily paste MSX-Basic programs from the net directly on the MSX.

Same on the other side: I could copy texts from the output of any MSX-DOS program to the host OS.

**Comment by openMSX-import** [comment]
**Commented by bifimsx on 2007-10-14 05:00 UTC**
Logged In: YES 
user_id=790845
Originator: NO

Using Catapult pasting from the native OS to openMSX is available for years already, although only to machines with an international keyboard layout.

**Comment by openMSX-import** [comment]
**Commented by auroramsx on 2007-10-14 08:32 UTC**
Logged In: YES 
user_id=951315
Originator: NO

BifiMSX wrote:
&gt; Using Catapult pasting from the native OS to openMSX is available for
&gt; years already, although only to machines with an international keyboard
&gt; layout.

...or via the "type" command in the console.

I guess this FRQ is still open due to the "vice versa". That's a rather
tricky issue though:

\* you'd probably need to differentiate between graphics and text modes.
In graphics mode you'd want to copy a rectangle of pixels, in text
mode, a selection of text. But that's not so simple either:

\- What about screen 1?
That mode is used for text as well as for graphics! 
- What about e.g jANSI?
That's a multi-colored text mode emulated in screen 7!

\* Implementing the selection mechanism poses the very practical
problem, that the mouse might be 'captured' by the MSX. This could
be overcome by having the user press an extra keyboard button to
copy/paste, but that's highly non-standard.

Next to these issues, I wonder what practical purposes copy/paste
from openMSX to the OS might have. I think most use cases can be
covered by already implemented features:

\* Need graphics? -&gt; Use screenshot
* Need text? -&gt; Direct MSX-output to the MSX-printer and log 
the printer file.

Just my 2cts on an early sunday morning ;-)

**Comment by openMSX-import** [comment]
**Commented by manuelbi on 2015-01-15 21:24 UTC**
Paste-to options are nowadays:
- the Type feature in Catapult (which works with any keyboard layout nowadays)
- the type_from_file console command to type the contents of a file (also works for any keyboard layout)
  Both use the type console command internally.

Copy-from options:
- the get_screen command on the console. Put to file e.g. via save_to_file test.txt [get_screen](for text modes only)
- indeed via the printer (e.g. llist for a basic program in RAM)
- via the listing command if it's about a basic program in RAM

**Comment by MBilderbeek** [comment]
Copy/paste to/from clipboard has been implemented in a basic way. You can copy text from the clipboard into openMSX, in the sense that it is typed into the MSX using the 'type' command now. Copying from openMSX is done with the `get_screen` command. Of course this means all limitations of these commands apply. But, as I said, the basics are there.

Due to limitations on SDL2, which only supports text on the clipboard, we cannot implement graphics copying (otherwise making a screenshot and putting it on the clipboard was an obvious implementation). Pasting graphics into the MSX is not something implementable at all, I think.

Anyway, because of the above, I'm closing this ticket. Note that all alternatives are still working. It's just that we added a few keyboard shortcuts (and mouse middle button) to use some of them with the host OS clipboard.

TODO separately: enhance the get_screen command. Something for another ticket.

Yay, another ancient ticket closed :) This one is about 17 years old!
