### ISSUE TITLE
[Bug] DAC not working in YM2413 (both cores) [sf#280]

### ISSUE THREAD

**Issue by openMSX-import** [openMSX/openMSX#581]
**Reported by manuelbi on 2007-10-19 18:01 UTC**
The YM2413 has a built in 4-bit DAC, on which you can play samples. Programs like PSG Sampler use this. See also http://www.msx.org/forumtopic7838.html

On openMSX you only hear a faint noise and then nothing. On a real MSX (I tried turboR) you hear the samples playing (e.g. FMDEMO2.MSX on ClubGuide Magazine 3, see http://www.msxarchive.nl/pub/msx/magazines/clubguide\_magazine/CGM%2303.LZH ). The volume is quite low, but when turning it up a bit, you can clearly hear quite bright samples playing.

**Comment by happppp** [comment]
http://www.msx.org/forumtopic7838.html doesn't work, the right link is https://www.msx.org/forum/development/msx-development/limitations-msx-music?page=1

**Comment by NYYR1KK1** [comment]
I can confirm this bug still exists in 0.15.0

**Comment by MBilderbeek** [comment]
And I can confirm no one worked on this indeed.

Did you test/confirm this:

> 1) First, you have to configure the YM2413 to DAC mode on the register 0Fh.
> 2) Output your samples to the register #10h. The lower 4 bits will be ignored. I'm not sure right now if you have to clean this lower 4 bits. Try both and compare the results.

It's also not clear to me what the two registers described below do exactly.

For informational purposes, I'll also copy the other info:
Register description:<br />
<br />
    Reg #0Fh  TST<br />
<br />
<pre>
       7   6   5   4   3   2   1   0
     +---+---+---+---+---+---+---+---+
     | - | - | - | - |SND| - | - |SMP|
     +---+---+---+---+---+---+---+---+
</pre><br />
<br />
     SND = 1 : Sound output from the FM synthesizer is out<br />
     SMP = 1 : Sample mode ON. The higher 4 bits of the register #10h are<br />
               output to the audio out.<br />
<br />
<br />
    Reg #10h (in PCM mode)<br />
<br />
<pre>
       7   6   5   4   3   2   1   0
     +---+---+---+---+---+---+---+---+
     |    DAC DATA   | - | - | - | - |
     +---+---+---+---+---+---+---+---+
</pre><br />
<br />

**Comment by grauw** [comment]
I have tried this, the description seems to be incomplete since I could not get any sound with the above.

However I’ve taken a look at the code used in Clubguide Magazine 3, it initially sets r#48 to 255, r#15 to 255, r#32 to 0, r#32 to 255 (?), and after that sends PCM data (AND 0F0H required) to r#16. I’ve tried this myself as well, and that [does work](http://www.grauw.nl/etc/msx/joou-fm.rom). I haven’t delved deeper to find out which of all those are the significant bits.

Perhaps FRS in his testing did not reset r#32 and r#48 so they stayed at those initial values set in an earlier test.

I’ve tried this with setting r#15 to 9 rather than 255 and then I do hear sound, but also a loud high pitch.

**Comment by grauw** [comment]
See also this Twitter conversation with some observations from Okazaki (D.S.A.) and Nuke.YKT:
https://twitter.com/Grauw/status/1208845242201509888

It also works for multiple channels actually:
https://github.com/digital-sound-antiques/emu2413/wiki/4-bit-DAC-in-test-mode

D.S.A.:
> I also tried reduced settings. The following works: r#48 to 240, r#15 to 15, r#32 to 31. Then send PCM data (with AND 0F0H mask) to r#16.
> Further, this approach seems also working on the another channel. I also tried r#56 to 240, r#15 to 15, r#40 to 31, then send PCM data (with AND 0F0H mask) to r#24. It also works.

nukeykt:
> Interesting, looks like it using test bits 2 and 0. Bit 2 resets phase accumulator on each iteration and thus phase gen. unit effectively outputs phase increment value which could be controlled using r#16. Bit 0 forces env. gen to output zero attenuation value (e.g max volume)

If Nuke.YKT is correct then the YM2413 test register is identical [to the VRC7](http://www.siliconpr0n.com/archive/doku.php?id=vendor:yamaha:opl2)’s:

```
TEST (0x0F)
	76543210
	|||||||\- if 1, Disables Car/Mod EG units, EG output is forced to 0 (max volume)
	||||||\-- if 1, resets (and holds, while active) the Trem and Vib LFO counts to 0
	|||||\--- if 1, resets (and holds, while active) the PG count for Car/Mod at 0 (this effectively silences the chip)
	||||\---- if 1, the EG unit clock comes from VRC7 'D2' Pin, and the Trem and Vib LFO clock dividers are disabled, so they increment once per clock (x64 and x1024 their usual clock rates, respectively)
	|||\----- Does nothing?
	||\------ Does nothing?
	|\------- Does nothing?
	\-------- Does nothing?
```

**Comment by grauw** [comment]
> Testing register 0FH values:
>
> 1110B: PCM plays softly and is affected by the volume in register 30H.

Bit 0 seems to force the EG attenuation to 0, however, it does not stop the EG from running and muting the sound output once the RR reaches 0 (mute is separate from max attenuation).

```
_MUSIC:_AUDREG(15,1):PLAY#2,"@14A1........"
```

As you can see in the following example the modulator and carrier are muted separately:

```
_MUSIC:_AUDREG(15,1):PLAY#2,"@10A1........"
```

(This also means it is possible to mute only the modulator which may be handy for measuring.)

> 1101B: Everything plays normal.

Bit 1 indeed disables the LFO as this test shows:

```
_MUSIC:_AUDREG(15,2):PLAY#2,"@12A1........"
```

> 1011B: Noise.

Bit 2 in this example mutes the sound:

```
_MUSIC:_AUDREG(15,4):PLAY#2,"@12A1........"
```

The fact that PCM playback can be done by modifying f-num+block when this bit is set means that the PG is not actually held at 0 but at the specified f-num.

Additionally, I’ve confirmed that the multiplier does still affect the PG when this bit is set.

> 0111B: PCM stops after a few seconds when a percussive instrument is selected in register 30H, coinciding with its RR to reach 0.

Bit 3 indeed seems to control whether the EG runs:

```
_MUSIC:_AUDREG(15,8):PLAY#2,"@15A1........"
```

If you execute _AUDREG(15,0) while it’s playing the EG will continue.

In the VRC7 it seems this mode can actually be externally clocked from a different pin, I don’t know if this applies to the YM2413 as well.

**Comment by grauw** [comment]
7½-bit PCM playback on YM2413: https://www.msx.org/forum/development/msx-development/limitations-msx-music?page=2#comment-371119

My current understanding of the test register bits:

**Test bit 0** = 1: EG always return 0 attenuation. Still mutes though when it completes.

> <Nuke.YKT> if 1, Disables Car/Mod EG units, EG output is forced to 0 (max volume)

**Test bit 1** = 1: Either LFO clock is frozen or the amount always returns 0.

> <Nuke.YKT> if 1, resets (and holds, while active) the Trem and Vib LFO counts to 0

I don’t know whether it is reset before or after the increment. For consistency with bit 2 I would expect after.

Quote from YM2151 test register documentation (may behave the same):
> When 1 - LFO gets HALTED (at maximum amplitude in case of AM).
> On the 1 to 0 transition LFO will be RESET to startup of the waveform (phase of the LFO _only_).

**Test bit 2** = 1: Increase phase counter from 0 rather than previous value. So this means, the table is indexed by ((fnum * mlTab[ML]) << block) >> 1.

> <Nuke.YKT> if 1, resets (and holds, while active) the PG count for Car/Mod at 0 (this effectively silences the chip)

It is unclear from this phrasing but it is reset _before_ the increment.

**Test bit 3** = 1: Don’t clock the EG.

> <Nuke.YKT> if 1, the EG unit clock comes from VRC7 'D2' Pin, and the Trem and Vib LFO clock dividers are disabled, so they increment once per clock (x64 and x1024 their usual clock rates, respectively)

Some complementary information about Yamaha test registers described previously:
VRC7: http://www.siliconpr0n.com/archive/doku.php?id=vendor:yamaha:opl2
Y8950: http://map.grauw.nl/resources/sound/yamaha_y8950_test.txt
YM2151: http://map.grauw.nl/resources/sound/yamaha_ym2151_test.txt

**Comment by grauw** [comment]
Also for reference Nuke.YKT’s brand new Nuked OPLL core which seems to have all of this implemented: https://github.com/nukeykt/Nuked-OPLL

He previously made an OPN2 Yamaha sound chip core with extreme accuracy. His cores glitch when accessed too fast just like the real thing.

**Comment by grauw** [comment]
My two ASCII16 test ROMs:

http://www.grauw.nl/etc/msx/joou-fm.rom

Relies on the PG phase, EG phase and EG amplitude test register flags.

http://www.grauw.nl/etc/msx/joou-fm2.rom

Relies only on the PG phase test register flag.

Adding:

```
if ((reg[0x0F] & 0x04) != 0) {
    ch.mod.cphase = 0;
    ch.car.cphase = 0;
}
```

…at the first line in the do of YM2413::calcChannel allows me to test the 2nd ROM. Although it is of course not a complete implementation since it doesn’t apply to the drums. Oh yeah, and I also had to add a few lines of code to the register write function to store the test register in the array.

Note that PSG Sampler and the ClubGuide Magazine 3 demos rely on test register bits 0 and 3 as well, so this change alone doesn’t make them work.

**Comment by grauw** [comment]
> > 1011B: Noise.
> 
> Bit 2 in this example mutes the sound:
> 
> ```
> _MUSIC:_AUDREG(15,4):PLAY#2,"@12A1........"
> ```
> 
> The fact that PCM playback can be done by modifying f-num+block when this bit is set means that the PG is not actually held at 0 but at the specified f-num.

Or rather likely, it holds the previous phase at 0, and then adds the f-num as normal.

Additionally, the fact that we hear silence means that this flag applies to both modulators and carriers.

It seems most likely to me that this flag makes the operator ignore its current-phase input, but I think it could also be that it triggers the phase-reset which occurs after EG dump ends continuously.

**Comment by grauw** [comment]
I’ve attempted to also involve the modulator in producing PCM playback, however it was unsuccessful because depending on CPU write timing alignment with the YM2413 processing it can result in the carrier getting the updated fnum while the modulator still uses the old value. This causes quite arbitrary spikes during PCM playback. I elaborate on it [here](https://www.msx.org/forum/development/msx-development/limitations-msx-music?page=4#comment-371860).

For the sake of perfecting emulation, here’s the ROM which tests this. It has quite a noisy output due to this effect:

http://www.grauw.nl/etc/msx/joou-fm4.rom

p.s. @m9710797 thinks that the delayed update of the modulator is actually guaranteed to happen, a result of the moment the YM2413 processes the register rather than the moment it receives the data.

**Comment by grauw** [comment]
Test VGMs here: http://www.grauw.nl/etc/msx/fmpcm-test-vgm.zip

Edit: I’ve updated the archive with test programs and recordings from my turboR GT.

**Comment by MBilderbeek** [comment]
@grauw Nuke.YKT's OPLL core is now in openMSX master... can you help with testing?

**Comment by grauw** [comment]
This is working fine now with the Nuke.YKT OPLL core newly integrated in 4ea01c9.

I verified using my [FM PCM Player](http://www.grauw.nl/projects/fmpcm/) with both the method originally used in CGM#3, with my new method using one-quarter sine wave, three-quarter sine wave, as well as involving the modulator (checked both the bad case using channel 0 and the good case using channel alias 9).

**Comment by MBilderbeek** [comment]
I've also confirmed that the FMDEMO demos on CGM#3 are working fine now :)
