### ISSUE TITLE
[Bug] Caps Lock isn't working on Mac OS X [sf#410]

### ISSUE THREAD

**Issue by openMSX-import** [openMSX/openMSX#804]
**Reported by sd-snatcher on 2011-05-14 17:38 UTC**
Caps Lock isn't working at all.

Tried on Toshiba HX-10, Panasonic FS-A1GT, Sanyo PHC-70FD

openMSX-0.8.1 + NekoLauncher-1.2

Operating System: iMac C2D 2.66GHz, Mac OS-X 10.6.7, with Apple compact keyboard

Tried with a "crystal" Mac keyboard and it didn't work also.

**Comment by openMSX-import** [comment]
**Commented by mthuurne on 2011-05-15 14:14 UTC**
The problem is that the Quartz input driver sends a key release for Caps Lock immediately after the key press. Because of this, the MSX CAPS key is pressed for 0 Z80 ticks, so the MSX BIOS never sees it in the pressed state.

We could work around this in openMSX by going back to the old (prior to SDL 1.2.14) model for Caps Lock when running under OS X.

The ideal solution would be to fix SDL so it sends the Caps Lock release event when the key is actually released. However, I don't know how difficult this would be to implement or whether Quartz supports this at all.

**Comment by openMSX-import** [comment]
**Updated by mthuurne on 2011-05-15 14:14 UTC**
- **labels**:  --> General/misc
- **milestone**:  --> Next_release
- **assigned_to**: nobody --> mthuurne
- **summary**: Caps Lock isn't working --> Caps Lock isn't working on Mac OS X

**Comment by openMSX-import** [comment]
**Commented by mthuurne on 2011-05-15 15:27 UTC**
It does not seem to be possible to get a Caps Lock release event from Cocoa. So we should work around that in openMSX because the workaround in SDL is not compatible with key matrix polling.

**Comment by openMSX-import** [comment]
**Commented by mthuurne on 2011-05-15 16:48 UTC**
I worked around the problem by letting openMSX use the old SDL model of CAPS: "press" for CAPS on and "release" for CAPS off (SVN r12162).

There is still a problem though with re-syncing the tab status when openMSX regains focus.

**Comment by openMSX-import** [comment]
**Commented by sd-snatcher on 2013-05-12 20:31 UTC**
I tested it and the fix is working fine on 0.9.1-dev12913.

**Comment by MBilderbeek** [comment]
Discussed with mth:
`<mth> it says "There is still a problem though with re-syncing the tab status when openMSX regains focus."
<Quibus> the 'tab status'?
<Quibus> anyway, perhaps it's clearer to put that in a new ticket?
<Quibus> mth: is that a typo? 'tab'?
<mth> yeah, I don't know what I meant there
<mth> CAPS status maybe?
<Quibus> I guess so
<mth> anyway, I'm not going to fix that any time soon and since FRS was happy with the part that was fixed, I think it's OK to close
<Quibus> If someone finds it a problem he can create a new ticket then
`
So, let's close it.
