### ISSUE TITLE
[Bug] Incorrect mixing balance on mbstereo extension

### ISSUE THREAD

**Issue by sdsnatcher** [openMSX/openMSX#965]
mbstereo.xml currently features the following balance:

FM-PAC SW-M004:  -75
NMS-1205: +75

But this balance setting is impossible on real hardware, because:

1) The FM-PAC sound is never mixed in the NMS-1205 built-in audio output
2) The mixed at a low volume on the MSX own audio output, where the FM-PAC will output its sound too.

So, there are two possible stereo balances for a mbstereo device:

1) FM-PAC <-100>, NMS-1205 <+75>

2) Generic MSX-Music with built-in audio-out: <-100>, NMS-1205 <+100>.

Personally, I prefer the 2nd option as the balance is in equilibrium between left and right. Of course the <volume> parameter of both chips must be equal too.

**Comment by MBilderbeek** [comment]
Indeed, but I always thought this whole mbstereo config was intended as a non-realistic config, just a convenience thing. And with 75 instead of 100 it sounded a bit better. So that's why I chose that when I updated this configfile in 2007 (see commit 14f642e9).

At least this explains why it's like it is. I don't know whether I agree with this bug report though. Should it be realistic or not? There is no real 'mbstereo' device!

**Comment by sdsnatcher** [comment]
I thought the mbstereo was kind of a shortcut device to make the user life easier instead of having to add both a MSX-Music and a NMS-1205 cartridge and then having to set the balance manually.

If you prefer keeping the -75/+75 setting, I would only advice to adjust the "volume" parameters so both chips output the same volume. I wrote this in the original post, but the github ate the "volume" word probably because of the angle brackets.

**Comment by MBilderbeek** [comment]
Oh, you're right, I'll fix it.
