### ISSUE TITLE
diskmanipulator doesn't work with directories/volumes that contain spaces under OS X

### ISSUE THREAD

**Issue by javilm** [openMSX/openMSX#978]
**Issue:** attempting to import file from the physical MSX CF card into the emulator. openMSX fails to import the file if a directory in the pathname contains a space:

![openmsx_issue](https://cloud.githubusercontent.com/assets/2294068/10876316/f59c67a6-817e-11e5-907f-da911bdb7afb.png)

**Environment:**
- openMSX 0.12.0 under OS X 10.11.
- 128MB CompactFlash card with four 32MB partitions, all without labels

When the card is attached to an OS X machine via a USB card reader the partitions are mounted under /Volumes with the following names (all except the first containing spaces): 

/Volumes/Untitled
/Volumes/Untitled 1
/Volumes/Untitled 2
/Volumes/Untitled 3

Renaming the volume from "Untitled 2" to anything else without spaces works.

**Comment by MBilderbeek** [comment]
Hi,

The console is actually a Tcl shell. So using the Tcl way to escape spaces (i.e. use braces} does work:

```
diskmanipulator import hda1 {/Volumes/Untitled 2/DEV/MSX-UG/RACE/MAIN.C}
```

Please try :)
I'll have to check with Wouter if there's something we can do about this.

**Comment by m9710797** [comment]
The 'problem' (or 'feature') here is that the argument is interpreted as a Tcl list of filenames. This allows for example things like
    diskmanipulator import hda1 [glob *.c]
Here 'glob *.c' expands to a single argument that is a Tcl list of filenames ending in '.c' (for example 'foo.c bar.c'). Items in a Tcl list are separated by spaces. So the argument
   foo.c<space>bar.c
is interpreted as two filenames. And similarly
   /Volumes/Untitles<space>2/DEV/MSX-UG/RACE/MAIN.c
is interpreted as a list of 2 items.

You can have Tcl lists were the elements themselves contain spaces, but that requires escaping. MBilderbeek above gave an example for how to create a list containing a single element that has a space.

One easy trick to not have to know about Tcl escape rules is to use the 'list' command. This command takes a number of parameter (possibly only one) and returns a properly formatted list (with all required escaping) that contains each of the given parameters as a list-item. For example
   list "my first filename with spaces" "my second filename"
And in the context of the diskmanipulator you use it like this:
   diskmanipulator import hda1 [list "/Volumes/Untitled 2/DEV/MSX-UG/RACE/MAIN.c"]
In Tcl enclosing something in [] will substitute the result of the enclosed command in the outer command.

I hope it's clear now. I hope  you agree it's a feature (being able to use 'glob') rather than a bug. So I'm closing this item for now.

**Comment by javilm** [comment]
Thanks, that explains it.
