### ISSUE TITLE
openMSX can't handle UNC paths (at least not for the data dir)

### ISSUE THREAD

**Issue by MBilderbeek** [openMSX/openMSX#983]
This is what happens for a Windows user with his home dir on an UNC path:

```
SRAM file fs-a1gt.sram not found, assuming blank SRAM content.
Couldn't load firmwareswitch status: File "//fiesps0732/users$/xsoilatim/openMSX/persistent/Panasonic_FS-A1GT/untitled1/firmwareswitch" not found
SRAM file fs-a1gt.cmos not found, assuming blank SRAM content.
Couldn't save SRAM fs-a1gt.cmos (Error creating dir //fiesps0732).
Couldn't save SRAM fs-a1gt.cmos (Error creating dir //fiesps0732).
Couldn't save SRAM fs-a1gt.sram (Error creating dir //fiesps0732).
Couldn't save SRAM fs-a1gt.cmos (Error creating dir //fiesps0732).
```

**Comment by MBilderbeek** [comment]
This is a duplicate of #248.

**Comment by MBilderbeek** [comment]
I'd better reopen. This is a separate issue: no UNC paths supported. The other issue is that you can't easily change the home dir at all.

**Comment by mfeingol** [comment]
Please test this accordingly.  It seems to work here, in that UNC home path directories now seem to work.  But YMMV, since there's a lot of pathing code out there.

Two asides:

I recommend restoring the <PlatformToolset>v140</PlatformToolset> specifier to each VC project.  Otherwise, opening the solution with VS means projects will default to 2010 and will need to be specifically migrated each time.

I saw assertions in the two locations that do this:

#ifdef **SSE2**
    assert((uintptr_t(dataOut) & 15) == 0); // must be 16-byte aligned

As far as I can tell, this happens because the pointer is actually `int32_t dummyBuf[4];`, which isn't guaranteed to be 16-byte aligned (at least on Windows).

**Comment by mfeingol** [comment]
I would deprecate XP and Vista, personally.  But that's your call.
