### ISSUE TITLE
MIDI-in on Windows not working

### ISSUE THREAD

**Issue by MBilderbeek** [openMSX/openMSX#999]
See comments on https://www.msx.org/forum/msx-talk/general-discussion/converting-cx5m-cassettes-cas-format?page=4 and https://www.msx.org/forum/msx-talk/general-discussion/converting-cx5m-cassettes-cas-format?page=5

The user plugged in a MIDI keyboard to the MIDI-in, but it wasn't working.

**Comment by mthuurne** [comment]
There was a bug with the thread ID being read before it was written, which could possibly cause the opening of the MIDI device to fail, or MIDI messages to be delivered to the wrong thread. This bug was fixed in commit ad85714. However, someone should still test whether MIDI-in works on Windows after that fix.

**Comment by MBilderbeek** [comment]
Apparently the code cashes now when plugging something on MIDI-in on Windows, see for example: https://www.msx.org/forum/msx-talk/openmsx/midi-roland-a-49
